### PR TITLE
skipping pre 5.0 run records while processing run records from tms in…

### PR DESCRIPTION
**Pull request by gsps1**
… ops dashboard

JIRA : https://issues.cask.co/browse/CDAP-13451

### CODE REVIEW

**Comment by ecfm** [comment]
This PR LGTM, but I'm wondering whether there's a better approach instead of adding a property in every notification. For instance, maybe we can skip all the notifications until the first notification with STARTING status and with the ARTIFACT_ID property. Since notifications with other statuses preceding this notification won't have a matching notification with STARTING status, and those should not be included in the report

**Comment by gsps1** [comment]
I think the cost is low, if there are format changes between 5.0 and the next release is future and we want to handle that, its easier to do that using the version tag and take appropriate action.

**Comment by prinam** [comment]
Assigning to @poornachandra for another quick review

**Comment by poornachandra** [comment]
@gsps1 Please update the base branch to 5.0 and resolve the conflicts.

**Comment by gsps1** [comment]
@poornachandra updated the base branch, please take a look again, thanks.

**Comment by gsps1** [comment]
build running here https://builds.cask.co/browse/CDAP-RUT1570-1

**Review by poornachandra — APPROVED** [review]

**Comment by gsps1** [comment]
build green - https://builds.cask.co/browse/CDAP-RUT1570-4

**Pull request merged**
