### PR TITLE
CDAP-8277 add gson back to coprocessor jars

### PR DESCRIPTION
**Pull request by albertshau**

### CODE REVIEW

**Comment by gokulavasan** [comment]
LGTM 👍

**Comment by poornachandra** [comment]
Does this Gson jar version have to match that of HBase?

**Comment by albertshau** [comment]
not sure how hbase does its classloading, but this is just reverting the logic to what it was in 4.0.0. Our integration tests should catch issues.

**Comment by poornachandra** [comment]
Cool 👍

**Comment by albertshau** [comment]
http://builds.cask.co/browse/CDAP-DUT5361

**Pull request merged**
