### PR TITLE
[CDAP-6610] Propagate exceptions to allow deletion of Hdfs namespace

### PR DESCRIPTION
**Pull request by knazir**
Issue: https://issues.cask.co/browse/CDAP-6610
Build: http://builds.cask.co/browse/CDAP-RUT90-1

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
lgtm

**Comment by knazir** [comment]
Thanks @sreevatsanraman
Will test on a secure cluster and wait for the guild to be breen.

**Comment by anwar6953** [comment]
can you explain how this fixes the issue? What exception was being thrown that wasn't being caught before and is being caught now?

**Comment by anwar6953** [comment]
can you explain how this fixes the issue? What exception was being thrown that wasn't being caught before and is being caught now?

Edit: nvm, JIRA says `AccessDeniedException`.
Edit #2: but that is an IOException...

**Comment by knazir** [comment]
Yeah, just tried it.. doesn't seem to work. Will look into it.

**Comment by knazir** [comment]
@anwar6953 the original issue was actually already fixed with catching the `IOException`. This changes just allows the hdfs directory to be cleaned up if other exceptions occur. Tested it on a cluster and it works.

**Comment by knazir** [comment]
Guild is breen: http://builds.cask.co/browse/CDAP-RUT90-1

**Comment by anwar6953** [comment]
lgtm

**Pull request merged**
