### PR TITLE
[CDAP-17343] Added integration tests for pipeline config, scheduling, and properties

### PR DESCRIPTION
**Pull request by njbriggs**
* Adds E2E tests for pipeline engine config, pipeline scheduling, and a pipeline save-and-reload path
* Adds some `data-cy` tags too

### CODE REVIEW

**Comment by njbriggs** [comment]
Jira: https://issues.cask.co/browse/CDAP-17343
Build: https://builds.cask.co/browse/CDAP-UDUT850
E2E: https://builds.cask.co/browse/IT-UPD2196

**Comment by njbriggs** [comment]
It looks like the 2 failing tests are failing on develop. None of the tests I added are failing.

**Review by ajainarayanan — APPROVED** [review]
👍  LGTM!

**Comment by njbriggs** [comment]
This has the same E2E failure as develop, so I'm going to merge.

**Pull request merged**
