### PR TITLE
[CDAP-15058] Ability to limit concurrent runs

### PR DESCRIPTION
**Pull request by anew**
- adds a new cdap-site property to control the number of allowed concurrent program runs (excluding system apps)
- program lifecycle service checks how many runs are active and if it exceeds the limit, rejects the new run
- for a rejected run, create a run record with status "REJECTED". This is the only way a UI user would know about exceeding the limit
- in the UI, an error message is displayed when attempting to start too many runs. 
- if a scheduled run is rejected, that schedule is skipped with an error message in the logs (and the run record will be visible in the UI)
- Rejected status is displayed in red in the UI

### CODE REVIEW

**Comment by anew** [comment]
Screen Shot 2019-03-14 at 1 54 01 PM

**Comment by anew** [comment]
Screen Shot 2019-03-14 at 1 52 26 PM

**Comment by anew** [comment]
Screen Shot 2019-03-14 at 1 55 06 PM

**Review by chtyim — APPROVED** [review]
LGTM

**Comment by anew** [comment]
all builds passed:

- DUT: https://builds.cask.co/browse/CDAP-DUT6922
- ITM: https://builds.cask.co/browse/IT-ITM-153

will squash and merge now

**Pull request merged**
