### PR TITLE
[CDAP-16130] Adds e2e test for multi-select & context menus in pipeline studio

### PR DESCRIPTION
**Pull request by ajainarayanan**
- Fixes the logic to make sure start -> move -> end happens in that sequence in all environments during selection in pipeline studio
- Adds data-cy attributes for tests
- Adds tests for multi-select & context menu e2e tests
- Adds helpful commands to right click on canvas, nodes & to select everything between two nodes.
- Also fixes comment nodes to be draggable from the get-go (https://issues.cask.co/browse/CDAP-15081)

Build: https://builds.cask.co/browse/IT-UPD2107-1

### CODE REVIEW

**Comment by ajainarayanan** [comment]
The current failing tests are because somehow when the tests run in bamboo the current window doesn't seem to be focussed. If the window is not focussed the DOM APIs for accessing clipboard for copy/paste won't work (security feature). This leads to the tests failing in bamboo alone. If the same test is run locally it succeeds. 

I am still following up with Cypress team to see how we can successfully run tests that access clipboard in bamboo. Worst case we will run it locally and avoid running it in bamboo.

**Comment by ajainarayanan** [comment]
Latest mini build: https://builds.cask.co/browse/IT-UIE2EMINI20-1

**Review by elfenheart — APPROVED** [review]
👍 LGTM

**Comment by ajainarayanan** [comment]
https://builds.cask.co/browse/IT-UPD2107-18 Green build on e2e test. Closing this PR and cherry-picking the commit to the base branch.

**Pull request closed without merging**
