### PR TITLE
[CDAP-16219] Allow worker programs on remote runtime

### PR DESCRIPTION
**Pull request by CuriousVini**
Allow Worker program to run on remote runtime.

build: https://builds.cask.co/browse/CDAP-DUT7097-2

### CODE REVIEW

**Review by albertshau — COMMENTED** [review]
can you look at ProfileMetadataTest and see if there needs to be any changes made there? Otherwise lgtm.

**Review by albertshau — APPROVED** [review]

**Comment by CuriousVini** [comment]
I dont think these changes will affect that test. Also the build has passed.

**Comment by albertshau** [comment]
right, but should we add to that test for workers?

**Comment by CuriousVini** [comment]
current test is missing spark program type check. Modified test to support spark and worker

**Comment by CuriousVini** [comment]
yea, we can modify that test. Modified it for spark and worker program types.

**Review by albertshau — APPROVED** [review]

**Comment by CuriousVini** [comment]
https://builds.cask.co/browse/IT-ITM-238

**Pull request merged**
