### PR TITLE
[CDAP-9090] Improve schema handling of existing datasets as pipeline sinks

### PR DESCRIPTION
**Pull request by tonybach**
JIRA: https://issues.cask.co/browse/CDAP-9090

~~Still needs to do item number 4 in the specs (Display a confirmation box in the sink node, when changing from a non-existing dataset to an existing one).~~ Done

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@tonybach Noticed two things,

1. This is what happened for me,
  - Typed in the output schema (or had a non-existing dataset)
  - Changed to a dataset that doesn't have schema
  The result I expected was "No schema found" 

  But instead saw the schema that I typed got disabled and the tooltip said that schema belonged to the dataset the existing dataset. I believe we want to apply the schema (whether its empty or not) if its an existing dataset.

2. On a published pipeline the sink schema still showed this tooltip
screen shot 2017-06-30 at 12 06 36 pm
Don't think that should be shown there right?

**Comment by ajainarayanan** [comment]
Talked to @tonybach . Seeing couple of strange things,

1. Schema confirmation modal shouldn't appear in detailed view
2. When cloning a pipeline and opening a sink with an already existing dataset it shouldn't ask for a confirmation as the user hasn't changed the dataset. 
3. Going back from studio to detailed view still prompts the schema confirmation modal, but now the styling for the node configuration modal is mixed up.

**Comment by bdmogal** [comment]
This looks good to me. Will check with @ajainarayanan and merge tomorrow.

**Comment by bdmogal** [comment]
@tonybach I know we added a 2 sec delay to show the confirmation message. However, when a user presses enter, he shouldn't have a 2 sec delay. He should see the message immediately.

**Comment by bdmogal** [comment]
Other than the previous comment, this LGTM

**Review by bdmogal — APPROVED** [review]

**Pull request merged**
