### PR TITLE
[CDAP-9059] Fixes express to strip out referer from /backendstatus end point

### PR DESCRIPTION
**Pull request by ajainarayanan**
JIRA: https://issues.cask.co/browse/CDAP-9059
Bamboo build: http://builds.cask.co/browse/CDAP-DRC6120/latest

### CODE REVIEW

**Comment by bdmogal** [comment]
Tested that this works. Is there a jira for future improvement to not generate such a large URL? If so, LGTM.

**Comment by bdmogal** [comment]
Tested with the same dataset and 50 directives.

**Comment by ajainarayanan** [comment]
@bdmogal JIRA for a permanent(long term) fix: https://issues.cask.co/browse/CDAP-9061

**Comment by tonybach** [comment]
Code LGTM 👍

**Pull request merged**
