### PR TITLE
[CDAP-118866] Enables dataprep popover menu to be scrollable.

### PR DESCRIPTION
**Pull request by ajainarayanan**
- Adds a wrapper `ScrollableList` that will take an array of children and render only those that fit the window.

JIRA: https://issues.cask.co/browse/CDAP-11886

### CODE REVIEW

**Comment by bdmogal** [comment]
@ajainarayanan Can this scrolling be done on hover? It is awkward to click every time

**Comment by tonybach** [comment]
Code LGTM 👍

**Review by bdmogal — CHANGES_REQUESTED** [review]
The data preparation link vanishes from the global navbar when you are in pipelines view.

**Comment by ajainarayanan** [comment]
@bdmogal I don't the changes in this PR is related to it. I believe we have a brief break point range in browser size where the "Data Preparation" goes to the next line. I believe that is what you are seeing.

**Comment by ajainarayanan** [comment]
Demoed to @bdmogal and have a LGTM. Hence merging.

**Pull request merged**
