### PR TITLE
Feature/release notes 5.0

### PR DESCRIPTION
**Pull request by bdmogal**
https://builds.cask.co/browse/CDAP-DQB425-5

### CODE REVIEW

**Comment by rohitsinha54** [comment]
LGTM

**Comment by bdmogal** [comment]
Running build - https://builds.cask.co/browse/CDAP-DQB425-6. Please merge after verifying the page on the build.

**Comment by bdmogal** [comment]
@rohitsinha54 @gsps1 @sreevatsanraman please merge after reviewing https://builds.cask.co/artifact/CDAP-DQB425/shared/build-7/Docs-HTML/5.0.0-SNAPSHOT/en/reference-manual/release-notes.html#release-5-0-0

**Comment by bdmogal** [comment]
ready to review and merge

**Pull request merged**
