### PR TITLE
[CDAP-8826] remove version label from splash screen

### PR DESCRIPTION
**Pull request by elfenheart**
screen shot 2017-02-26 at 10 39 44 pm

JIRA: https://issues.cask.co/browse/CDAP-8827

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
Don't merge before the git tags are pushed. Will remove the on-hold label once it is done

**Comment by prinam** [comment]
@elfenheart pls remove the Intro to CDAP button.

**Comment by elfenheart** [comment]
screen shot 2017-02-27 at 12 22 40 am

**Comment by bdmogal** [comment]
lgtm

**Comment by sreevatsanraman** [comment]
LGTM

**Pull request merged**
