### PR TITLE
[CDAP-13994] Removes the ability to create stream from ResourceCenter modal

### PR DESCRIPTION
**Pull request by ajainarayanan**
JIRA: https://issues.cask.co/browse/CDAP-13994
Build: https://builds.cask.co/browse/CDAP-UDUT76

### CODE REVIEW

**Comment by tonybach** [comment]
Should we also remove the code for the Stream create wizard, since we no longer show it in the UI?

**Comment by ajainarayanan** [comment]
@tonybach No. We still haven't figured out the market. Some of the solutions still use it.

**Review by elfenheart — DISMISSED** [review]
👍 LGTM

**Review by tonybach — APPROVED** [review]
LGTM 👍

**Pull request merged**
