### PR TITLE
[CDAP-15726] Fix preview service to use secure store client modules

### PR DESCRIPTION
**Pull request by CuriousVini**

### CODE REVIEW

**Review by chtyim — APPROVED** [review]

**Comment by chtyim** [comment]
Actually does it different in SDK vs distributed mode?

**Comment by CuriousVini** [comment]
build: https://builds.cask.co/browse/CDAP-DUT7065

**Comment by CuriousVini** [comment]
yes, this change affect kubernetes runtime.

**Comment by CuriousVini** [comment]
> yes, this change affect kubernetes runtime.

**Comment by CuriousVini** [comment]
> Actually does it different in SDK vs distributed mode?

yes, this change only affects kubernetes runtime.

**Review by chtyim — APPROVED** [review]

**Pull request merged**
