### PR TITLE
[CDAP-12768] Fixes left panel store to not error our during import

### PR DESCRIPTION
**Pull request by ajainarayanan**
#### Issue:
Steps to reproduce,
- Go to pipeline studio
- Create a plugin template from left panel
- Once created import a pipeline via the `Import` button in the pipeline studio

After the last step import pipeline fails.

#### Fix:
- Fix templates, stored as part of plugins list in the left panel to have the same structure object structure as other plugins

JIRA: https://issues.cask.co/browse/CDAP-12768

### CODE REVIEW

**Review by elfenheart — APPROVED** [review]
👍  LGTM

**Comment by ajainarayanan** [comment]
There seems to be an error while adding templates from the left panel. This is caused by the complex schema editor in the template creation modal. Working on this fix.

**Comment by elfenheart** [comment]
The big chunk of the `plugin-template.html` change is moving out the html out of `<form>`. The `<form>` element causing the modal to refresh when you hit enter. The other change is simply changing the schema to `<my-output-schema>`

**Review by tonybach — APPROVED** [review]
LGTM 👍

**Review by bdmogal — APPROVED** [review]

**Pull request merged**
