### PR TITLE
(CDAP-13135) Remove more InputSupplier, OutputSupplier and derived usages

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Review by albertshau — APPROVED** [review]
lgtm

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Build passed https://builds.cask.co/browse/CDAP-DUT6672-6

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Squashed and merging.

**Pull request merged**
