### PR TITLE
CDAP-13625 tag dataproc clusters with the cdap version

### PR DESCRIPTION
**Pull request by albertshau**
When creating a dataproc cluster, add a label with the cdap version.
This will allow users to track which clusters were created by CDAP.

### CODE REVIEW

**Comment by albertshau** [comment]
https://builds.cask.co/browse/CDAP-RUT1527

**Comment by sreevatsanraman** [comment]
These changes Looks good to me. Are we doing only version in 5.0? The JIRA talks about mode (sandbox vs distributed). Will that come in a follow up PR

**Comment by albertshau** [comment]
I couldn't find existing logic for mode so I haven't added it in this PR, but if you know of something I could use, I can add it. Otherwise it will come in a future PR, likely in a future release.

**Comment by sreevatsanraman** [comment]
The logic exists for Ui where an env variable is set for sandbox vs cluster. 

Can you please open a Jira to track additional tagging that is needed after 5.0 before merging.

**Review by sreevatsanraman — APPROVED** [review]

**Pull request merged**
