### PR TITLE
Batch the application info and status call for control center; limit …

### PR DESCRIPTION
**Pull request by elfenheart**
…entities to 10

- Batch applications detail call and status call: O(n) to O(1)
- Limit entities to 10

### CODE REVIEW

**Review by ajainarayanan — APPROVED** [review]
👍 LGTM

**Comment by chtyim** [comment]
Does it also default the filter to "artifact" only?

**Comment by elfenheart** [comment]
Build: https://builds.cask.co/browse/CDAP-URUT211

**Comment by elfenheart** [comment]
have discussed with @chtyim, will keep the change as is, and revisit post release to optimize the artifact calls.

**Pull request merged**
