### PR TITLE
[CDAP-7469] Fix flaky SpamClassifierTest with Kafka publish retry

### PR DESCRIPTION
**Pull request by ecfm**
https://issues.cask.co/browse/CDAP-7469
http://builds.cask.co/browse/CDAP-RUT524-1

### CODE REVIEW

**Comment by ecfm** [comment]
Running more iterations on bamboo agent to verify the fix

**Comment by anwar6953** [comment]
btw, what's an example of a reason for failure to publish?

**Comment by ecfm** [comment]
@anwar6953 didn't figure out what caused Kafka publish to fail. This test only fails once in a while, so it's very hard to replicate

**Comment by anwar6953** [comment]
I mean, if you're sure that the test failure is due to the kafka publishing failure, and that it is a retry-able failure, then LGTM.

**Comment by ecfm** [comment]
Build is green, merging http://builds.cask.co/browse/CDAP-RUT524-1

**Pull request merged**
