### PR TITLE
Cherry pick from release/4.3

### PR DESCRIPTION
**Pull request by anwar6953**
There were a couple of commits on release/4.3 branch that were not on release/5.0.
Cherry-picking them here.

List of such PRs:
https://github.com/caskdata/cdap/pull/9999
https://github.com/caskdata/cdap/pull/10217
https://github.com/caskdata/cdap/pull/10122
https://github.com/caskdata/cdap/pull/10103

Edit: https://github.com/caskdata/cdap/pull/10141 was not cherry-picked due to @albertshau's comment below.

Build: https://builds.cask.co/browse/CDAP-RUT1594-1

### CODE REVIEW

**Comment by elfenheart** [comment]
👍 ui LGTM

**Comment by rohitsinha54** [comment]
10217 : LGTM. 
Thank you 💯

**Comment by albertshau** [comment]
CDAP-13430 was purposely not cherry-picked onto release/5.0 because it requires further testing. Let's leave it out of this.

**Comment by anwar6953** [comment]
@albertshau removed it; thanks for the heads up.

**Pull request merged**
