### PR TITLE
Merge release/3.4 to develop

### PR DESCRIPTION
**Pull request by rohitsinha54**
- Missed the point of using commit after resolving conflicts so have a custom message. 
- Resolved conflicts in all pom for cdap version keeping 3.5.0-SNAPSHOT
- Some JSON have 1.3.0 which I needs to be bumped to 1.4.0-SNAPSHOT and branches of other repo like tracker etc needs to bumped which I will do in a follow-up PR. In this doing straight merge without an content change.

### CODE REVIEW

**Comment by anwar6953** [comment]
all the 1.3.0 should probably be 1.4.0-SNAPSHOT, on develop.
Were there conflicts for these json files?

**Comment by rohitsinha54** [comment]
@anwar6953 : No there were no conflicts in these JSON. Keeping them as it is to keep this a straight merge. Will bump these in a follow-up PR as soon as I merge this.

**Comment by rohitsinha54** [comment]
BUILD: http://builds.cask.co/browse/CDAP-DUT4096-1

**Comment by anwar6953** [comment]
I think its fine to have the modifications to the json files as its own commit (after the merge commit) in this PR.

**Comment by rohitsinha54** [comment]
@wolf31o2 @dereklwood Can you please look at the following files and tell me what version they should point to. I think they should be current release version, correct me if I am wrong. 
1. cdap-distributions/src/emr/install.sh
2. cdap-distributions/src/hdinsight/install.sh
3. cdap-distributions/src/packer/files/cdap-sdk.json

**Comment by wolf31o2** [comment]
1. It should be the last version that was supported on EMR, prior to dropping support for HBase 0.94 and should never be changed
2. This should be the latest release version, as it pulls from release repositories
3. This must be the last release version

**Comment by anwar6953** [comment]
lgtm

**Pull request merged**
