### PR TITLE
[CDAP-7636] Rename system.tx.timeout to system.data.tx.timeout

### PR DESCRIPTION
**Pull request by anew**
subject says it all

### CODE REVIEW

**Comment by chtyim** [comment]
You might consider moving the constant and add a method in `SystemArguments`.

**Comment by anew** [comment]
@chtyim I addressed your comment, please take another look.

**Comment by chtyim** [comment]
LGTM

**Comment by anew** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT5068

**Comment by anew** [comment]
squashing and merging

**Pull request merged**
