### PR TITLE
Directive Dropdown

### PR DESCRIPTION
**Pull request by elfenheart**
## Features:
- Directive dropdown
- Split Column
- Delete Column
- Fill Empty or Null
- User should be able to expand directive dropdown
- When user scroll horizontally, the dropdown should attempt to adjust position to fit in the screen. Once it overflows, dropdown will be hidden
- Clicking outside dropdown will close the dropdown
- User should be able to toggle the expansion of the expandable directives

### JIRAs:
- https://issues.cask.co/browse/WRANGLER-77
- https://issues.cask.co/browse/WRANGLER-49
- https://issues.cask.co/browse/WRANGLER-54

### Incomplete
For [WRANGLER-77](https://issues.cask.co/browse/WRANGLER-77):
- Right click behavior
- Hover behavior to show and hide the dropdown toggle

### CODE REVIEW

**Comment by bdmogal** [comment]
@elfenheart the drop down should show up a little to the right:
image


Also, is it possible to somehow indicate that the down arrow is clicked (darken a rectangle around it, just like the logs button in Studio?

**Comment by bdmogal** [comment]
@elfenheart pressing ``Esc`` should remove the dropdown?

**Comment by bdmogal** [comment]
@elfenheart if there is a scroll bar, the down arrow gets hidden:
image

Is there anything that can be done?

**Comment by elfenheart** [comment]
@bdmogal we can add more right padding ~15px to offset the scroll bar

**Comment by bdmogal** [comment]
@elfenheart two problems:
1. After the drop down is activated, you have click "outside" to remove it. Can we also allow removing using ``Esc`` and clicking the down arrow again?
2. It seems like the drop-down "remembers" the last chosen option. I don't think it should

See attached gif for both problems

remember_dropdown

**Comment by bdmogal** [comment]
@elfenheart when you have clicked on a menu item, a submenu opens. Then when you hover over a different menu item, the submenu still remains open:
image


If the way to open a submenu is by clicking, should we remove the hover state of changing the background color?

**Comment by bdmogal** [comment]
@elfenheart the submenu dropdown seems to start at the top. Can it start at the same height as the menu item?

image

**Comment by bdmogal** [comment]
@elfenheart Split to Columns has a horizontal rule between the actions and buttons:
image

But Fill Null or Empty Cells is missing that rule:
image

**Comment by bdmogal** [comment]
also regarding my previous comment, should we add a placeholder for the Fill Empty Cells box?

"Enter default value"

Also the header should be the same as the menu item? "Fill Null or Empty Cells"

**Comment by bdmogal** [comment]
@elfenheart Instead of increasing the font size for the submenu title, can we just keep the same font size, but increase the weight?

**Comment by bdmogal** [comment]
@elfenheart when either:
1. The delimiter is not entered when Custom Delimiter is selected; or
2. The default value for filling Null or empty cells is not entered;

The Ok button should be disabled.

**Comment by bdmogal** [comment]
@elfenheart re-clicking on the menu item should remove the submenu

**Comment by bdmogal** [comment]
@elfenheart few more comments:
1. Split to columns -> Split to columns (Regex). Also use the `split-to-columns` directive for this, not `parse-as-csv`
2. Placeholder for Fill Null or Empty -> "Enter value to set"
3. When focus is on the text box, hitting ``Enter`` should apply the directive.
4. Change Ok button to Apply.

**Comment by leacd** [comment]
There seems to be a lag between the user clicking [Apply] and the transformation being applied. The lag is sometimes 1 sec or more, making the experience disorienting to the user. Can we add a visual indicator next to the directive itself (animated loading icon) to cue the user that the system is working in the background? This should be implemented across all directives

**Comment by leacd** [comment]
Column drop down should be opening on the right of the column, so that information is not covered. This is not as critical today, as the drop down is quite small (three directives) but it will become more important as the list of directives grow.

**Comment by leacd** [comment]
Interactions that are missing:
- The drop down icon is always visible, instead of being revealed on hover.
- The user should be able to see the drop down by right-clicking the header of the column.

**Comment by leacd** [comment]
I created a jira for the few interactions that were not addressed with this released. https://issues.cask.co/browse/WRANGLER-79
Everything else LGTM. Merge.

**Comment by elfenheart** [comment]
Build: http://builds.cask.co/browse/CDAP-DRC6064-9

**Pull request merged**
