### PR TITLE
[CDAP-8494] Fix back button while navigating from old to new UI

### PR DESCRIPTION
**Pull request by ajainarayanan**
- Fixes navigating to hydrator list view from anywhere to navigate back to the same state on clicking browser back button
- Fixes old UI to handle browser back button to come back to the same state where the user left.

Corresponding old UI change: d54d623a1646d3f285b99439d25ff87fbeb3753e

#### Note:
- I couldn't reproduce the issue mentioned in the bug however noticed an issue in the way we access ACCESS_TOKEN from the cookie. Fixed that and still couldn't reproduce the issue. @elfenheart @tonybach please pull this down and see if you are able to reproduce the original issue.

### CODE REVIEW

**Comment by tonybach** [comment]
When I go to the Hydrator list view from Tracker/metadata, clicking back doesn't take me back to Tracker?

EDIT: Nvm, forgot to run `gulp build`. It works after I did that.

**Comment by elfenheart** [comment]
@ajainarayanan which JIRA mentioned the ACCESS_TOKEN issue?

**Comment by elfenheart** [comment]
The original issue was fixed when we add routing to a specific namespace to the old UI. However the problem still exist when user go to Administration page without a namespace context, go to old UI  and now user cannot click back button to go back to the Administration page

**Comment by elfenheart** [comment]
👍  LGTM

**Comment by ajainarayanan** [comment]
@tonybach @elfenheart Need to unit tests for url-generator too but that requires pulling out the actual functions into testable units and then add tests for them individually. This required minor refactor of url-generator which I didn't want to do in this PR. Tests these will come in another PR.

**Pull request merged**
