### PR TITLE
Remove UpgradeDatasetServiceManager and only user UpgradeToolTest

### PR DESCRIPTION
**Pull request by deepakwadhwani**
After CDAP-7835, UpgradeDatasetServiceManager is not required. 
Build: http://builds.cask.co/browse/CDAP-DUT5545

### CODE REVIEW

**Comment by anew** [comment]
LGTM

**Comment by deepakwadhwani** [comment]
Build failing with unrelated tests. YarnRMHAOperationalStatsTest failed twice which is also failing on develop. Will run another build to check for a successful build.

**Comment by anew** [comment]
I just merged the fix for that. If you rebase on develop, your build should pass now

**Comment by deepakwadhwani** [comment]
Getting failure at [TransactionServiceTest testHA] Looks unrelated, investigating root cause. http://builds.cask.co/browse/CDAP-DUT5545-4

**Comment by anew** [comment]
This is same as https://issues.cask.co/browse/CDAP-8881

**Comment by deepakwadhwani** [comment]
clean build: http://builds.cask.co/browse/CDAP-DUT5545-5

**Pull request merged**
