### PR TITLE
[CDAP-8951] - Fix Metadata entity detail page has wrong font color for Business Tags 

### PR DESCRIPTION
**Pull request by sushil-car**
https://issues.cask.co/browse/CDAP-8951

### CODE REVIEW

**Comment by sushil-car** [comment]
Preferred tags are also displayed inside Business tag section, but we haven't changed color for Preferred tags.
Shall I change its color same as User Tags in Business Tag section ?

**Review by ajainarayanan — CHANGES_REQUESTED** [review]
@sushiladokar If we are changing the text color we need to change the `x` button color too. Right now close button is almost invisible.

**Comment by ajainarayanan** [comment]
👍 LGTM

**Comment by ajainarayanan** [comment]
Created against release/4.1 https://github.com/caskdata/cdap/pull/8437

**Pull request closed without merging**
