### PR TITLE
[CDAP-9235] DataPrep Workspace Tabs

### PR DESCRIPTION
**Pull request by elfenheart**
JIRA: https://issues.cask.co/browse/CDAP-9235

### CODE REVIEW

**Review by ajainarayanan — APPROVED** [review]
Code 👍 LGTM

**Comment by ajainarayanan** [comment]
@elfenheart Noticed a few things,

Not sure if they were already talked about,

1. Clicked `Delete` button couple of times when trying to create/upload data to a workspace 
screen shot 2017-04-03 at 4 54 21 pm

2. In active tab the workspace name seems to be pushed down a little.
workspacename

3. Should we show tooltips on al workspace names? Right now the tab sizes seem to be small enough that it can't take more than 4 characters. This forces the user to click to know the namespace name.

**Comment by bdmogal** [comment]
About 2. Move the Record Delimiter field left aligned below the file upload.
Upload button goes below it. Let's turn the upload button to the main call to action blue in CDAP. "Delete this workspace" button goes to the right, vertically aligned with the Upload button.

**Comment by bdmogal** [comment]
One last change. Let's change the modal header to ``Workspace '<workspace-name>' properties'

**Comment by elfenheart** [comment]
demoed to @bdmogal

**Pull request merged**
