### PR TITLE
[CDAP-11730] Remove newline delimiter so that XML and JSON files can be parsed correctly

### PR DESCRIPTION
**Pull request by sameetandpotatoes**

### CODE REVIEW

**Comment by elfenheart** [comment]
@sameetandpotatoes we have eslint to check codestyle in the UI. If you run `npm run cdap-prod-build`, you'll see these errors.

```
/cdap/cdap-ui/app/cdap/components/DataPrepConnections/UploadFile/index.js
  49:42  warning  Trailing spaces not allowed  no-trailing-spaces
  52:1   warning  Trailing spaces not allowed  no-trailing-spaces
```

**Comment by sameetandpotatoes** [comment]
Removed eslint errors.

**Comment by elfenheart** [comment]
@sameetandpotatoes It works with JSON, but not with XML files. Can you see what `e[0].type` actually returns for XML?

**Comment by sameetandpotatoes** [comment]
`e[0].type` for XML files is `text/xml`.

Tested both `XML` and `JSON` files now by uploading and verifying that `\n` disappears (and reappears when uploading a file of a different type). 

There are no eslint errors.

**Review by elfenheart — APPROVED** [review]
👍  LGTM

**Pull request merged**
