### PR TITLE
Updated test case to wait for COMPLETED state.

### PR DESCRIPTION
**Pull request by sagarkapare**
In this test case we were starting the Workflow and waiting for STOPPED status. However there is a race in which it is possible that the program is started but the runtime info is not yet added. In this case the status will return STOPPED, causing test case to continue.

### CODE REVIEW

**Comment by sagarkapare** [comment]
Note that this race would only happen if the program is started and we wait for STOPPED using status endpoint. If program is started, then we wait for RUNNING, then we stop the program and then wait for STOPPED then this race would not happen.

**Comment by sagarkapare** [comment]
https://builds.cask.co/browse/CDAP-RUT526-1

**Comment by anwar6953** [comment]
LGTM

**Comment by sagarkapare** [comment]
Build is green - https://builds.cask.co/browse/CDAP-RUT526-4. Merging.

**Pull request merged**
