### PR TITLE
[🍒] fix maxConcurrentRuns (to 6.9)

### PR DESCRIPTION
**Pull request by GnsP**
Cherrypick of #15585 to release/6.9

### CODE REVIEW

**Review by itsankit-google — CHANGES_REQUESTED** [review]
Please bump snapshot in `release/6.9` branch: https://github.com/cdapio/cdap/blob/bee9c8eeb34e2d2a070f5916a99902fdb9124172/pom.xml#L25

**Comment by GnsP** [comment]
> Please bump snapshot in `release/6.9` branch:
> 
> https://github.com/cdapio/cdap/blob/bee9c8eeb34e2d2a070f5916a99902fdb9124172/pom.xml#L25

done

**Comment by itsankit-google** [comment]
> > Please bump snapshot in `release/6.9` branch:
> > https://github.com/cdapio/cdap/blob/bee9c8eeb34e2d2a070f5916a99902fdb9124172/pom.xml#L25
> 
> done

The next snapshot version should be `6.9.6-SNAPSHOT` and it needs to be bumped up in all sub-modules as well.

sample PR: https://github.com/cdapio/cdap/pull/15529/files

First we bump snapshot in `cdap-ui`, otherwise build will always fail.

**Comment by GnsP** [comment]
> > > Please bump snapshot in `release/6.9` branch:
> > > https://github.com/cdapio/cdap/blob/bee9c8eeb34e2d2a070f5916a99902fdb9124172/pom.xml#L25
> > 
> > 
> > done
> 
> The next snapshot version should be `6.9.6-SNAPSHOT` and it needs to be bumped up in all sub-modules as well.
> 
> sample PR: https://github.com/cdapio/cdap/pull/15529/files
> 
> First we bump snapshot in `cdap-ui`, otherwise build will always fail.

Understood. Made the changes. 
Not updating cdap-ui in this commit, as there are no ui changes.

**Comment by itsankit-google** [comment]
> > > > Please bump snapshot in `release/6.9` branch:
> > > > https://github.com/cdapio/cdap/blob/bee9c8eeb34e2d2a070f5916a99902fdb9124172/pom.xml#L25
> > > 
> > > 
> > > done
> > 
> > 
> > The next snapshot version should be `6.9.6-SNAPSHOT` and it needs to be bumped up in all sub-modules as well.
> > sample PR: https://github.com/cdapio/cdap/pull/15529/files
> > First we bump snapshot in `cdap-ui`, otherwise build will always fail.
> 
> Understood. Made the changes. Not updating cdap-ui in this commit, as there are no ui changes.

It is not related to the changes made in ui but this is how it works right now, first we need to merge a PR like this: https://github.com/cdapio/cdap-ui/pull/1171 in `cdap-ui` repo and then do the snapshot bump in cdap.

**Review by itsankit-google — APPROVED** [review]

**Pull request merged**
