### PR TITLE
[CDAP-7475] Remove Deprecated setInput/setOutput methods

### PR DESCRIPTION
**Pull request by anew**
Built this locally and hydrator against it. all passed.

Fix for: https://issues.cask.co/browse/CDAP-7475

### CODE REVIEW

**Comment by anew** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DRC4774

**Comment by awholegunch** [comment]
LGTM

**Comment by anwar6953** [comment]
lgtm

**Comment by anew** [comment]
squashing and merging.

**Pull request merged**
