### PR TITLE
CDAP-8206 adding documentation on program retry policies

### PR DESCRIPTION
**Pull request by albertshau**
Running as a Quick Build: http://builds.cask.co/browse/CDAP-DQB277-2

Page of interest: http://builds.cask.co/artifact/CDAP-DQB277/shared/build-2/Docs-HTML/4.1.0-SNAPSHOT/en/developers-manual/advanced/program-retry-policies.html

### CODE REVIEW

**Comment by awholegunch** [comment]
I've edited the file; please check my changes. Started a Quick Build. I will review the results before concluding my review.

**Comment by albertshau** [comment]
changes lgtm

**Comment by awholegunch** [comment]
The build failed due to bad links. I have:
- corrected the links
- changed the file name to follow our pattern of filename matching the title as closely as possible
- added more references to the information in the higher-level index files
- changed the formatting a bit on the page to improve readability

**Comment by albertshau** [comment]
changes lgtm

**Pull request merged**
