### PR TITLE
Feature/merge 36 to develop

### PR DESCRIPTION
**Pull request by CuriousVini**
- Resolved version conflicts
- `HBaseQueueAdmin` had conflicts
  - Kept changes from release/3.6
  - made changes to dropAllInNamespace to use`namespaceId` instead of `namespaceId.toEntityId()`
  - made changes to upgrade() line`DatasetId stateStoreId = createStateStoreDataset(cdapNamespace);`. Instead of using `Id.DatasetInstance`, `DatasetId` is used.
- Conflicts in `MetricsDataMigrator` - kept changes from release/3.6

Build: http://builds.cask.co/browse/CDAP-DUT4925-1

### CODE REVIEW

**Comment by anwar6953** [comment]
Just curious - what changes went into develop (for HBaseQueueAdmin), that conflicted with the 3.6 changes?

**Comment by CuriousVini** [comment]
@anwar6953 `HBaseQueueAdmin` has methods `upgrade()` and `dropAllInNamespace()` methods. The changes for those methods are same as present in PR description. Made changes to alignment of description format to make it more clear

**Comment by anwar6953** [comment]
I see; ok. I thought they were separate bullet points.
It's clear now.

**Review by anwar6953 — APPROVED** [review]
lgtm

**Comment by CuriousVini** [comment]
Build is green. Squashing and merging.

**Pull request merged**
