### PR TITLE
[CDAP-8660] - Fix for Line height of textbox for adding tags in new UI is not sufficient to show some characters

### PR DESCRIPTION
**Pull request by sushil-car**
https://issues.cask.co/browse/CDAP-8660

### CODE REVIEW

**Comment by sushil-car** [comment]
tags input

**Comment by sushiladokar** [comment]
Increased the padding-bottom of textbox only for overview-meta-section container

**Comment by sushil-car** [comment]
input tag details viw

**Comment by sushil-car** [comment]
Increased the margin-bottom for tag input textbox only for overview-meta-section container

**Pull request merged**
