### PR TITLE
[CDAP-7463] Removes footer from CDAP, Tracker, and Hydrator

### PR DESCRIPTION
**Pull request by PGuimarais**
removes footer 3

removes footer 1

removes footer 2

JIRA: 
https://issues.cask.co/browse/CDAP-7463

Bamboo Build:
http://builds.cask.co/browse/CDAP-DRC4705

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@PGuimarais we still query for version and have copyrightyear in controller. If we are removing the footer should we remove those things too?

**Comment by PGuimarais** [comment]
@ajainarayanan  we're going to keep it for now

**Comment by ajainarayanan** [comment]
In Hydrator.
screen shot 2016-10-21 at 1 00 50 pm

screen shot 2016-10-21 at 1 03 30 pm

**Comment by ajainarayanan** [comment]
Footer gap in Tracker
screen shot 2016-10-21 at 1 10 52 pm

**Pull request closed without merging**
