### PR TITLE
[CDAP-19342] Tethering: Polling should return a batch of messages

### PR DESCRIPTION
**Pull request by rmstar**
Fixed a bug where only 1 message was returned on every poll.

### CODE REVIEW

**Review by nliu132 — APPROVED** [review]

**Review by CuriousVini — APPROVED** [review]
LGTM for this change.
Shall we also reduce polling interval to be 1second or lower? 10 seconds seems way too long. Wondering if thats how we are trying to throttle the inflow to a CDAP on kubernetes cluster?

**Comment by rmstar** [comment]
> Shall we also reduce polling interval to be 1second or lower? 

Only downside of lowering the polling interval is that we would generate more network traffic. Also, if CDF is unreachable, we would spam the logs with more errors - might need to look into rate limiting error logging in the tethering agent. 

We can reduce the polling interval if we find that 10 second interval is causing too much latency in starting pipeline runs/limits scalability of tethering.

**Comment by CuriousVini** [comment]
> > Shall we also reduce polling interval to be 1second or lower?
> 
> Only downside of lowering the polling interval is that we would generate more network traffic. Also, if CDF is unreachable, we would spam the logs with more errors - might need to look into rate limiting error logging in the tethering agent.
> 
> We can reduce the polling interval if we find that 10 second interval is causing too much latency in starting pipeline runs/limits scalability of tethering.

Could we rely on appfabric concurrent launch capability to throttle that? 10 seconds for fetching messages seems too long. OR may be good to keep it configurable?

**Comment by rmstar** [comment]
Appfabric concurrent launch capability will help with throttling too many concurrent launches, but it doesn't fix increase network traffic (polling is done by tethering agent) caused by frequent polling.
But I do agree that 10 seconds seems too much, will increase the default in a subsequent PR.
The polling interval is configurable using `tethering.agent.connection.interval.secs` config. https://github.com/cdapio/cdap/blob/develop/cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java#L1996

**Pull request merged**
