### PR TITLE
(CDAP-9301) Improve message when there is no data in a workspace

### PR DESCRIPTION
**Pull request by bdmogal**
image

Jira: [CDAP-9301](http://issues.cask.co/browse/CDAP-9301)

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
Do we need some? also what's transformations? We are calling it data prep. 

How about? - "Please upload data to begin data prep."

**Comment by bdmogal** [comment]
Eventually, we want to get rid of the term 'prep'. Every directive you apply is a transformation.

**Comment by bdmogal** [comment]
Removed 'some'

**Comment by sreevatsanraman** [comment]
We can change the message when we change the product. Currently on top it says Data preparation and in the bottom it is transformation. It doesn't look consistent to me.

**Comment by bdmogal** [comment]
Data preparation is the name of the functionality. But when we use the word 'prepare', I don't think we are conveying what we're doing crisply, in common english.

**Comment by bdmogal** [comment]
This is a message, so I prefer using  common English. :)

**Comment by sreevatsanraman** [comment]
How about "data preparation"

**Comment by nitinmotgi** [comment]
Line 1 : "Start by uploading data to this workspace", 
Line 2 : button will say : ```Upload```

**Comment by bdmogal** [comment]
@root @sreevatsanraman updated. Please review again

**Comment by nitinmotgi** [comment]
👍

**Pull request merged**
