### PR TITLE
(CDAP-11626) Fix the Spark ShutdownHook removal in SDK

### PR DESCRIPTION
**Pull request by chtyim**
- Correctly remove the Spark ShutdownHookManager from Hadoop
ShutdownHookManager to avoid permgen leakage

### CODE REVIEW

**Comment by anwar6953** [comment]
LGTM

**Review by CuriousVini — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Building https://builds.cask.co/browse/CDAP-RUT1009

**Comment by chtyim** [comment]
Build passed

**Pull request merged**
