### PR TITLE
Feature/merge rc2 to 35

### PR DESCRIPTION
**Pull request by wolf31o2**
This is a merge of the `release/3.5.0-0.rc2` branch into `release/3.5` with the conflicts resolved. Please, check `cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java` carefully, as that was the only file with conflicts.

### CODE REVIEW

**Comment by wolf31o2** [comment]
This replaces #6303

**Comment by sagarkapare** [comment]
@wolf31o2 We should not require to merge the rc2 to release/3.5.
1. Changes made by @chtyim for CDAP-6168 should already in release/3.5
2. We do not need the changes corresponding to upgrading CDAP version which was done for RC only.
3. CDAP-6864 should already be in the release/3.5 as well.

**Comment by wolf31o2** [comment]
@sagarkapare OK. My changes in rc2 for the VM aren't in 3.5 and there were some differences in `cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java` between rc2 and 3.5 that look like they're needed.

I'll create a new PR to cherry-pick my changes. Can you check the LineageWriterDatasetFramework?

**Comment by wolf31o2** [comment]
My cherry-picked fixes are in #6305 

You can close this after looking at that one Java file.

**Comment by sagarkapare** [comment]
Thanks @wolf31o2. Closing this PR since the required CDAP changes are already release/3.5

**Pull request closed without merging**
