### PR TITLE
[CDAP-9541] Have directives popover always appear on the right of dropdown icon for consistency

### PR DESCRIPTION
**Pull request by ajainarayanan**
- Today we have popover menu always appear on the left of the dropdown icon (most overlapping the contents of the column in which it is being operated on). 
- This PR changes that to have the popover menu appear always on the right and adapt to columns on the far right (appear left of the dropdown icon) to be consistent with the popover menu that will appear on right click on column header (to be added in future PRs)

JIRA: https://issues.cask.co/browse/CDAP-9541
Bamboo build: https://builds.cask.co/browse/CDAP-DRC6413/latest

### CODE REVIEW

**Comment by tonybach** [comment]
Code LGTM :+1:

**Comment by bdmogal** [comment]
Can we fix this related (ok, I'm stretching the bounds of related, but still :) ) issue:

The format submenu at my resolution is going beyond the screen, and there's no way to scroll to reach its end. It could use the same treatment as the parse submenu:

image

**Comment by elfenheart** [comment]
👍  Code LGTM

**Comment by leacd** [comment]
LGTM

**Pull request merged**
