### PR TITLE
Bumping version to 4.1.2-SNAPSHOT

### PR DESCRIPTION
**Pull request by Nishith**
Remaining files with 4.1.1

cdap-distributions/src/emr/install.sh
cdap-distributions/src/hdinsight/pkg/install.sh
cdap-distributions/src/hdinsight/pkg/mainTemplate.json
cdap-distributions/src/packer/cdap-sdk-ubuntu16-with-uri.json

### CODE REVIEW

**Comment by wolf31o2** [comment]
Everything under cdap-distributions/src/packer should move to 4.1.2 (or 4.1.2-1, if iteration's required).

**Comment by wolf31o2** [comment]
Also, cdap-distributions/src/packer/files/cdap-sdk.json has 4.1.2-SNAPSHOT, which is invalid. It should be match the upcoming *package* version 4.1.2-1, not Java versioning.

**Comment by Nishith** [comment]
Addressed comments. Please take another look.

**Review by wolf31o2 — APPROVED** [review]
cdap-distributions 👍 LGTM

**Pull request merged**
