### PR TITLE
Updated the MD5 hash.

### PR DESCRIPTION
**Pull request by sagarkapare**

### CODE REVIEW

**Comment by sagarkapare** [comment]
Quick doc build passes here - http://builds.cask.co/browse/CDAP-DQB35-3

**Comment by rohitsinha54** [comment]
We should also verify if the example code changes need line number changes in docs.

**Comment by sagarkapare** [comment]
@rohitsinha54 Updated the line numbers. Please take a look again.

**Comment by rohitsinha54** [comment]
LGTM  assuming that the new lines numbers are verified to render the same code snippet.

**Comment by sagarkapare** [comment]
Verified the line numbers manually. Squashing and merging.

**Pull request merged**
