### PR TITLE
[HYDRATOR-1296] - Add option "All Fields" to input-field-selector widget

### PR DESCRIPTION
**Pull request by sushil-car**
https://issues.cask.co/browse/HYDRATOR-1296

### CODE REVIEW

**Comment by sushil-car** [comment]
Added the All Fields option.
But its throwing below error when publishing pipeline:
   java.util.concurrent.ExecutionException: java.lang.RuntimeException: Exception while configuring plugin of type transform and name Wrangler for stage Wrangler: Field all is not present in the input schema

**Review by ajainarayanan — COMMENTED** [review]
@sushiladokar Two things,
- There should be an option to allow users to choose 'All' from the dropdown. All plugins might not support that option
- In our current case we need it as `*` instead of `all`.

**Comment by sushil-car** [comment]
To make its value to either * or any other value depending on plugin, shall I add a attribute in widget-container directive call or can it be added to field variable which we send to data-myconfig

**Comment by ajainarayanan** [comment]
@sushiladokar let us keep it simple,

1. `enableAllOption` can be set to true to add `All` option to the dropdown.
2. `allOptionValue` can be set to `*` or `All` by the user. 

If `enableAllOption` is set to true and if the `allOptionValue` is not set, the UI can default to `*`. This way we can achieve two things,
- allow users to configure to show or hide `All` option
- allow users to specify a custom value for `All` dropdown option needed by the backend..

A sample widget json would look like this,

```
{
  "widget-type": "input-field-selector",
  "widget-attributes": {
    "enableAllOption": true,
    "allOptionValue": "*"
  },
  "label": "Custom Reference Name",
  "name": "pluginProp1",
}
```

Case where `enableAllOption` is specified but not `allOptionValue`,

```
{
  "widget-type": "input-field-selector",
  "widget-attributes": {
    "enableAllOption": true
  },
  "label": "Custom Reference Name",
  "name": "pluginProp1",
}
```
in the above case UI will default to `*`.

Hope that is clear. @nitinmotgi can confirm on the widget attribute names.

**Comment by ajainarayanan** [comment]
@sushiladokar Have fixed the case where `input-field-selector` doesn't have `widget-attributes` field in widget json.

**Comment by elfenheart** [comment]
👍  LGTM

**Pull request merged**
