### PR TITLE
in  cdap 4.2 when use system artifact kafka-plugin 1.7  at  preview stage, many kafka relative class not found excepiton occurs  how to resolve that problem?

### PR DESCRIPTION
**Pull request by dongbin86**

### CODE REVIEW

**Comment by dongbin86** [comment]
qq 20170613214238

**Comment by sreevatsanraman** [comment]
Please use cdap-user@googlegroups.com to discuss any issues. Pull requests is for code contributions and not for raising questions. We have fixed this issue in the following pull request https://github.com/hydrator/kafka-plugins/pull/11 and the fix will be available with the next release of CDAP.  Alternatively, you can build kafka plugins from source and use it in the meantime.

**Comment by dongbin86** [comment]
@sreevatsanraman  how to join   cdap-user@googlegroups.com，I sent email to that group，but failed，need join that group first ？

**Comment by prinam** [comment]
Hi @sumpan you shouldn't need to join the group before sending an email. Please try re-sending the email to cdap-user@googlegroups.com - it **may** have got marked as spam previousl. Alternately, you can also join the group and send the email - it then may not get marked as spam.

**Pull request closed without merging**
