### PR TITLE
Cherry pick of the documentation update in develop branch

### PR DESCRIPTION
**Pull request by awholegunch**
Running as a Quick Build: http://builds.cask.co/browse/CDAP-DQB176-3 (Passes)

Running as a Docs Develop Build: http://builds.cask.co/browse/CDAP-DDB52-1 (Passes)

### CODE REVIEW

**Comment by wolf31o2** [comment]
What's edited?

**Comment by awholegunch** [comment]
"Edited" was probably the wrong word. "Consolidated" would be better, as it is a number of different commits (and PRs) added together. If there is any difference, that would be in the settings in the `vars` file. The `functions.sh` script was something else in earlier branches.

**Comment by wolf31o2** [comment]
I guess I am asking you to explicitly point out the changes, so those can be reviewed, specifically, and also how they interact with the whole.

**Comment by awholegunch** [comment]
"On-hold" until https://issues.cask.co/browse/CDAP-7712 is resolved.

**Comment by awholegunch** [comment]
I have added to this PR so that the only differences between this branch and develop are 
- branch settings (in the `var` file); 
- settings for MD5 hashes in the `build.sh` files; 
- a few copyright dates; 
- `common_build.sh` has a different path to the `cdap_set_java` function; 
- different CDAP UI default port settings; 
- different CDAP start scripts (`cdap.sh` versus `cdap`); and 
- text differences in the documentation RST files.

**Comment by sreevatsanraman** [comment]
Merging this. Will fix the javadocs build on develop and backport.

**Pull request merged**
