### PR TITLE
[CDAP-16118] Set default properties when adding nodes to the canvas

### PR DESCRIPTION
**Pull request by njbriggs**
Jira: https://cdap.atlassian.net/browse/CDAP-16118

This adds default properties to nodes when adding them to the canvas. This saves the user from having to open the Properties screen if they want to keep the defaults.

### CODE REVIEW

**Comment by njbriggs** [comment]
E2E tests: https://builds.cask.co/browse/IT-UPD2211

**Review by ajainarayanan — APPROVED** [review]
👍 LGTM

**Comment by njbriggs** [comment]
Squashed to 1 commit

**Pull request merged**
