### PR TITLE
CDAP-6615 Add UsageDataset to registry using simple name.

### PR DESCRIPTION
**Pull request by sagarkapare**
Using `UsageDataset` simple name while adding it to the registry and during upgrade process as well. This is different from other datasets where we use name while adding to the registry.

### CODE REVIEW

**Comment by sagarkapare** [comment]
@poornachandra please take a look. Thanks!

**Comment by poornachandra** [comment]
LGTM

**Comment by sagarkapare** [comment]
Build is running here - http://builds.cask.co/browse/CDAP-DUT4482-2/

**Comment by sagarkapare** [comment]
Build is green. Merging.

**Comment by anwar6953** [comment]
@poornachandra @sagarkapare 
Should we instead have registered UsageDataset with the full name as well as the short name?

We often register other datasets by both short and full names:
https://github.com/caskdata/cdap/blob/develop/cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetModule.java#L40-L41

**Pull request merged**
