### PR TITLE
Cherry-pick changes from develop to 4.1

### PR DESCRIPTION
**Pull request by ajainarayanan**
https://github.com/caskdata/cdap/pull/8242 - **[CDAP-8396][CDAP-8554] Call to action for namespace creation**
https://github.com/caskdata/cdap/pull/8243 - **[CDAP-8828] Remove dialog to select pipeline type upon pipeline creation**
https://github.com/caskdata/cdap/pull/8245 - **[CDAP-8834] prevent dropdown from closing when clicking on entity filter**
https://github.com/caskdata/cdap/pull/8261 - **[CDAP-8430] New "No Entities Found" message**
https://github.com/caskdata/cdap/pull/8267 - **[HYDRATOR-1364] Fixes pipeline studio to remove __ui__ property while exporting pipeline**
https://github.com/caskdata/cdap/pull/8273 - **[CDAP-8494] Fix back button while navigating from old to new UI**
https://github.com/caskdata/cdap/pull/8275 - **[HYDRATOR-1187] - Fix Hydrator widget json number field should allow null values**
https://github.com/caskdata/cdap/pull/8282 - **[CDAP-8638] Fixes log fast action to open each log in a separate tab**
https://github.com/caskdata/cdap/pull/8283 - **[CDAP-8501] Fixes Preview button to be disabled in distributed environment**
https://github.com/caskdata/cdap/pull/8303 - **[CDAP-8433][CDAP-8861] Show units for YARN, and remove CDAP Version Range**

Bamboo build: http://builds.cask.co/browse/CDAP-DRC6045-1

### CODE REVIEW

**Comment by bdmogal** [comment]
Please fix these issues before merging:
1. https://issues.cask.co/browse/CDAP-8933
2. See comment on https://issues.cask.co/browse/CDAP-8430?focusedCommentId=28609&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-28609
3. Going from stream card -> stream overview -> stream details is broken
4. In distributed mode, the preview button's tooltip should be - "Pipeline preview is not available in distributed mode."


Yet to verify the two hydrator issues.

**Comment by ajainarayanan** [comment]
Talked to @bdmogal . The issues mentioned above can be added as separate PRs. Have added the tooltip change alone as its minor and is a missing functionality spec'd out in the JIRA. Issue.3 mentioned above seems to be a regression. Will come in as a separate PR.

**Comment by bdmogal** [comment]
@ajainarayanan @elfenheart @tonybach I've reported https://issues.cask.co/browse/CDAP-8950 for 3. since you're saying its not caused by this PR. 

Can we merge this, since for all other issues I reported, there are jiras?

**Comment by elfenheart** [comment]
@bdmogal Yes we can merge this

**Comment by elfenheart** [comment]
👍  LGTM

**Pull request merged**
