### PR TITLE
(CDAP-6168) Small improvement the efficiency of Auth cache lookup

### PR DESCRIPTION
**Pull request by chtyim**
- Use a better cache structure for faster lookup
- Avoid creating new object for lookup
- Cache the hashCode of all EntityId classes
  - Avoid creating intermediate Object[]

### CODE REVIEW

**Comment by chtyim** [comment]
From local micro-benchmarking, the time is about half (400ms vs 200ms to perform 1M lookup).

**Comment by chtyim** [comment]
Crap. Gson doesn't like the `hashCode` field. Need to make some adjustment.

**Comment by bdmogal** [comment]
LGTM

**Comment by bdmogal** [comment]
Ok, just saw your comment. Will review again.

**Comment by bdmogal** [comment]
nice! LGTM

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT4439-3

**Comment by chtyim** [comment]
sqaushed and merging.

**Pull request merged**
