### PR TITLE
[CDAP-13020] Remove parents from jdbc driver upload

### PR DESCRIPTION
**Pull request by elfenheart**
JIRA: https://issues.cask.co/browse/CDAP-13020
Build: https://builds.cask.co/browse/CDAP-URUT24

### CODE REVIEW

**Comment by tonybach** [comment]
Just to make sure, does the `ArtifactUploadActionCreator.uploadArtifact()` call in `LibraryUpload` need to pass the `false` param as well?

**Comment by ajainarayanan** [comment]
Code 👍 LGTM. @tonybach If its not passed it will have undefined which is falsy value right? Should be ok? But @elfenheart would be good if we have a `defaultProps` set to false.

**Comment by elfenheart** [comment]
@ajainarayanan I set the defaultProps to true actually. Can set it to false, but the original intend was to not disturb code that didn't need to be.

@tonybach the LibraryUpload still needs the parent artifact, and since it's not specified in the argument, the ActionCreator will set it to true. Maybe that's quite confusing...

**Comment by ajainarayanan** [comment]
Code 👍 LGTM

**Review by bdmogal — APPROVED** [review]

**Pull request merged**
