### PR TITLE
[CDAP-8021] Preferences for applications and programs (modifications)

### PR DESCRIPTION
**Pull request by tonybach**
JIRA: https://issues.cask.co/browse/CDAP-8021 (Comments section)

### CODE REVIEW

**Comment by tonybach** [comment]
Not sure why I couldn't find the builds for this branch: http://builds.cask.co/browse/CDAP-DRC/branches

**Comment by ajainarayanan** [comment]
Bamboo build: http://builds.cask.co/browse/CDAP-DRC5365-1

For some reason the plan for the branch was not created. Manually created one.

**Comment by elfenheart** [comment]
check eslint, it's failing some test

**Comment by elfenheart** [comment]
👍  LGTM

**Pull request merged**
