### PR TITLE
[CDAP-9390] add system artifacts reload button

### PR DESCRIPTION
**Pull request by elfenheart**
JIRA: https://issues.cask.co/browse/CDAP-9390

### CODE REVIEW

**Comment by elfenheart** [comment]
demoed to @bdmogal

**Comment by tonybach** [comment]
Code LGTM 👍

**Comment by tonybach** [comment]
Actually can you update the license years in the older files that you changed

**Review by tonybach — APPROVED** [review]
LGTM 👍

**Pull request merged**
