### PR TITLE
added abstract and remote clients to retrieve information using service discovery

### PR DESCRIPTION
**Pull request by miguelvelezmj25**

### CODE REVIEW

**Comment by miguelvelezmj25** [comment]
I am not able to see my branch in the build https://builds.cask.co/browse/CDAP-DUT/branches

**Comment by chtyim** [comment]
You have to name your branch in the pattern `feature/CDAP-[xxxx]-[description]` in order to trigger the branch build

**Comment by miguelvelezmj25** [comment]
I am guessing that the `-[xxxx]-` is a bug report number. Do I create a new one?

**Comment by anwar6953** [comment]
Yea, go ahead and create a Jira for this.

**Pull request closed without merging**
