### PR TITLE
[CDAP-7551] Upgrade to Bootstrap 4 & Migrate to SASS

### PR DESCRIPTION
**Pull request by elfenheart**
JIRA: https://issues.cask.co/browse/CDAP-7551

- Upgrading to Bootstrap 4 for React Components
- Migrating to SASS for CSS Preprocessor

- Added couple of missing CSS styles to our Angular Components CSS so that the shared components will still work.
- We still have to go through everything to make sure the styling is OK

## How to migrate?

1. Install less2sass `npm install -g less2sass`
2. To convert file, simply run `less2sass <filename>`
3. Make sure in the newly created scss file, the `calc()` has no quote
4. Go to the index.js file, change the `require(component.less);` to `require(component.scss);`
5. Search through the index.js and convert class names listed at the bottom.

### To find all files recursively under a directory with `.less` extension 
```
find . -type f -name \*.less
```

### To remove all files recursively under a directory with `.less` extension
```
rm `find . -type f -name \*.less`
```

## Classes to convert
1. btn-default -> btn-secondary
2. pull-right -> float-xs-right
3. pull-left -> float-xs-left
4. text-right -> text-xs-right
5. text-center -> text-xs-center
6. text-left -> text-xs-left
7. checkboxes:
```
<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="checkbox" value="">
    label for the checkbox
  </label>
</div>
```

### CODE REVIEW

**Comment by ajainarayanan** [comment]
Looks awesome! Noticed few things,

- Dropdown in wheel icon 
screen shot 2017-01-09 at 12 20 33 pm

- Font and font-spacing seems to be different. Is it possible to confirm with Lea and @nitinmotgi 

- Program card in app overview
 screen shot 2017-01-09 at 1 30 57 pm

- Management system services, instances set button text color
screen shot 2017-01-09 at 1 32 31 pm

- Explore modal in cdap home page
screen shot 2017-01-09 at 1 35 10 pm

**Comment by ajainarayanan** [comment]
@elfenheart 🎆 🍾 🎉 It looks awesome! Overall it was smooth!

Noticed a few things when observing in detail,

**- The fonts (both weight and size & bold) seem to have varied in places**
screen shot 2017-01-12 at 10 07 25 pm

**- Running common build doesn't seem to update the top navbar being shared across all the webapps. Not sure what I am missing**
I ran the following commands,
```
$ rm -rf node_modules
$ npm i
$ npm run cdap-prod-build
$ gulp build
```
**- There are many subtle styling changes in places. We should probably need more eyes to see what has changed. If the change is good ok but if not we should make sure it resembles the existing UI.**

For instance,

screen shot 2017-01-12 at 10 12 43 pm
screen shot 2017-01-12 at 10 16 31 pm
screen shot 2017-01-12 at 10 17 43 pm


It would be nice if we pushed the changes to a cluster and get more eyes before we merge this PR. We could reduce the amount of surprises at the end of the release.

**Comment by tonybach** [comment]
I noticed two minor changes, compared with http://latestui17400-1000.dev.continuuity.net:11011. Not sure if the first one was deliberate:

- Before: 
screen shot 2017-01-18 at 12 28 17 pm
After: 
screen shot 2017-01-18 at 12 28 30 pm

- Space between columns?
screen shot 2017-01-18 at 12 38 53 pm

**Comment by tonybach** [comment]
👍  LGTM!

**Comment by elfenheart** [comment]
Build: http://builds.cask.co/browse/CDAP-DRC5263-10

**Comment by elfenheart** [comment]
Green build - merging

**Pull request merged**
