### PR TITLE
[CDAP-8951] - Fix Metadata entity detail page has wrong font color for Business Tags

### PR DESCRIPTION
**Pull request by ajainarayanan**
Exact [PR#8344](https://github.com/caskdata/cdap/pull/8344) against release/4.1 branch

### CODE REVIEW

**Comment by tonybach** [comment]
I think Sushil made a valid point in his PR about the preferred tags. Here's what it looks like right now:

screen shot 2017-03-27 at 1 30 03 pm

If we make the font color of the preferred tags to be the same as others, it would make those tags look less out of place, while still being readable.

**Comment by leacd** [comment]
Hi there, Ajai asked me to take a look at this pr and weigh in. 
I am pasting below a visual treatment for the Preferred Business tags. 
image

**Comment by tonybach** [comment]
@ajainarayanan We can remove the now-unused LESS variable `@preferred-tag-bg`. Other than that, code LGTM 👍

**Comment by elfenheart** [comment]
👍  LGTM

**Comment by leacd** [comment]
Two feedback
1) The preferred treatment is not displayed when the tag is in the details overview or details view.  
2) When I create a new preferred tag the confirmation message displays the tag with white text on white background. (see image.) 
screen shot 2017-03-28 at 12 41 12 pm

**Comment by leacd** [comment]
LGTM

**Pull request merged**
