### PR TITLE
[CDAP-15478] adds support for configuration-filter plugin ui widget

### PR DESCRIPTION
**Pull request by neelesh-nirmal**
#### Jira
https://issues.cask.co/browse/CDAP-15478

## Configuration Filter Widget

configuration-filter

#### Widget Type
_configuration-filter_

#### Widget Attributes

- _options_ : Array of String as dropdown values
- _default_: Default value of the dropdown.

#### Output Data type
_String_
#### Description
Show/Hide other input configuration widgets based on selected drop down value.

#### How to use
 
_Refer to demo gif on the top_

- Using the configuration-filter widget example

``` javascript
{
          "widget-type": "configuration-filter",
          "name": "numberOfJiraTicketsGenerated",
          "label": "Number of Tickets to be generated",
          "widget-attributes": {
                "options": ["Single", "Multiple"]
          }
}
```

- Below example shows how to use configuration-filter's value in other input widget to show/hide them based on the selected values.

```javascript
{
  "name": "numberOfTickets",
  "label": "Ticket Count",
  "widget-type": "number",
  "widget-attributes": {
    "default": "2",
    "min": "2",
    "max": "30",
    "filters": [
      {
        "widget-name": "numberOfJiraTicketsGenerated",
        "filter-values": ["Multiple"]
      }
    ]
  }
},
{
  "name": "uniqueIdentifierForEachTicket",
  "label": "Unique Identifier For Each Ticket",
  "widget-type": "input-field-selector",
  "widget-attributes": {
    "filters": [
      {
        "widget-name": "numberOfJiraTicketsGenerated",
        "filter-values": ["Multiple"]
      }
    ]
  }
},
{
  "name": "suggestedQueryHelp",
  "label": "Suggested Query Help",
  "widget-type": "textBox",
  "widget-attributes": {
    "filters": [
      {
        "widget-name": "numberOfJiraTicketsGenerated",
        "filter-values": ["Single"]
      }
    ]
  }
}```

### CODE REVIEW

**Comment by neelesh-nirmal** [comment]
I signed it !

**Comment by ajainarayanan** [comment]
Hi @neelesh-nirmal Thank you so much for contributing back to CDAP! Appreciate it.

Since we have been thinking about this problem for sometime, after reviewing the pull request we have decided to take this one step up. We currently are not in sync on the design for this feature and I have created a proposal and sent to the cdap-user group for review. 

Would you mind checking [it here](https://groups.google.com/forum/#!topic/cdap-user/R7X36hyxb_g) and collaborate more on what we decide on the design based on review?

**Comment by neelesh-nirmal** [comment]
Thanks @ajainarayanan .
Will checkout the praposed approaches and collaborate.

**Comment by ajainarayanan** [comment]
Currently on-hold. The proposal for implementing this in widget spec is being discussed and [reviewed here](https://groups.google.com/forum/#!topic/cdap-user/R7X36hyxb_g)

**Comment by ajainarayanan** [comment]
After extensively iterating over the design for dynamic plugin filters have opened a pull [request here](https://github.com/cdapio/cdap/pull/11602). Please follow [PR#11602 ](https://github.com/cdapio/cdap/pull/11602) for further updates. 

Closing this for now. Thank you so much for the contribution @neelesh-nirmal Appreciate all the contributions you do!

**Pull request closed without merging**
