### PR TITLE
Feature/9077 cdap bat update

### PR DESCRIPTION
**Pull request by dereklwood**
windows side of CDAP-9077

updates to linux scripts to upgrade ui-pack via cdap apply-pack [zip].

```
C:\Users\vagrant\Desktop\new\cdap-sdk-4.1.1-SNAPSHOT\cdap-sdk-4.1.1-SNAPSHOT\bin>cdap apply-pack C:\Users\vagrant\Desktop\new\cdap-sdk-4.1.1-SNAPSHOT\
cdap-sdk-4.1.1-SNAPSHOT\cdap-ui-pack-4.1.1-SNAPSHOT_p1.zip

> cdap-ui-upgrade@1.0.0 upgrade C:\Users\vagrant\Desktop\new\cdap-sdk-4.1.1-SNAPSHOT\cdap-sdk-4.1.1-SNAPSHOT\ui\cdap-ui-upgrade
> node index.js "--new-ui-zip-path=C:\Users\vagrant\Desktop\new\cdap-sdk-4.1.1-SNAPSHOT\cdap-sdk-4.1.1-SNAPSHOT\cdap-ui-pack-4.1.1-SNAPSHOT_p1.zip"

 v Verifying environment before upgrading UI Pack
 v Backing existing UI : <C:\Users\vagrant\Desktop\new\cdap-sdk-4.1.1-SNAPSHOT\cdap-sdk-4.1.1-SNAPSHOT>
 v Updating with new UI Pack
```

### CODE REVIEW

**Review by wolf31o2 — APPROVED** [review]
This 👍 LGTM, assuming you've tested on different versions of Windows.

**Comment by awholegunch** [comment]
Testing revisions under Windows 8 and a non-admin account.

**Comment by dereklwood** [comment]
Tested on windows 8 laptop, 2012 server (output above), and 2008 server (see https://issues.cask.co/browse/CDAP-9345).  @awholegunch can we do line-endings in another PR?  i'd like to merge this....

**Comment by poornachandra** [comment]
@dereklwood There is a typo in line 394 of the script - `Standalone CDAP started succesfully`. It would be good if you can fix that in this PR. JIRA - https://issues.cask.co/browse/CDAP-9206

**Comment by dereklwood** [comment]
@poornachandra fixed

**Pull request merged**
