### PR TITLE
[CDAP-11827] Fixes alignment for ScalaSparkProgram

### PR DESCRIPTION
**Pull request by tonybach**
JIRA: https://issues.cask.co/browse/CDAP-11827

Before:
screen shot 2017-06-07 at 3 58 55 pm

After:
screen shot 2017-06-07 at 3 59 00 pm

### CODE REVIEW

**Review by ajainarayanan — APPROVED** [review]
Code 👍 LGTM

**Review by bdmogal — COMMENTED** [review]
@tonybach this doesn't change the logic for Python and Javascript plugins right? Shouldn't change the left margin for them, since transforms have input schema as well.

**Comment by tonybach** [comment]
@bdmogal Nope, since the left padding change only affects Action plugins that have a code editor in their config.

**Comment by tonybach** [comment]
Demoed to @bdmogal, squashing and merging.

**Pull request merged**
