### PR TITLE
[CDAP-15190] Fix database table count when filtered

### PR DESCRIPTION
**Pull request by njbriggs**
Jira: https://issues.cask.co/browse/CDAP-15190

Show the current table count when filtering the table list when adding a connection.

### CODE REVIEW

**Comment by njbriggs** [comment]
E2E tests: https://builds.cask.co/browse/IT-UPD2199

**Comment by njbriggs** [comment]
Tests: https://builds.cask.co/browse/CDAP-UDUT877

**Review by ajainarayanan — APPROVED** [review]

**Pull request merged**
