### PR TITLE
HYDRATOR-213 Fix Default to highest version when creating a plugin template

### PR DESCRIPTION
**Pull request by sushil-car**
https://issues.cask.co/browse/HYDRATOR-213

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@sushiladokar the dropdown right now defaults to the default selected version and not to the latest version. Can you check if @elfenheart 's changes in [this PR](https://github.com/caskdata/cdap/pull/7607) could be used to interpret the latest version?

**Comment by ajainarayanan** [comment]
latestversion

**Comment by sushil-car** [comment]
@ajainarayanan I am trying to use Version class to compare the versions, need to debug how to implement this, is this correct ?

**Comment by ajainarayanan** [comment]
@sushiladokar By version class you mean Edwin's Version class changes? You can export it as part of the common/cask-header.js file. You need to use `VersionRange` service inside angular to find out the latest version. We already export `VersionStore & VersionActions`

**Comment by elfenheart** [comment]
@sushiladokar you can export the Version class, and once you construct the Version object, there is a method `compareTo()` that will let you know whether the current version is smaller, equal, or greater

**Comment by ajainarayanan** [comment]
@sushiladokar I am still noticing incorrect default versions for plugins in the left panel. This is what I did,

- Uploading Cassandra plugin version 1.5.1
- SDK already had 1.6.0-SNAPSHOT
- On reloading the UI Cassandra was showing 1.5.1 in the tooltip instead of 1.6.0-SNAPSHOT
- On clicking the Cassandra plugin in the left panel it 

I have attached a gif of what I am seeing. Let me know if I am missing something.

latestversion

**Comment by sushil-car** [comment]
@ajainarayanan We are showing the latest version on click of the template in dropdown list.
Tooltip on plugin shows the last changed version and same version (last changed) will be shown when we drag that plugin on canvas and click on node to open it.

In GIF, I see 1.5.1 is selected on plugin hover, so it will show 1.5.1 when click on node from canvas.

Is this correct ?

**Review by ajainarayanan — APPROVED** [review]
👍 LGTM

**Pull request merged**
