### PR TITLE
Revert "Make ClientConfig class ThreadSafe, by making it immutable."

### PR DESCRIPTION
**Pull request by Nishith**
This reverts commit 687dcaf577bdf10fcf96ea3f8ad6f4154cba327e.

Cause: https://issues.cask.co/browse/CDAP-7355

### CODE REVIEW

**Comment by bdmogal** [comment]
LGTM, so long as its been tested in the IDE. Please confirm with @anwar6953 too though.

**Comment by poornachandra** [comment]
Instead of reverting this change, can we fix the issue?

**Comment by Nishith** [comment]
It is blocking Edwin and I don’t know what the fix is right now.

**Comment by bdmogal** [comment]
Going to merge this to unblock testing.

**Pull request merged**
