### PR TITLE
[CDAP-7205] Remove deprecated useDatasets() from API and documentation

### PR DESCRIPTION
**Pull request by anew**
title says it all. 

This does not break hydrator build.

### CODE REVIEW

**Comment by anew** [comment]
Build running here: http://builds.cask.co/browse/CDAP-DUT5029

**Comment by anew** [comment]
Docs build passed, too: http://builds.cask.co/browse/CDAP-DQB168-1

**Comment by anwar6953** [comment]
LGTM. I think all the cdap-apps, cdap-guides, etc should be made sure that they're not using these deprecated APIs first, before merging this.

**Comment by anew** [comment]
To be honest, I think that everybody who deprecated a method should remove that from all apps, guides, and plugins. We have to make sure that these don't break, but that will be in a separate PR anyway (if it requires a fix).

I have validated using local mvn install that this does not break any of the hydrator-plugins, cdap-apps, or cdap-guides. Merging now.

**Pull request merged**
