### PR TITLE
Merge release 401 to develop

### PR DESCRIPTION
**Pull request by Nishith**
Conflicts in all the pom files as release version was bumped to 4.0.1. Resolved manually.
Conflicts in UI and packaging files. Merged them manually too. 

Merged develop back into merge_release_401_to_develop on 19/1

### CODE REVIEW

**Comment by Nishith** [comment]
Green build: http://builds.cask.co/browse/CDAP-DUT5291-1

**Comment by gokulavasan** [comment]
@Nishith Can you fix the conflicts? I will review it right after that.

**Comment by gokulavasan** [comment]
LGTM 👍

**Comment by Nishith** [comment]
Thanks for the review. 
Green build at http://builds.cask.co/browse/CDAP-DRC5334-4
Merging.

**Pull request merged**
