### PR TITLE
Return right promise on update state reload in published pipeline view

### PR DESCRIPTION
**Pull request by ajainarayanan**

### CODE REVIEW

**Review by elfenheart — APPROVED** [review]
👍  LGTM

**Comment by tonybach** [comment]
New commit LGTM 👍

**Comment by ajainarayanan** [comment]
Will check to see if the promise returned from the state reload was causing the issue. The correct fix then would be to fix the return of `$state.reload()` function call.

**Review by elfenheart — APPROVED** [review]
👍  LGTM

**Review by bdmogal — APPROVED** [review]

**Pull request merged**
