### PR TITLE
Bumping up develop version from 4.1.0-SNAPSHOT to 4.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by Nishith**

### CODE REVIEW

**Comment by rohitsinha54** [comment]
Have you run a find in cdap repo for 4.1.0-SNAPSHOT
I see a lot of occurrence for it. The hydrator json and scripts needs to change too. Refer to older version bump PR https://github.com/caskdata/cdap/pull/7261 
Also the hydrator, tracker versions needs to be updated right ?

**Comment by Nishith** [comment]
Added missing files. Please take a look.

**Comment by awholegunch** [comment]
LGTM

**Comment by Nishith** [comment]
Running a build @ http://builds.cask.co/browse/CDAP-DUT5418-1

**Comment by Nishith** [comment]
Build is green. Merging.

**Comment by Nishith** [comment]
Thanks @wolf31o2. Changed rx version back to 4.1. Please take a look

**Comment by elfenheart** [comment]
👍  LGTM. nice catch @wolf31o2

**Comment by Nishith** [comment]
Got a go-ahead from @elfenheart, merging.

**Pull request merged**
