### PR TITLE
Do not trace input record for source and output record for sink

### PR DESCRIPTION
**Pull request by yaojiefeng**
JIRA: https://issues.cask.co/browse/HYDRATOR-1123
Build: http://builds.cask.co/browse/CDAP-DUT5116-2
Since we are not sure about the data type of source and sink, we will not trace them using PreviewStore

### CODE REVIEW

**Comment by gsps1** [comment]
@sagarkapare @chtyim 
would it make sense to get a data tracer for a stage with list of properties that it can trace ( call info method on that property)

something like `DataTracer getDataTracer(String dataTracerName, Set<String> allowedProperties);`

so pipeline source can just call `getDataTracer(source, ImmutableSet.of("records.out"));` while getting the data tracer ? and the DataTracer implementation will skip info on other properties eg : `records.in`.

or is that api not ideal ? what do you think?

**Comment by chtyim** [comment]
I don't quite understand the issue. Do you mean the source/sink is emitting something that Gson cannot serialize??

**Comment by chtyim** [comment]
@gsps1 I am not quite sure why we need to skip some properties. However, what you've proposed is not a very good API, as it promotes code that will get ignore without notice, making it very difficult to debug (e.g a plugin keeps emitting `record.in`, but nothing get logged. It is not obvious that the one who created the tracer, which maybe outside of the plugin, is actually filtering the property out).

**Comment by albertshau** [comment]
The issue is that a source gets whatever an inputformat produces, and a sink writes out whatever an outputformat expects? How come this causes issues with DataTracer? Doesn't that mean anybody using the DataTracer with those objects in their own programs will have the same issue?

**Comment by yaojiefeng** [comment]
@chtyim @albertshau Some of the input record for source and output record for sink cannot be serialized by GSON. Tested with DBSource, the input has type DBRecord, and GSON cannot serialize it. So we will not put input record from source and output record to sink for preview.

**Comment by albertshau** [comment]
I understand that we might not want to store it for Hydrator, but what do you mean when you say it cannot be serialized? Do you mean there is some sort of error? Or just that the gson serialized string cannot correctly be deserialized by gson?

**Comment by chtyim** [comment]
DBSource is a plugin, not a data type. Who is trying to emit it to the data tracer??

**Comment by yaojiefeng** [comment]
@albertshau In `PreviewStore`, we use `Gson.toJson()` to serialize the input. But there is error when Gson tried to serialize DBRecord

**Comment by yaojiefeng** [comment]
@chtyim That was a typo.. Should be DBRecord, fixed the comment

**Comment by chtyim** [comment]
Why? Because `StructuredRecord` or `Configuration` (the only two fields it has)? Shouldn't we fix that? Also, what happen if some plugin other than source/sink emits data object that can't be serialized with Gson? We shouldn't workaround like this.

**Comment by yaojiefeng** [comment]
@chtyim @albertshau tested the DBSource, and here is the findings: The input type for the DBSource is a KeyValue object with key as the stage name and the value as a DBRecord. DBRecord contains two fields: `StructuredRecord` and `Configuration`. Gson fails to serialize Configuration object and throws StackOverflow error. Have also tried `new Gson.new Gson().toJson(new Configuration());`, got the same error. Also, does it make sense to let `DBRecord` has field `Configuration`? Even if it is serializable, I feel we should not trace the `Configuration` and show that to the user. Any thoughts on this?

**Comment by yaojiefeng** [comment]
```Could not find the clause substitution token $CONDITIONS in the query: [select * from preview]. Parallel splits may not work correctly.
java.lang.StackOverflowError
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
….// a lot of repeated 
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
	at com.google.gson.Gson.getAdapter(Gson.java:356)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
	at com.google.gson.Gson.getAdapter(Gson.java:356)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
	at com.google.gson.Gson.getAdapter(Gson.java:356)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
	at com.google.gson.Gson.getAdapter(Gson.java:356)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
	at com.google.gson.Gson.getAdapter(Gson.java:356)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
	at com.google.gson.Gson.getAdapter(Gson.java:356)
…// a lot repeated

```

**Comment by chtyim** [comment]
One interesting thing about the `DBRecord` is that, it actually implements `Writable`, meaning it is serializable (can write to some external storage). Maybe we should support `Writable` objects as well. Using Gson blindly can lead to the problem you described.

**Comment by albertshau** [comment]
Ideally, if it is Writable, or if it is Serializable (similar issue for Spark), we serialize according to those contracts. In the short term however, we can make the configuration field transient, since we don't want it stored for preview.

In any case, at the very least, the DataTracer API should document what can and can't be used. Also, shouldn't DataTracer be annotated as Beta?

**Comment by yaojiefeng** [comment]
Closing this PR, will add documentation to the DataTracer about the usage of the input record and mark it as Beta. Will figure out a better way to deal with source/sink in the future.

**Pull request closed without merging**
