### PR TITLE
CDAP-9321 Avoid spark console progress

### PR DESCRIPTION
**Pull request by deepakwadhwani**
Avoid progress messages like for Spark programs: 

2017-05-15 16:31:02,985 - WARN  [refresh progress:o.a.s.d.y.ApplicationMaster@91] - 
[Stage 0:>                                                          (0 + 2) / 2]
2017-05-15 16:31:05,186 - WARN  [refresh progress:o.a.s.d.y.ApplicationMaster@91] - 
[Stage 0:=============================>                             (1 + 1) / 2]
2017-05-15 16:31:07,387 - WARN  [refresh progress:o.a.s.d.y.ApplicationMaster@91] - 
[Stage 6:>                                                          (0 + 0) / 2]
2017-05-15 16:31:08,788 - WARN  [refresh progress:o.a.s.d.y.ApplicationMaster@91] - 
[Stage 12:>                                                         (0 + 2) / 2]

### CODE REVIEW

**Comment by chtyim** [comment]
I am not sure if we want to suppress it by default. Spark users are so used to it.

**Comment by deepakwadhwani** [comment]
@chtyim Since Spark writes these to stderr program logs show them as WARN messages. https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/ui/ConsoleProgressBar.scala#L101
Ideally they should be shown at level INFO, but there isn't a clean way to change the level. [until we can stop redirecting logs from stderr altogether]  
If we believe User would want to see these logs, we could leave this on by default and the User can turn off if required using spark config. Please suggest.

**Comment by chtyim** [comment]
Seems like this PR has the same changes as the transaction failure exception one??

**Comment by chtyim** [comment]
The disabling of it is already controllable by the user. Why we need to turn it off by default? Also, it's the Spark framework that output it to stderr (which is for "error" purpose), why we have to bother?

**Comment by deepakwadhwani** [comment]
@chtyim 
1. I fixed the branch to remove the exception related changes from this branch. 
2. Based on our discussion, I will close this PR and attach to Jira for future reference.

**Comment by chtyim** [comment]
If we want to disable it for the pipeline, we should do it from the hydrator app by setting that config

**Pull request closed without merging**
