### PR TITLE
Update of documentation design for 4.2.

### PR DESCRIPTION
**Pull request by awholegunch**
The long-awaited update to the design of CDAP docs for release 4.2.

Running as a Quick Build: https://builds.cask.co/browse/CDAP-DQB349-1 (passes)

Page of interest: https://builds.cask.co/artifact/CDAP-DQB349/shared/build-1/Docs-HTML/4.2.0-SNAPSHOT/en/index.html

Running as a Docs Build and Test (to check Javadocs and links): https://builds.cask.co/browse/CDAP-DBT23-2 (passes)

Page of interest: https://builds.cask.co/artifact/CDAP-DBT23/shared/build-2/Current-Docs-HTML/4.2.0-SNAPSHOT/en/index.html
Javadocs: https://builds.cask.co/artifact/CDAP-DBT23/shared/build-2/Current-Docs-HTML/4.2.0-SNAPSHOT/en/reference-manual/javadocs/index.html

### CODE REVIEW

**Comment by wolf31o2** [comment]
The `Guides` link at the top leads back to the index.

**Comment by awholegunch** [comment]
Currently, that's by design, as we have not created a separate "Guides" section. In lieu of that, I just pointed the link back to the index page. The next big PR will reorganize things and create that section.

**Comment by awholegunch** [comment]
"On-hold", as these changes have been requested by @bdmogal:
- [x] Larger CDAP logo, small v and smaller version number
- [x] Add colored underlines indicating the current manual under the links in the navbar; these can match the right sidebar)
- [x] Increase space between left-sidebar and main body to accommodate the perma-links (shown on hover)
- [x] Adjust title at top of left sidebar menu correctly
- [x] Add a landing page that replaces the current one
- [x] Disable any links that return to the current page
- [ ] Replace the left sidebar menu with a collapsible menu with disclosure triangles (to be completed)
- [ ] Mouse-wheel scrolling has been disabled in the scrolling areas; check if it is preventing trackpad scrolling of those areas. (looks like it does; to be replaced with lightbox)

**Comment by awholegunch** [comment]
New Build: https://builds.cask.co/browse/CDAP-DQB349-4

Page of interest: https://builds.cask.co/artifact/CDAP-DQB349/shared/build-4/Docs-HTML/4.2.0-SNAPSHOT/en/index.html

**Comment by awholegunch** [comment]
BTW: In the latest build, _everything_ should work. If not, let me know. All links should be fixed, and point to appropriate locations. (As Javadocs haven't been built in the Quick Build, any links to them will not work.)

**Comment by bdmogal** [comment]
@awholegunch this is not on hold anymore right? The only concern I have is that the CDAP logo looks too large perhaps. Can you reduce it to ~80%?

**Comment by bdmogal** [comment]
Other than the above concern, let's merge this. There's plenty of follow up, but let's get the big PR in first.

**Review by bdmogal — APPROVED** [review]

**Comment by awholegunch** [comment]
Reduced image and adjusted text baseline to match.

**Comment by awholegunch** [comment]
Running as a Quick Build: https://builds.cask.co/browse/CDAP-DQB349-5 (passed)

**Pull request merged**
