### PR TITLE
(CDAP-6956) Setting the context classloader.

### PR DESCRIPTION
**Pull request by Nishith**

### CODE REVIEW

**Comment by Nishith** [comment]
Build: http://builds.cask.co/browse/CDAP-RUT98-1

**Comment by chtyim** [comment]
LGTM

**Comment by anwar6953** [comment]
This seems like a fairly impactful change.
I suggest running integration tests against a cluster from this branch before merging.

Edit: kicked off a build: http://builds.cask.co/browse/CDAP-ITM0-18

**Comment by Nishith** [comment]
Integration tests passed: http://builds.cask.co/browse/CDAP-ITM0-18

**Comment by Nishith** [comment]
Green build: http://builds.cask.co/browse/CDAP-RUT98-1

**Pull request merged**
