### PR TITLE
[cherry-pick 15020] Added support for Java 11 in program runtime (not for CDAP system its…

### PR DESCRIPTION
**Pull request by iam-divya**
…elf)

  - Added support for configuration activation based on JVM version
  - Make class loading compatible with Java 11
    - Remove the usage of `sun.boot.class.path`
    - Replace getURLs call on the system class loader with java.class.path
  - Make it compatible with Spark3 in GCP Dataproc environment out of the box - Added dependency log4j-to-slf4j for log4j2 with version compatible with Spark 3
  - Fix HBase coprocessor jar building to include all classes and resources correctly (for unit-test)

### CODE REVIEW

**Comment by chtyim** [comment]
Can you add the commit from https://github.com/cdapio/cdap/pull/15063 too? This is to fix the HBase failure in the integration test environment.

**Review by chtyim — APPROVED** [review]
Please also add https://github.com/cdapio/cdap/pull/15063 to this cherry pick

**Comment by iam-divya** [comment]
> Please also add #15063 to this cherry pick

This is already added in 6.9 branch in your last cherry-pick,
 https://github.com/cdapio/cdap/commits/release/6.9?author=chtyim

**Comment by chtyim** [comment]
Now I get confused by this cherry-pick. It seems like the commit 28872edf41427ae65cf19136fd49cf40a3424ce1 , which is the Java11 changes, is already in release/6.9 branch?

**Comment by iam-divya** [comment]
Right. That is the reason, this cherry-pick did not pick all the changes. But I dont understand why some of the changes in this diff was not part of the previous cherry-pick.

**Comment by iam-divya** [comment]
That was a wrong url, Here is the list of commits in release branch,
https://github.com/cdapio/cdap/commits/release/6.9

2 of your commits are already cherry picked and rest of the changes are in this PR. 

[Merge pull request](https://github.com/cdapio/cdap/commit/df85848fee82b1cf838418556c24a5775a3d98d7) https://github.com/cdapio/cdap/pull/15081 [from cdapio/fix-hbase-tmp-path-6.9](https://github.com/cdapio/cdap/commit/df85848fee82b1cf838418556c24a5775a3d98d7) 
@chtyim
chtyim committed 3 days ago
  
Get the absolute file path for the temp directory for creating coproc… 
@[chtyim](https://github.com/cdapio/cdap/commits?author=chtyim)
chtyim committed 3 days ago

**Comment by iam-divya** [comment]
After the discussion, we found out that some changes in the commit(#15020) are not pulled into release branch because of conflict. Hence second cherrypick was needed for the same commit.

**Review by chtyim — APPROVED** [review]

**Pull request merged**
