### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by anwar6953**
Remove deprecated methods from PartitionedFileSetArguments and WorkflowContext.
Replace usages of AbstractWorkflowAction with AbstractCustomAction.
Make CustomActionContext also implement ServiceDiscoverer.

http://builds.cask.co/browse/CDAP-DUT5144-8

### CODE REVIEW

**Comment by sagarkapare** [comment]
LGTM 👍

**Comment by sagarkapare** [comment]
LGTM 👍

**Comment by anwar6953** [comment]
Removing commit https://github.com/caskdata/cdap/commit/0f80fbde0f05f4be4c66c170acf83980adc00083 from this PR, since its not proper removal of the deprecated methods in FlowletDefinition.

**Comment by anwar6953** [comment]
Build is green.
Rebased from develop, squashed commits and merging.

**Comment by anwar6953** [comment]
Had gotten LGTM for latest changes from @sagarkapare on Slack:
image

**Pull request merged**
