### PR TITLE
CDAP-8095 Script: cdap version

### PR DESCRIPTION
**Pull request by wolf31o2**
Adds a context-sensitive `version` command to `cdap` script.

```
$ cdap version
CDAP configuration version 4.2.0-SNAPSHOT
CDAP cli version 4.2.0-SNAPSHOT
CDAP gateway version 4.2.0-SNAPSHOT
CDAP kafka version 4.2.0-SNAPSHOT
CDAP master version 4.2.0-SNAPSHOT
CDAP security version 4.2.0-SNAPSHOT
CDAP ui version 4.2.0-SNAPSHOT

```

### CODE REVIEW

**Comment by awholegunch** [comment]
What about Windows?

**Comment by wolf31o2** [comment]
Added Windows.

**Comment by bdmogal** [comment]
@wolf31o2 may be unrelated to this change, but the CLI should also somehow show the source checksum/revision number/commit hash just like so:
```
$ hdfs version
Hadoop 2.7.1.2.3.4.7-4
Subversion git@github.com:hortonworks/hadoop.git -r a07c8dd4174930367fb2d3b8c91eaad12828c37c
Compiled by jenkins on 2016-02-11T07:18Z
Compiled with protoc 2.5.0
From source with checksum cf48a4c63aaec76a714c1897e2ba8be6
This command was run using /usr/hdp/2.3.4.7-4/hadoop/hadoop-common-2.7.1.2.3.4.7-4.jar
```

**Comment by wolf31o2** [comment]
@bdmogal we don't have that information available to us, currently... I've filed [CDAP-9434](https://issues.cask.co/browse/CDAP-9434) to track the additional request

**Review by awholegunch — APPROVED** [review]
I have added a "the" and changed the order of the commands in the Windows usage to match that of the shell version. LGTM

**Pull request merged**
