### PR TITLE
[CDAP-17442] Fix post-run notifications for deployed pipelines take 2

### PR DESCRIPTION
**Pull request by njbriggs**
Jira: https://cdap.atlassian.net/browse/CDAP-17442

This fixes an issue with popovers from the material-ui upgrade by adjusting a z-index. It also adds a Cypress test to cover this flow.

This will need to be cherry-picked for 6.3.

Original proposed fix: #12891

### CODE REVIEW

**Comment by njbriggs** [comment]
E2E: https://builds.cask.co/browse/IT-UPD2210

**Review by elfenheart — APPROVED** [review]

**Comment by njbriggs** [comment]
Squashed to 1 commit

**Pull request merged**
