### PR TITLE
CDAP-7314 Fix broken example links

### PR DESCRIPTION
**Pull request by awholegunch**
Cherry-pick of #6835.

Passes a Quick Build: http://builds.cask.co/browse/CDAP-DQB143-1

Changed branch used to "develop" in cherry-pick.

### CODE REVIEW

**Comment by sagarkapare** [comment]
Does this need to go in 3.6? If so can you open it against release/3.6 branch. We merge 3.6 to develop periodically.

**Comment by awholegunch** [comment]
@sagarkapare It has been opened against release/3.6: https://github.com/caskdata/cdap/pull/6838.
I was told that I needed to open against all three branches, but two is plenty.

**Comment by awholegunch** [comment]
I've put this on-hold, as it might be needed still. Note https://github.com/caskdata/cdap/pull/6839/commits/9932414b1e79e3a5590d93965754a0dbf77133ac as it would not get created correctly in most merges from 3.6 to develop.

**Comment by awholegunch** [comment]
Closed as no longer required.

**Pull request closed without merging**
