### PR TITLE
[CDAP-7837] Remove versioned ProgramRuntimeArgs CLI and HTTP handler

### PR DESCRIPTION
**Pull request by ecfm**
https://issues.cask.co/browse/CDAP-7837
http://builds.cask.co/browse/CDAP-DUT5256-1

### CODE REVIEW

**Comment by ecfm** [comment]
Build is green

**Comment by bdmogal** [comment]
how come we're removing these without deprecating them first?

**Comment by ecfm** [comment]
They are not deprecated. Just because there's no support to store versioned RuntimeArgs. They are not documented for users either, so there should be no external usage.

**Comment by albertshau** [comment]
lgtm

**Pull request merged**
