### PR TITLE
Upgrade react-router from alpha release to stable v4 release

### PR DESCRIPTION
**Pull request by ajainarayanan**
- Upgrades `react-router` to v4 stable release & moves to `react-router-dom`
- One-on-One mapping for old to new components from react-router,

    | react-router (alpha-v4)        | react-router (stable v4)  |
    | ------------- |:-------------:|
    | Router      | BrowserRouter |
    | Match      | Route      |
    | Link | Link      |
    | Redirect | Redirect |
    | NavigationPrompt | Prompt |

- Fixes the following components,

  ```
    - EntityListView
    - Overview (all entities overview)
    - Detailed view (all entities detailed view)
    - Header (including ProductDropdown, NamespaceDropdown)
    - BreadCrumb,
    - 404
  ```
- Updates dll file with new react-router source
- Fixes wrangler to use the same.

#### Things todo:
- Add Unit tests
- Fix existing unit test that depend on routing.

Bamboo build: http://builds.cask.co/browse/CDAP-DRC6114-3

### CODE REVIEW

**Comment by tonybach** [comment]
Seems like the Datasets tab in App overview and detail views no longer works. Here's the error I got from React:

screen shot 2017-03-21 at 11 01 11 am

But it didn't point out the exact line this error was occurring at, so not very helpful...

**Comment by tonybach** [comment]
There also might be some problems with query params, since `?modalToOpen=explore` and `?modalToOpen=sendEvents` in stream detail view doesn't open up the modals anymore.

**Comment by ajainarayanan** [comment]
@tonybach ~I could not reproduce the `modalToOpen` bug that you mentioned. Can you try it again to see if the dataset tab error fixed it?~ Was able to reproduce  the issue. 

react-router v4 doesn't parse the query parameters anymore so we need to parse it manually. Missed on the detailed routes for streams and datasets. @tonybach Can you give it another try?

**Comment by nitinmotgi** [comment]
Why are we making such changes in the middle of tight release ? Was this scheduled ?

**Comment by ajainarayanan** [comment]
@nitinmotgi This change was not scheduled. This can go after extensive testing. We are right now using an alpha release of react-router library and this upgrades it to a stable release. People can review it whenever they are free as this is not blocking anything. It is solely for upgrading to a stable version of react-router (routing library)

**Comment by ajainarayanan** [comment]
Will re-open this against develop

**Pull request closed without merging**
