### PR TITLE
CDAP-13558 Support CDC pipelines on Spark version 2.x

### PR DESCRIPTION
**Pull request by mlozbin-cybervisiontech**
JIRA - https://issues.cask.co/browse/CDAP-13558
WIKI - https://wiki.cask.co/display/CE/CDC+Solution+Enhancements

Added new core template module for plugins based on Spark 2.

### CODE REVIEW

**Review by albertshau — COMMENTED** [review]
Are there any differences between these classes and the spark1 versions? 

If not, I think the plugin should be able to use the existing cdap-etl-api-spark dependency as long as it excludes spark-core and spark-streaming and includes the relevant spark2 versions of those dependencies. Does that not work with the plugin?

**Comment by mlozbin-cybervisiontech** [comment]
It seems I misunderstood convention in CDAP modules. For example, there are 2 modules with similar classes (cdap-api-spark and cdap-api-spark2_2.11). There is 1 difference actually in SparkHttpServiceContext class but method getSparkSession is not used anywhere. 
Answering your question. There are no differences in classes and it is possible to depend on cdap-etl-api-spark module with 3 exclusions (cdap-api-spark, spark-core_2.10, spark-streaming_2.10) but as for me it makes modules tight coupled and not safe to make any changes to plugin related to Spark 1. I'll wait for your decision here.
NOTE: Also I think dependencies on cdap-api-spark and cdap-etl-api should be in compile scope instead of provided.

**Comment by albertshau** [comment]
The reason we need spark1 and spark2 modules are if:

Any scala code is used -- spark1 and spark2 use binary incompatible scala versions
Any incompatible spark code is used -- for example if .flatMap() is used

In the case of cdap-etl-api-spark, neither of these are true so another module is not strictly needed, though it could be nice to have to avoid requiring module exclusions. Let's hold off on this for now.

As a side note, if we were to add this, since the code is exactly the same, we would want to follow the pattern done in https://github.com/cdapio/cdap/blob/develop/cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/pom.xml, where the code is copied from one module to the other, but with a different pom.

**Comment by albertshau** [comment]
Actually, I don't think plugin projects should have to exclude anything at all, as long as they are declaring spark2 as a dependency.

**Pull request closed without merging**
