### PR TITLE
Move copy-cli-etc from dist to rpm-prepare and copy to deb-prepare as…

### PR DESCRIPTION
**Pull request by wolf31o2**
… copy-cli-etc-deb

Otherwise, the `deb` target fails to find an `etc` directory.

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
LGTM. Merge once this has been tested.

**Comment by wolf31o2** [comment]
I confirmed that it works using one of the build agents.

**Comment by wolf31o2** [comment]
Using `mvn clean package -DskipTests -P examples,templates,dist,release,rpm-prepare,rpm,deb-prepare,deb,tgz,unit-tests -pl cdap-cli -am`:

```
main:
[INFO] Executed tasks
[INFO] 
[INFO] --- exec-maven-plugin:1.3.1:exec (rpm-package) @ cdap-cli ---
{:timestamp=>"2016-05-18T13:28:16.485724+0000", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2016-05-18T13:28:16.532426+0000", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2016-05-18T13:28:17.376706+0000", :message=>"Created package", :path=>"cdap-cli-3.5.0.1463577970160-1.noarch.rpm"}
[INFO] 
[INFO] --- exec-maven-plugin:1.3.1:exec (deb-package) @ cdap-cli ---
{:timestamp=>"2016-05-18T13:28:19.122294+0000", :message=>"Created package", :path=>"cdap-cli_3.5.0.1463577970160-1_all.deb"}
```

**Comment by chtyim** [comment]
Shouldn't need to do the same copying. There is a dist profile for that. I will take a look

**Comment by wolf31o2** [comment]
I had it in `dist`... However, `rpm` and `deb` use different staging directories. If you do it only in `dist` then one or the other won't get copied correctly. This is actually fixing that mistake.

**Comment by chtyim** [comment]
There is a step in the deb profile to copy everything from the rpm staging directory. Probably the ordering is causing the issue

**Pull request merged**
