### PR TITLE
[CDAP-15553] fixed issue with connections going down at origin for splitter

### PR DESCRIPTION
**Pull request by itsanudeep**
For splitter, the connection lines were going down at origin, look at the JIRA for screenshots. This PR is to fix the issue.

JIRA: https://issues.cask.co/browse/CDAP-15553
BUILD: https://builds.cask.co/browse/CDAP-DRC9321

### CODE REVIEW

**Comment by elfenheart** [comment]
Screen Shot 2019-06-21 at 1 53 07 PM

we want some small stub going straight outside the endpoint first before curving. Can you see if that can be done?

**Comment by itsanudeep** [comment]
> Screen Shot 2019-06-21 at 1 53 07 PM
> 
> we want some small stub going straight outside the endpoint first before curving. Can you see if that can be done?

Sure, will look into it.

**Comment by itsanudeep** [comment]
@elfenheart pushed changes to make the lines go outward before curving.

**Review by elfenheart — APPROVED** [review]
👍 LGTM

**Comment by elfenheart** [comment]
make sure to link to the right UI build

**Comment by itsanudeep** [comment]
Build: https://builds.cask.co/browse/CDAP-UDUT340-3

**Pull request merged**
