### PR TITLE
(CDAP-13835) Remove all examples

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Build passed https://builds.cask.co/browse/CDAP-DUT6709

**Review by albertshau — APPROVED** [review]
lgtm.

I believe this breaks a bunch of integration tests so it would be a good idea to change the versions in the integration test pom to use version 5.1.2 of the examples before merging this.

**Comment by anew** [comment]
Don't you need to change the top-level pom.xml, not to build examples? And the packaging for sandbox, not to include examples?

**Comment by chtyim** [comment]
@anew Those are changed in this PR already.

**Comment by anew** [comment]
Oh the pom changes were at the end of PR. I overlooked them between al the deleted files. +1

**Pull request merged**
