### PR TITLE
[CDAP-17627] Fix alignment of configuration Resources tab, esp. for real time

### PR DESCRIPTION
**Pull request by njbriggs**
Jira: https://cdap.atlassian.net/browse/CDAP-17627

* Narrow control width to match internal input width
* Fix margin to align CPU and Memory inputs

Real time:
image

Batch:
image

### CODE REVIEW

**Review by elfenheart — APPROVED** [review]

**Comment by njbriggs** [comment]
Build: https://builds.cask.co/browse/CDAP-UDUT964

**Pull request merged**
