### PR TITLE
Feature/rename packer dev

### PR DESCRIPTION
**Pull request by dereklwood**
This, along with Bamboo changes documented below, renames the SDK/VM artifacts, and the remote docker push repo.  Addresses the basic renaming requirements of https://issues.cask.co/browse/CDAP-11491

- [x] BUT build captures the name of the built SDK, and reads new maven properties for the name of the VM & Docker push repo
- [x] BUT build records these names in its Variables metadata artifact, to be used by the subsequent BA/DA builds

Supporting Bamboo build changes (impacting all branches) which much be deployed with this PR:
```
CDAP-BUT-BMA
  Script - Create Variables.txt

> 
> # capture cdap-standalone artifact, which was renamed in 4.2
> __standalone_artifact=$(basename $(ls -1 cdap/cdap-standalone/target/cdap*.zip))
> __standalone_artifact_name=${__standalone_artifact%-${bamboo.cdap.version}.zip}
> echo "standalone.artifact=${__standalone_artifact}" >> variables.txt
> echo "standalone.artifact.name=${__standalone_artifact_name}" >> variables.txt
> 
> # Extract the VM artifact name from Maven property
> __vm_artifact_name=$(/opt/maven/bin/mvn -q -f cdap/cdap-distributions/pom.xml -Dexec.executable='echo' -Dexec.args='${vm.artifact.name}' --non-recursive exec:exec)
> if [[ ${__vm_artifact_name} == '${vm.artifact.name}' ]]; then
>   __vm_artifact_name='cdap-standalone-vm'
> fi
> echo "vm.artifact.name=${__vm_artifact_name}" >> variables.txt
> 
> # Extract the Docker repo from Maven property
> __docker_repo=$(/opt/maven/bin/mvn -q -f cdap/cdap-distributions/pom.xml -Dexec.executable='echo' -Dexec.args='${docker.repo}' --non-recursive exec:exec)
> if [[ ${__docker_repo} == '${docker.repo}' ]]; then
>   __docker_repo='caskdata/cdap-standalone'
> fi
> echo "docker.repo=${__docker_repo}" >> variables.txt
> 


CDAP-BA-DCKR
  Script - Replace JSON VERSION and URI

2,3c2,3
<   -e "s#{{VERSION}}#${bamboo_inject_cdap_version}-${bamboo_inject_package_iteration}#g" \
<   -e "s#{{URI}}#file:///tmp/files/cdap/cdap-standalone/target/cdap-sdk-${bamboo_inject_cdap_version}.zip#g" \
---
>   -e "s#{{VERSION}}#${bamboo.inject.cdap.version}-${bamboo.inject.package.iteration}#g" \
>   -e "s#{{URI}}#file:///tmp/files/cdap/cdap-standalone/target/${bamboo.inject.standalone.artifact}#g" \

  Docker - Docker build, Repository:

1c1
< caskdata/cdap-standalone:${bamboo.inject.cdap.version}
---
> ${bamboo.inject.docker.repo}:${bamboo.inject.cdap.version}


CDAP-BA-VMI
  Script - Setup packer_cache and rename SDK/local downloads

6c6
< mv -f files/cdap/cdap-standalone/target/cdap-sdk-*.zip files/cdap-sdk.zip
---
> mv -f files/cdap/cdap-standalone/target/cdap-*.zip files/cdap-sdk.zip

  Command - Run Packer
1c1
< build -only=cdap-sdk-vm -var sdk_version=${bamboo.inject.cdap.version} cdap-sdk-ubuntu16-with-uri.json
---
> build -only=cdap-sdk-vm -var standalone_vm_name=${bamboo.inject.vm.artifact.name} -var sdk_version=${bamboo.inject.cdap.version} cdap-sdk-ubuntu16-with-uri.json


CDAP-DA-DSZ
  Command - Upload SDK

1c1
< sync --acl-public --progress cdap-sdk-${bamboo.inject.cdap.version}.zip s3://${bamboo.repository_s3_bucket}/downloads/co/cask/cdap/cdap-sdk/${bamboo.inject.cdap.version}/cdap-sdk-${bamboo.inject.cdap.version}.zip
---
> sync --acl-public --progress ${bamboo.inject.standalone.artifact} s3://${bamboo.repository_s3_bucket}/downloads/co/cask/cdap/${bamboo.inject.standalone.artifact.name}/${bamboo.inject.cdap.version}/${bamboo.inject.standalone.artifact}


CDAP-DA-DDI
  Command - Push Image to Docker Hub, Argument:
1c1
< push caskdata/cdap-standalone
---
> push ${bamboo.inject.docker.repo}

CDAP-DA-DVM
  Upload VM, Argument:
1c1
< sync --acl-public --progress cdap-standalone-vm-${bamboo.inject.cdap.version}.ova s3://${bamboo.repository_s3_bucket}/downloads/co/cask/cdap/cdap-standalone-vm/${bamboo.inject.cdap.version}/
---
> sync --acl-public --progress ${bamboo.inject.vm.artifact.name}-${bamboo.inject.cdap.version}.ova s3://${bamboo.repository_s3_bucket}/downloads/co/cask/cdap/${bamboo.inject.vm.artifact.name}/${bamboo.inject.cdap.version}/
```

### CODE REVIEW

**Comment by wolf31o2** [comment]
Use the Bamboo variable for the Maven location in the build, rather than hard-coding it.

**Review by wolf31o2 — APPROVED** [review]
One comment about the build... Code 👍 LGTM

**Comment by dereklwood** [comment]
Which variable are you referring to?  From the logs I see many Capability-related ones, but which to use, or when might they change?
 
 ``bamboo_build_commandline_com_atlassian_bamboo_plugins_maven_task_builder_mvn3_3=/opt/maven/bin/mvn``
``bamboo_build_commandline_com_atlassian_bamboo_plugins_maven_task_builder_mvn3_17=/opt/maven/bin/mvn``
``bamboo_capability_system_builder_mvn3_Maven_3_x=/opt/maven``
``bamboo_capability_system_builder_mvn3_Maven_3_1=/opt/maven``
``bamboo_capability_system_builder_mvn3_Maven_3=/opt/maven``

**Comment by wolf31o2** [comment]
We use "Maven 3.1" capability, so `bamboo_capability_system_builder_mvn3_Maven_3_1` is the variable. It changes when new versions are added. They're only removed by us. It matches the names used in the official elastic bamboo images, too. For example, Docker builds can run in elastic bamboo, but the on-disk path is different. Using the variable avoids this.

**Comment by dereklwood** [comment]
One additional note:  the changes to the packer template will need to be backported to all active release branches.

``packer -var x=y`` where x is not defined in the template throws an error.

**Pull request merged**
