### PR TITLE
[CDAP-16607] Expands plugin configuration, plugin templates and post run actions

### PR DESCRIPTION
**Pull request by ajainarayanan**
Cherry-picking https://github.com/cdapio/cdap/pull/12256 & https://github.com/cdapio/cdap/pull/12087

### CODE REVIEW

**Review by yukiej — APPROVED** [review]
lgtm!

**Comment by yukiej** [comment]
One thing to check for - when I open the plugin properties or postrun actions modal, and then make the screen size smaller, this hides the close button and I can't close the modal. This does not happen for hub.

**Comment by ajainarayanan** [comment]
> One thing to check for - when I open the plugin properties or postrun actions modal, and then make the screen size smaller, this hides the close button and I can't close the modal. This does not happen for hub.

Thanks @yukiej Good catch! Have fixed. Please give it another review

**Comment by yukiej** [comment]
Resizing looks good! 👍

**Comment by ajainarayanan** [comment]
Green build: https://builds.cask.co/browse/CDAP-URUT261-2

**Pull request merged**
