### PR TITLE
[CDAP-17417] Replace old schema editor with new schema editor in react side of app

### PR DESCRIPTION
**Pull request by ajainarayanan**
JIRA - https://cdap.atlassian.net/browse/CDAP-17417

### CODE REVIEW

**Review by njbriggs — APPROVED** [review]
Code LGTM.

From running the app, one question: In the schema editor, the checkbox and trash can look enabled, even though they should be disabled.

**Comment by ajainarayanan** [comment]
> Code LGTM.
> 
> From running the app, one question: In the schema editor, the checkbox and trash can look enabled, even though they should be disabled.

Have addressed this in the latest commit. 

Screen Shot 2020-12-03 at 11 28 06 PM

**Comment by njbriggs** [comment]
Changes to disable the controls LGTM 👍

**Pull request merged**
