### PR TITLE
adds remaining icons for run actions + plugins

### PR DESCRIPTION
**Pull request by astewes**
-  Adds run player icons
-  Adds additional plugin + custom action icons
-  Adds background color to run player
-  Removes "selected" class and associated styling from my-dag
-  Adds min-width to detail view metadata container

app status + last run background color w/padding:
bgcolor

Runtime Args button fix + addition of spark stream icon:
spark

### CODE REVIEW

**Comment by astewes** [comment]
Bamboo build: http://builds.cask.co/browse/CDAP-DRC4282

**Comment by elfenheart** [comment]
screen shot 2016-08-16 at 6 12 47 pm

the trash and plus button looks funky to me

**Comment by elfenheart** [comment]
the spark streaming icon is still missing from next to the pipeline name or in the list view

**Comment by nitinmotgi** [comment]
Also, the play is not as per mocks!

**Comment by ajainarayanan** [comment]
Noticed two things,
- Icons appear smaller than before now? I was never able to see HBASE even after full zoom
  screen shot 2016-08-17 at 7 33 55 pm
- Scheduling is super snappy and I am not sure if we are giving the right feedback for the user about whatever is happening. I feel it should be a smooth transition rather than snappy.

**Comment by elfenheart** [comment]
👍  LGTM

**Pull request merged**
