### PR TITLE
Feature/merge 3.6

### PR DESCRIPTION
**Pull request by bdmogal**
Fair amount of conflicts. Plus, git did not do a great job of merging. So running a build - http://builds.cask.co/browse/CDAP-DUT4840-1

### CODE REVIEW

**Comment by bdmogal** [comment]
Please review the conflicts fixed in:
1. `ResolvingDiscoverable.java`
2. `AuthServerAnnounceTest.java`
3. `ExternalAuthenticationServer.java`
4. `TrackerAppCreationService.java`
5. `AppLifecycleHttpHandler.java`
6. `AppLifecycleHttpHandlerTest.java`
7. `ProgramLifecycleService.java`

**Comment by sagarkapare** [comment]
Resolved conflicts LGTM 👍

**Comment by anwar6953** [comment]
@bdmogal what feature in 4.0 did the conflicts result due to?

**Comment by bdmogal** [comment]
@anwar6953 a combination of:
1. The `EntityId` PRs
2. https://github.com/caskdata/cdap/pull/6551
3. https://github.com/caskdata/cdap/pull/6629

**Comment by anwar6953** [comment]
alright; was just curious.
LGTM

**Comment by bdmogal** [comment]
Build - http://builds.cask.co/browse/CDAP-DUT4840-2. Merging.

**Pull request merged**
