### PR TITLE
Perform Keytab login for upgrade tool and queue debugger

### PR DESCRIPTION
**Pull request by anwar6953**
Perform Keytab login for upgrade tool and queue debugger.
See JIRA for more in-depth explanation:

https://issues.cask.co/browse/CDAP-7438
http://builds.cask.co/browse/CDAP-RUT226-1

### CODE REVIEW

**Review by wolf31o2 — APPROVED** [review]
:+1: LGTM

**Comment by chtyim** [comment]
Are these the only two tools we have?

**Comment by wolf31o2** [comment]
SimpleHBaseQueueDebugger is a wrapper for HBaseQueueDebugger. There's also the transaction debugger and ETL upgrade tools.

**Comment by anwar6953** [comment]
Spoke with @albertshau - the ETL upgrade tool doesn't require Kerberos credentials; it uses an CDAP auth token, and interacts with CDAP entirely via REST APIs.

**Comment by wolf31o2** [comment]
Transaction debugger gets a token, too.

**Comment by anwar6953** [comment]
Yep; confirmed with @poornachandra. It interacts just via REST API; doesn't need Kerberos credentials.

**Comment by anwar6953** [comment]
Tested on cluster; the build failed due to a flaky test case.
Merging.

**Pull request merged**
