### PR TITLE
CDAP-8345 TMS hdfs directory for coprocessors under /cdap is not required

### PR DESCRIPTION
**Pull request by gokulavasan**
JIRA : https://issues.cask.co/browse/CDAP-8345
Build : https://builds.cask.co/browse/CDAP-DUT5877

### CODE REVIEW

**Comment by gokulavasan** [comment]
Build is 🍏

**Comment by sreevatsanraman** [comment]
These changes look good. Is there a corresponding docs change?

**Comment by gokulavasan** [comment]
@sreevatsanraman There are no documentation around this property in the docs. Are you referring to updating of MD5 of the cdap-default.xml?

**Comment by sreevatsanraman** [comment]
We will need to update the md5 if we changed the docs. Why does this property not surface in the cdap-default docs? It should, right?

**Comment by gokulavasan** [comment]
@sreevatsanraman Not sure, I searched for the property name but it didn't show up in cdap-docs.

**Comment by sreevatsanraman** [comment]
LGTM

**Pull request merged**
