### PR TITLE
CDAP-13759 Rename metadata tables

### PR DESCRIPTION
**Pull request by CuriousVini**
Build: https://builds.cask.co/browse/CDAP-RUT1586-1
Currently Testing against the cluster

### CODE REVIEW

**Comment by rohitsinha54** [comment]
Can you add the complete table name which gets created here or better if it's in comment of code?

**Comment by sreevatsanraman** [comment]
@rohitsinha54 - we don't add complete table name anywhere. Also it is tied to the hbase versions and dependent on HBase. So, I don't see a point in adding it.

**Comment by rohitsinha54** [comment]
Then in the PR to make sure what table is being created.

**Comment by rohitsinha54** [comment]
@sreevatsanraman I am not sure what do you mean by table name being tied to hbase version though. Do we generate different names based on hbase versions? I think the only configurable part is table name prefix if one is defined in cdap-site but then that applied to all tables.

**Comment by sreevatsanraman** [comment]
Older hbase versions don't have namespaces so we do custom naming with underscores.

**Comment by rohitsinha54** [comment]
@sreevatsanraman : Oh I see. Didn't know that. 👍

**Review by sreevatsanraman — APPROVED** [review]

**Comment by rohitsinha54** [comment]
### [Issue](https://issues.cask.co/browse/CDAP-13759)

### This PR introduces the following change:
#### Old Metadata Table Name: 
>system.metadata.metadata_index.d
system.metadata.metadata_index.i

#### New Metadata Table Names:
>v2.system.metadata_index.d
v2.system.metadata_index.i

Note: The table names are not namespaced.

**Review by rohitsinha54 — APPROVED** [review]

**Comment by CuriousVini** [comment]
Tested on the upgraded cluster:

image

**Comment by CuriousVini** [comment]
Merging the changes.

**Pull request merged**
