### PR TITLE
CDAP-2388 Upgrade guice version to 4.0.

### PR DESCRIPTION
**Pull request by anwar6953**
[CDAP-2388](https://issues.cask.co/browse/CDAP-2388) This is in order to help support Java 8.
For changes, see: https://github.com/google/guice/wiki/Guice40

Unit tests: https://builds.cask.co/browse/CDAP-DUT6345-3
Integration tests: https://builds.cask.co/browse/IT-ITM-19

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM

**Comment by anwar6953** [comment]
@chtyim there were unit test failures with guice 4.2.0, so I'm using version 4.0 instead.

**Comment by chtyim** [comment]
What are the errors?

**Comment by anwar6953** [comment]
With guice 4.2.0, the failures are here: https://builds.cask.co/browse/CDAP-DUT6345-1.
However, with guice 4.0, the unit tests and integration tests pass, so I'm using 4.0.

**Comment by chtyim** [comment]
Hum, they added Guava dependency starting from Guice 4+ ... Anyway, use 4.0 for now and need to figure out how to deal with the guice issue later.

**Pull request merged**
