### PR TITLE
fix in - twill log entry adapter to include className, method…

### PR DESCRIPTION
**Pull request by gsps1**
…eName, lineNumber in caller data writing to master logs

JIRA : https://issues.cask.co/browse/CDAP-12559

### CODE REVIEW

**Comment by gsps1** [comment]
build running : https://builds.cask.co/browse/CDAP-RUT1359-1

**Comment by chtyim** [comment]
Changes LGTM. How's the output looks like?

**Comment by gsps1** [comment]
Without changes :
```
2017-09-11 19:45:06,097 - INFO  [leader-election-tx.service-leader:?@?] - Transaction Thrift Service started successfully on cdhcls27212-1000.dev.continuuity.net/10.250.0.14:33687
```
With changes:
```
2017-09-11 20:33:46,441 - INFO  [leader-election-tx.service-leader:o.a.t.d.TransactionService$1@113] - Transaction Thrift Service started successfully on cdhcls27212-1000.dev.cont
inuuity.net/10.250.0.14:44713
```

**Comment by chtyim** [comment]
Cool, how about the case that it has throwable?

**Comment by anew** [comment]
Please update the commit message to include the Jira (CDAP-???) and little better wording, then LGTM

**Comment by gsps1** [comment]
@chtyim Error log
```
2017-09-12 18:48:21,118 - ERROR [MapReduceRunner-phase-1:o.a.h.c.Configuration@2105] - MapReduce program 'phase-1' failed with error: Class org.apache.hadoop.hive.metastore.Defaul
tMetaStoreFilterHookImpl not found. Please check the system logs for more details.
java.lang.ClassNotFoundException: Class org.apache.hadoop.hive.metastore.DefaultMetaStoreFilterHookImpl not found
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2105)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2197)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2223)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.loadFilterHooks(HiveMetaStoreClient.java:238)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:190)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:179)
        at org.apache.hive.hcatalog.common.HiveClientCache$CacheableHiveMetaStoreClient.<init>(HiveClientCache.java:303)
        at org.apache.hive.hcatalog.common.HiveClientCache$5.call(HiveClientCache.java:227)
        at org.apache.hive.hcatalog.common.HiveClientCache$5.call(HiveClientCache.java:224)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
        at org.apache.hive.hcatalog.common.HiveClientCache.getOrCreate(HiveClientCache.java:224)
        at org.apache.hive.hcatalog.common.HiveClientCache.get(HiveClientCache.java:200)
        at org.apache.hive.hcatalog.common.HCatUtil.getHiveClient(HCatUtil.java:558)
        at org.apache.hive.hcatalog.mapreduce.HCatOutputFormat.setOutput(HCatOutputFormat.java:90)
        at co.cask.hydrator.plugin.batch.sink.HiveBatchSink$HiveSinkOutputFormatProvider.<init>(HiveBatchSink.java:122)
        at co.cask.hydrator.plugin.batch.sink.HiveBatchSink.prepareRun(HiveBatchSink.java:82)
        at co.cask.hydrator.plugin.batch.sink.HiveBatchSink.prepareRun(HiveBatchSink.java:62)
        at co.cask.cdap.etl.common.plugin.WrappedBatchSink$1.call(WrappedBatchSink.java:54)
        at co.cask.cdap.etl.common.plugin.WrappedBatchSink$1.call(WrappedBatchSink.java:51)
        at co.cask.cdap.etl.common.plugin.Caller$1.call(Caller.java:30)
        at co.cask.cdap.etl.common.plugin.StageLoggingCaller.call(StageLoggingCaller.java:40)
        at co.cask.cdap.etl.common.plugin.WrappedBatchSink.prepareRun(WrappedBatchSink.java:51)
        at co.cask.cdap.etl.common.plugin.WrappedBatchSink.prepareRun(WrappedBatchSink.java:37)
        at co.cask.cdap.etl.common.submit.SubmitterPlugin$3.run(SubmitterPlugin.java:83)
        at co.cask.cdap.internal.app.runtime.AbstractContext$3.run(AbstractContext.java:516)
        at co.cask.cdap.data2.transaction.Transactions$CacheBasedTransactional.finishExecute(Transactions.java:235)
        at co.cask.cdap.data2.transaction.Transactions$CacheBasedTransactional.execute(Transactions.java:223)
        at co.cask.cdap.internal.app.runtime.AbstractContext.execute(AbstractContext.java:511)
        at co.cask.cdap.internal.app.runtime.AbstractContext.execute(AbstractContext.java:499)
        at co.cask.cdap.etl.common.submit.SubmitterPlugin.prepareRun(SubmitterPlugin.java:79)
        at co.cask.cdap.etl.batch.mapreduce.ETLMapReduce.initialize(ETLMapReduce.java:350)
        at co.cask.cdap.api.mapreduce.AbstractMapReduce.initialize(AbstractMapReduce.java:122)
        at co.cask.cdap.api.mapreduce.AbstractMapReduce.initialize(AbstractMapReduce.java:33)
        at co.cask.cdap.internal.app.runtime.batch.MapReduceRuntimeService.doInitialize(MapReduceRuntimeService.java:567)
        at co.cask.cdap.internal.app.runtime.batch.MapReduceRuntimeService.beforeSubmit(MapReduceRuntimeService.java:540)
        at co.cask.cdap.internal.app.runtime.batch.MapReduceRuntimeService.startUp(MapReduceRuntimeService.java:224)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$1.run(AbstractExecutionThreadService.java:47)
        at co.cask.cdap.internal.app.runtime.batch.MapReduceRuntimeService$1$1.run(MapReduceRuntimeService.java:441)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by chtyim** [comment]
LGTM

**Pull request merged**
