### PR TITLE
(CDAP-11779) Added auto cleanup of Spark interpreter directory

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Build https://builds.cask.co/browse/CDAP-RUT1095

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
The 2nd commit is just renaming `SparkInterpreterCleanupManager` to `SparkCompilerCleanupManager`. No logic change. Rerunning the build.

**Comment by chtyim** [comment]
Build passed.

**Comment by chtyim** [comment]
Squashed and merging.

**Pull request merged**
