### PR TITLE
[CDAP-8203] Add calls to action for all entity 'creation'	

### PR DESCRIPTION
**Pull request by tonybach**
JIRA: https://issues.cask.co/browse/CDAP-8203
Bamboo: http://builds.cask.co/browse/CDAP-DRC5490

The secondary call to actions for Stream creation are not fully implemented yet, since it requires interacting with the Stream Details page.

### CODE REVIEW

**Comment by elfenheart** [comment]
You didn't add the CTA to StreamCreate wizard? Only StreamCreateWithUpload?

**Comment by tonybach** [comment]
@elfenheart I talked to Bhooshan, and he said that we shouldn't add the CTA for for stream uploads in the Market (which is where the StreamCreate component is used). Since they're usually one of the steps in an use case, we should still show the done steps and skipped steps like before.

**Comment by elfenheart** [comment]
@tonybach @bdmogal that seems weird, because the following steps like upload data pack in the use case do have the call to action. This becomes an inconsistency with the steps

**Comment by bdmogal** [comment]
I meant there shouldn't be an intermediate call to action in a usecase. e.g. If the usecase ends up creating a pipeline, then the CTA should be to display the pipeline in the Studio. But if an intermediate step (e.g. step 2/5) creates a stream, we shouldn't have CTA to go to the stream page after step 2/5.

**Comment by tonybach** [comment]
For entity creation during steps of an use case in Market, I'll create a separate PR to change the CTAs for those.

**Comment by elfenheart** [comment]
👍  LGTM

**Pull request merged**
