### PR TITLE
Feature/bump develop version

### PR DESCRIPTION
**Pull request by CuriousVini**
First commit: `mvn versions:set -DnewVersion=4.1.0-SNAPSHOT -DgenerateBackupPoms=false -P examples`
Rest of the commits are manually updated for archetype, hydrator, tracker etc.

cdap: from `4.0.0-SNAPSHOT` to `4.1.0-SNAPSHOT`
hydrator: from `1.5.0-SNAPSHOT` to `1.6.0-SNAPSHOT`
tracker: from `0.3.0-SNAPSHOT` to `0.4.0-SNAPSHOT`

I verified that `4.0.0-SNAPSHOT` and `1.5.0-SNAPSHOT` does not exist in codebase.

### CODE REVIEW

**Comment by elfenheart** [comment]
UI version bump LGTM 👍

**Review by wolf31o2 — CHANGES_REQUESTED** [review]
Missing the `cdap-distributions` updates... the version should be updated to prevent `CDAP-BUT` failures once 4.0.0 is released.

**Review by wolf31o2 — APPROVED** [review]

**Comment by wolf31o2** [comment]
👍 on the `cdap-distributions` changes

**Comment by awholegunch** [comment]
Docs changes LGTM.

**Comment by anwar6953** [comment]
I believe this file also needs to be modified:
cdap-docs/_common/common-build.sh

@awholegunch can probably confirm.

**Comment by CuriousVini** [comment]
@anwar6953 Talked to @awholegunch offline. We do not change versions in `cdap-docs/_common/common-build.sh`. Could you please take another look when you get a chance, thanks.

**Comment by anwar6953** [comment]
lgtm

**Pull request merged**
