### PR TITLE
[CDAP-13305] Report app spark1 and spark2 compatibility

### PR DESCRIPTION
**Pull request by ecfm**
https://issues.cask.co/browse/CDAP-13305

This PR adds the module for Spark1 compatibility codes in `cdap-program-report1_2.10`

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
Does the unit test cover both spark 1 & 2?

**Comment by ecfm** [comment]
@sreevatsanraman Yes, the only change in the unit test is to set the correct version of Spark compat in the TestConfiguration. Once it's copied to each package, it will be run with each version of Spark

**Comment by ecfm** [comment]
Temporarily close this until #10176 is merged

**Comment by maochf** [comment]
Reopen the PR with base `feature/CDAP-13305-refactor-report-app-spark2`

**Pull request closed without merging**
