### PR TITLE
(CDAP-11874) Fix Spark SQL class loader leaks

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Verified on SDK with heapdump.

**Comment by chtyim** [comment]
Building https://builds.cask.co/browse/CDAP-RUT1139

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Build passed with the fix for CDAP-11939.

https://builds.cask.co/browse/CMP-BSP-181

**Comment by sagarkapare** [comment]
Second commit LGTM 👍

**Pull request merged**
