### PR TITLE
[CDAP-8425] Switch to Classic View

### PR DESCRIPTION
**Pull request by elfenheart**
JIRA: https://issues.cask.co/browse/CDAP-8425

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@elfenheart 

responsive

We might want to adjust the media queries for header bar now that we have more room for rendering the entire header bar before collapsing to hamburger menu, unless we are not adding spotlight search back. I think we set it to collapse at 1011px. 

Otherwise 👍 LGTM

**Comment by elfenheart** [comment]
Modified the breakpoint to `860px`

**Comment by elfenheart** [comment]
Build: http://builds.cask.co/browse/CDAP-DRC5842-3

**Comment by ajainarayanan** [comment]
👍 LGTM

**Pull request merged**
