### PR TITLE
Update dataset RESTful APIs for dataset principal

### PR DESCRIPTION
**Pull request by rohitsinha54**
Also adds a section for dataset meta.

Quick Build: http://builds.cask.co/browse/CDAP-DQB292-1

### CODE REVIEW

**Comment by awholegunch** [comment]
I've started a new Quick Build: http://builds.cask.co/browse/CDAP-DQB292-2
I've updated and changed the tables and the copy. Added additional formatting commands elsewhere in the file to improve the rendering of JSON examples. 
Please check my commit carefully.
LGTM.

**Comment by awholegunch** [comment]
Running another Quick Build: http://builds.cask.co/browse/CDAP-DQB292-3 (this is expected to fail, as release/4.1 was broken)

Page of interest: http://builds.cask.co/artifact/CDAP-DQB292/shared/build-3/Docs-HTML/html/reference-manual/http-restful-api/dataset.html

**Comment by awholegunch** [comment]
LGTM. @rohitsinha54 could you do a final check and merge?

**Comment by sreevatsanraman** [comment]
LGTM

**Pull request merged**
