### PR TITLE
CDAP-17059 validate no actions in the middle of a pipeline

### PR DESCRIPTION
**Pull request by albertshau**

### CODE REVIEW

**Review by fernst — APPROVED** [review]
LGTM.

nit: Would it be possible to capture the names of all the failed stages before returning the exception? This can help a user identify all actions that need to be deleted/connected.

**Comment by albertshau** [comment]
It would definitely be better, but I'm holding off on that for future work. 

It requires a little bit of restructuring, which we're planning on doing when we add pipeline level validation. Similar to how stage level validation will return the full set of errors with details about what needs to be highlighted, we're planning on doing something similar to structural issues like this, cycles, etc.

**Review by supriyapatil-google — APPROVED** [review]
Thanks!

**Pull request merged**
