### PR TITLE
[CDAP-6236] CLI commands with spaces in path

### PR DESCRIPTION
**Pull request by liu-joe**

### CODE REVIEW

**Comment by liu-joe** [comment]
https://github.com/caskdata/common/pull/40 is also part of the same ticket

**Review by russorat — APPROVED** [review]
Lgtm

**Comment by sreevatsanraman** [comment]
cdap-common 0.9 is released. It should be available within 2 hours in maven central http://repo1.maven.org/maven2/co/cask/common/common-cli/ 

ETA: noon PST 02/07

**Comment by liu-joe** [comment]
opening a new pr for this: https://github.com/caskdata/cdap/pull/7869

**Pull request closed without merging**
