### PR TITLE
Spark HiveContext fixes

### PR DESCRIPTION
**Pull request by chtyim**
This PR fixes two issues:

1. (CDAP-12243) Make SparkClassLoader exposes underlying URLs
2. (CDAP-12330) Localize Hadoop and hive configs to Spark container

### CODE REVIEW

**Comment by chtyim** [comment]
Tried on CDH 5.10 cluster. Successfully issuing SQL query via {{HiveContext}} to get a list of tables.

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Building https://builds.cask.co/browse/CDAP-RUT1341

**Comment by chtyim** [comment]
The last commit is to fix a thread leakage problem in local mode when running PySpark. The idea is to capture the python worker monitor thread (via rewriting the constructor) and then interrupt the thread on program completion.

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Only one known flaky test failed (https://issues.cask.co/browse/CDAP-9260) . Merging.

**Pull request merged**
