### PR TITLE
CDAP-14161 Added retry logic for checking the provisioning state.

### PR DESCRIPTION
**Pull request by sagarkapare**
JIRA: https://issues.cask.co/browse/CDAP-14161

### CODE REVIEW

**Review by chtyim — APPROVED** [review]
LGTM

**Review by anwar6953 — APPROVED** [review]
Edit: Seems like Terence already did.

**Comment by anwar6953** [comment]
test

**Review by anew — APPROVED** [review]
+1. This will effectively fix https://builds.cask.co/browse/CDAP-BUT-1426. I mean by fixing https://issues.cask.co/browse/CDAP-14131

**Comment by sagarkapare** [comment]
Build is green - https://builds.cask.co/browse/CDAP-DUT6591-1. Merging.

**Pull request merged**
