### PR TITLE
CDAP-6666 impersonation fix StreamFileJanitor cleanup

### PR DESCRIPTION
**Pull request by gsps1**
JIRA : https://issues.cask.co/browse/CDAP-6666

### CODE REVIEW

**Comment by gsps1** [comment]
http://builds.cask.co/browse/CDAP-DUT4552-1

**Comment by gsps1** [comment]
only "get" for base location needs to be impersonated. subsequent iteration through files in the base location and cleanup of them will use the same impersonated user. however if we wrap those operations in impersonation callable, will cause `cdap_system:app.meta` to be accessed by "user" instead of "cdap" causing the failure when we executing co.cask.cdap.data.stream.service.MDSStreamMetaStore#streamExists.

**Comment by gokulavasan** [comment]
LGTM 👍

**Comment by gsps1** [comment]
Build is green, merging.

**Pull request merged**
