### PR TITLE
CDAP-11568 document the new spark2 example app

### PR DESCRIPTION
**Pull request by albertshau**
Added a Quick Build: https://builds.cask.co/browse/CDAP-DQB350-2

### CODE REVIEW

**Comment by awholegunch** [comment]
I've made a few changes. Please take a look. Running a Quick Build. Docs LGTM, though I have not (yet) tested the application. Let me test it before we merge to check the instructions.

**Comment by albertshau** [comment]
edits lgtm

**Comment by awholegunch** [comment]
"On-hold" until we've finished successful manual testing.

**Comment by awholegunch** [comment]
Re-ran the Quick Build: https://builds.cask.co/browse/CDAP-DQB350-3

**Comment by awholegunch** [comment]
Corrected the instructions. Tested successfully manually. 
Re-running Quick Build: https://builds.cask.co/browse/CDAP-DQB350-4

Page of interest: https://builds.cask.co/artifact/CDAP-DQB350/shared/build-4/Docs-HTML/4.2.0-SNAPSHOT/en/examples-manual/examples/decision-tree-regression.html

**Comment by sreevatsanraman** [comment]
LGTM

**Pull request merged**
