### PR TITLE
CDAP-4208 Fix testWorkerInstances flaky test

### PR DESCRIPTION
**Pull request by gokulavasan**
JIRA : https://issues.cask.co/browse/CDAP-4208
Build : http://builds.cask.co/browse/CDAP-DUT4486-1

### CODE REVIEW

**Comment by gsps1** [comment]
the stack trace @poornachandra  pasted says expected is <3> but actual is <5>, however the existing check (before the fix) doesn't seem to check for 3.. do you know why it was expecting 3 then ?

**Comment by albertshau** [comment]
lgtm, though this is a confusing test

**Comment by gokulavasan** [comment]
@gsps1 It was checking for 3 here : https://github.com/caskdata/cdap/pull/6154/files#diff-7ba8564ee62f45aad57f64190cac9e02R1091

**Comment by gokulavasan** [comment]
Build is 🍏 . Merging.

**Pull request merged**
