### PR TITLE
CDAP-13526 'DataProc'->'Dataproc'.

### PR DESCRIPTION
**Pull request by anwar6953**
https://issues.cask.co/browse/CDAP-13526

### CODE REVIEW

**Comment by anwar6953** [comment]
https://builds.cask.co/browse/CDAP-DUT6614

**Review by albertshau — DISMISSED** [review]
lgtm

**Comment by anwar6953** [comment]
@albertshau I resolved conflicts, so will need another LGTM before I can merge.

**Review by albertshau — APPROVED** [review]
lgtm

**Pull request merged**
