### PR TITLE
[CDAP-16290] Added recordLineage to SparkSink and StreamingSource classes for spark streaming plugins

### PR DESCRIPTION
**Pull request by vravish**

### CODE REVIEW

**Comment by yaojiefeng** [comment]
We shouldn't introduce this change in cdap. CDAP shouldn't have any dependencies on hydrator since that will introduce circular dependencies. Also recordLineage should not be in the interface, currently only plugin with reference name can have field lineage, let's put the method in ReferenceBatchSource and ReferenceBatchSink. We should close this one

**Comment by vravish** [comment]
> We shouldn't introduce this change in cdap. CDAP shouldn't have any dependencies on hydrator since that will introduce circular dependencies. Also recordLineage should not be in the interface, currently only plugin with reference name can have field lineage, let's put the method in ReferenceBatchSource and ReferenceBatchSink. We should close this one

But there's one plugin that directly extends BatchSink or BatchSource instead of Reference classes. How will that plugin have access to this method unless we copy it?

**Comment by yaojiefeng** [comment]
That's a separate problem. Anyway we shouldn't introduce this dependency. It will break the build. If it directly extends the interface, we should make it extend Reference classes or just record lineage in the plugin itself

**Comment by vravish** [comment]
Ack. Closing this one, please review https://github.com/cdapio/hydrator-plugins/pull/1071

**Pull request closed without merging**
