### PR TITLE
[CDAP-7408] Configure a limit for the transaction timeout

### PR DESCRIPTION
**Pull request by anew**
This is implemented in Tephra, we only need to configure it.
- add property  in cdap-default.xml
-  bring back test case inherited from Tephra

### CODE REVIEW

**Comment by anew** [comment]
Build is here: http://builds.cask.co/browse/CDAP-DUT5058

**Comment by chtyim** [comment]
LGTM

**Comment by chtyim** [comment]
Lgtm

**Comment by anew** [comment]
Build passed: http://builds.cask.co/chain/result/viewChainResult.action?planKey=CDAP-DUT5058&buildNumber=2

Squashing and merging.

**Pull request merged**
