### PR TITLE
[CDAP-12674] Fixes showing duration or start time of a program in UI only when it is available

### PR DESCRIPTION
**Pull request by ajainarayanan**
JIRA: https://issues.cask.co/browse/CDAP-12674
Build: https://builds.cask.co/browse/CDAP-UDUT49

### CODE REVIEW

**Review by elfenheart — APPROVED** [review]
👍 LGTM

**Comment by anwar6953** [comment]
The Pipeline Summary page (charts) also uses the start time value, right?

**Comment by ajainarayanan** [comment]
@anwar6953 Yes. The duration will anyways change when the program is running right?

**Comment by anwar6953** [comment]
The duration will drop as soon as the `start` time becomes non-null?

**Comment by ajainarayanan** [comment]
Talked to @anwar6953 @bdmogal. We decided to file JIRA https://issues.cask.co/browse/CDAP-14146 to decide on this and change in pipeline summary and duration of the current run in UI once we have a decision. 

Merging this PR for now as the current UI is broken when UI gets null values for start time.

**Pull request merged**
