### PR TITLE
log permissions fix

### PR DESCRIPTION
**Pull request by gsps1**
minor fix. we have to use the permissions when  opening output stream too. else it gets overwritten.

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM

**Comment by gsps1** [comment]
noticing some test failures. looking into this.

**Comment by gsps1** [comment]
build passed after the fix in local log appender - http://builds.cask.co/browse/CDAP-RUT624-2 . will resolve conflicts and merge.

**Comment by chtyim** [comment]
LGTM

**Pull request merged**
