### PR TITLE
ETLMapReduce/ETLSpark output aliasing

### PR DESCRIPTION
**Pull request by gokulavasan**
Backporting of #5930 for release/3.4.

Build : http://builds.cask.co/browse/CDAP-DUT4286-1

### CODE REVIEW

**Comment by rohitsinha54** [comment]
Github diff shows +45 lines and -69 for this one and -71 for the PR which was merged to develop. 
I  noticed a removal of Dataset from cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkBatchSourceContext.java in the other PR. 
Is this used somewhere in 3.4 in this class or can it be removed ? 
I was not able to find the other line which is removed in develop but not here. Can you point it out ?

**Comment by gokulavasan** [comment]
@rohitsinha54 Both Dataset and BatchReadable classes are used here in 3.4. Hence those imports cannot be removed. https://github.com/caskdata/cdap/pull/5943/files#diff-f374e11c109dc163329bb3e9ea001aecR77 . And probably those imports were unused in develop when I was working and so those were removed in develop through my original PR

**Comment by rohitsinha54** [comment]
LGTM

**Comment by gokulavasan** [comment]
Build passed. Merging.

**Pull request merged**
