### PR TITLE
(CDAP-5113) Use YarnClient instead of HTTP to get Yarn RM reports

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by anwar6953** [comment]
I think this will also resolve: https://issues.cask.co/browse/CDAP-6913

**Comment by chtyim** [comment]
Yes it does

**Comment by anwar6953** [comment]
lgtm

**Comment by anwar6953** [comment]
Would it also resolve https://issues.cask.co/browse/CDAP-6189?

**Comment by chtyim** [comment]
Yes. For CDAP-6189, need to backport?

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-DUT4620-2

**Pull request merged**
