### PR TITLE
[UI] Fixes the backend/Nodejs down message

### PR DESCRIPTION
**Pull request by ajainarayanan**
- Fixes backend or nodejs down message show in UI
- Fixes angular side of app to poll for backend status

### CODE REVIEW

**Review by elfenheart — APPROVED** [review]
👍 LGTM, just have to add logviewer startPollingForBackendStatus

**Comment by yukiej** [comment]
Can you include screenshots to this PR for future reference? Thank you!

**Comment by ajainarayanan** [comment]
Screen Shot 2020-05-15 at 3 05 43 PM

Screen Shot 2020-05-15 at 3 08 10 PM

**Comment by ajainarayanan** [comment]
Green build: https://builds.cask.co/browse/CDAP-URUT252-1

**Pull request merged**
