### PR TITLE
(CDAP-6933) Remove the alias Action.ALL and instead force users to ex…

### PR DESCRIPTION
**Pull request by bdmogal**
…plicitly specify all actions for authorization.

Jira: [CDAP-6933](https://issues.cask.co/browse/CDAP-6933)
Build: http://builds.cask.co/browse/CDAP-RUT95

### CODE REVIEW

**Comment by bdmogal** [comment]
This will need a follow-up in the security extensions repo. Will open a PR for that.

**Comment by anwar6953** [comment]
worth it to put `EnumSet.allOf(Action.class)` in a constant somewhere?

**Comment by anwar6953** [comment]
lgtm

**Comment by bdmogal** [comment]
`EnumSet.allOf(Action.class)` is not too verbose, plus it makes things sufficiently clear, so that we don't have to refer to a constant defined somewhere else?

**Comment by bdmogal** [comment]
Rebased and ran relevant tests locally. Also, from the reported bug:

```
cdap (http://example.com:10000/namespace:default)> revoke actions ALL on entity namespace:instant from role .namespace:instant
e actions ALL on entity namespace:instant from role .namespace:instant
Error: No enum constant co.cask.cdap.proto.security.Action.ALL
```

**Comment by bdmogal** [comment]
Merging.

**Pull request merged**
