### PR TITLE
[CDAP-8430][CDAP-8933] "No Entities Found" message improvements

### PR DESCRIPTION
**Pull request by tonybach**
[CDAP-8430] https://issues.cask.co/browse/CDAP-8430
[CDAP-8933] https://issues.cask.co/browse/CDAP-8933

- Added Browse Cask Market CTA
- Changed default message to include namespace name

TODO: add an unit test for the Browse Market CTA.

### CODE REVIEW

**Comment by bdmogal** [comment]
@tonybach Functionality works. For the text, can you add a ``;`` after every CTA except the last one?
```
Clear your search; or
Add new entities; or
Browse Cask Market
```

**Comment by elfenheart** [comment]
@bdmogal Updated

screen shot 2017-03-12 at 3 51 39 pm

**Comment by elfenheart** [comment]
👍  LGTM on @tonybach changes

**Review by bdmogal — APPROVED** [review]
LGTM

**Comment by elfenheart** [comment]
Build: http://builds.cask.co/browse/CDAP-DRC6062-5

**Pull request merged**
