### PR TITLE
CDAP-17298 Upgrade Material-ui

### PR DESCRIPTION
**Pull request by njbriggs**
Upgrades `@material-ui/core` to `4.11.0` and `@material-ui/icons` to 4.9.1.

We've tested the UI with this upgrade and found no functional regressions. We have found some visual differences, such as the top-bar popups on the deployed pipeline page.

### CODE REVIEW

**Comment by njbriggs** [comment]
Build: https://builds.cask.co/browse/CDAP-UDUT844

**Comment by yukiej** [comment]
Could you add some info about the main upgrade related changes you made, for posterity?

**Comment by njbriggs** [comment]
@yukiej Sure! The changes are:
* Move the Pipeline configuration and customization modal from a custom modal to the material-ui Popover. This was to fix an issue with click event propagation in the original code.
* Some type issues in SchemaEditor had to be cleaned up.
* Some small TypeScript declaration changes.
* Plugin JSON Creator integration tests ran into a scrolling/element visibility issue and wouldn't complete. I changed the order the elements were clicked in to work around it.

**Review by yukiej — APPROVED** [review]
lgtm!

**Comment by njbriggs** [comment]
I spoke to @leacd and she prefers that we switch all the popovers to material-ui to get the animation. I've filed a bug (https://issues.cask.co/browse/CDAP-17329) to switch over the pipeline configuration popovers. That will not be in this PR.

**Pull request merged**
