### PR TITLE
[CDAP-20661] Reverting default version of dataproc to 2.0

### PR DESCRIPTION
**Pull request by iam-divya**

### CODE REVIEW

**Comment by samdgupi** [comment]
Can you please add description and link to the jira ticket.

**Comment by iam-divya** [comment]
https://github.com/cdapio/cdap/pull/15089/files

**Comment by iam-divya** [comment]
> Can you please add description and link to the jira ticket.

Done

**Review by samdgupi — COMMENTED** [review]
LGTM

**Review by samdgupi — APPROVED** [review]

**Pull request merged**
