### PR TITLE
Remove the existence check for dataset while computing lineage.

### PR DESCRIPTION
**Pull request by sagarkapare**
JIRA https://issues.cask.co/browse/CDAP-7204

### CODE REVIEW

**Comment by sagarkapare** [comment]
https://builds.cask.co/browse/CDAP-DUT4745-1

**Comment by sagarkapare** [comment]
Build is running here - https://builds.cask.co/browse/CDAP-DUT4760-1

**Comment by poornachandra** [comment]
LGTM

**Comment by sagarkapare** [comment]
Build is green. Merging.

**Pull request merged**
