### PR TITLE
(CDAP-387) Adding SparkSQL to table based Datasets

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Build https://builds.cask.co/browse/CDAP-DUT6028

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
build passed https://builds.cask.co/browse/CDAP-DUT6028-4

**Comment by chtyim** [comment]
squashed and merging.

**Pull request merged**
