### PR TITLE
[CDAP- 5976] - Adds ds-multiplevalues widget to plugin widget json docs

### PR DESCRIPTION
**Pull request by ajainarayanan**
Quick Build: http://builds.cask.co/browse/CDAP-DQB11-1/artifact

### CODE REVIEW

**Comment by elfenheart** [comment]
👍  LGTM

**Comment by awholegunch** [comment]
I've made major edits to the docs: please check and let me know if that looks good. Once they look good, let's re-run Quick Build...

**Comment by ajainarayanan** [comment]
👍 on @awholegunch changes.

**Comment by awholegunch** [comment]
Re-running as [Quick Build 2](http://builds.cask.co/browse/CDAP-DQB11-2). LGTM2.

[The Page](http://builds.cask.co/artifact/CDAP-DQB11/shared/build-2/Docs-HTML/3.5.0-SNAPSHOT/en/cdap-apps/hydrator/custom.html#plugin-widget-json)

**Pull request merged**
