### PR TITLE
(CDAP-15606) Implement GraphQL layer with Apollo Server to fetch data for the pipeline list view

### PR DESCRIPTION
**Pull request by miguelvelezmj25**

### CODE REVIEW

**Comment by miguelvelezmj25** [comment]
This PR is a clean version of 

https://github.com/cdapio/cdap/pull/11462

The original discussion and review can be accessed in  PR 11462. That branch had several merge conflicts when attempting to squash the commits.

**Comment by miguelvelezmj25** [comment]
JIRA: https://issues.cask.co/browse/CDAP-15606

**Comment by miguelvelezmj25** [comment]
This PR is a clean version of 

https://github.com/cdapio/cdap/pull/11463

The original discussion and review can be accessed in #11463. That branch had several merge conflicts when attempting to squash the commits. Hence, this PR has all of the changes from #11463.

**Comment by miguelvelezmj25** [comment]
Build: https://builds.cask.co/browse/CDAP-UDUT352

**Review by elfenheart — APPROVED** [review]
👍 LGTM

**Pull request merged**
