### PR TITLE
Bump twill version to 0.9.0-SNAPSHOT and apply changes

### PR DESCRIPTION
**Pull request by yaojiefeng**
This is needed for log level change at runtime for cdap. 
Removed `AbstractTwillController` since [Twill-177](https://issues.apache.org/jira/browse/TWILL-177) is fixed.

### CODE REVIEW

**Comment by anwar6953** [comment]
Can you verify that the `AbstractTwillController` class in twill repo has all the changes that were in the cdap repo?

**Comment by yaojiefeng** [comment]
@anwar6953 Yes. It has the changes in cdap with some refactor, I think the changes is in https://github.com/apache/twill/pull/8

**Comment by yaojiefeng** [comment]
Build is running: http://builds.cask.co/browse/CDAP-RUT323-1

**Comment by chtyim** [comment]
LGTM

**Pull request merged**
