### PR TITLE
Bugfix release/ui widget styling fixes

### PR DESCRIPTION
**Pull request by elfenheart**

### CODE REVIEW

**Comment by bdmogal** [comment]
@elfenheart in outer joins, the checkbox and label seem to not be aligned
image

**Comment by bdmogal** [comment]
@elfenheart in the join condition, can the widget occupy more horizontal space?
image

**Comment by bdmogal** [comment]
@elfenheart Redshift to S3 icon seems not proper
image

**Review by bdmogal — COMMENTED** [review]
@elfenheart 3 comments.

**Review by ajainarayanan — APPROVED** [review]
👍 Code LGTM

**Comment by bdmogal** [comment]
@elfenheart I'm not able to see the s3toRedshift and vice versa icons. Tried chrome, safari, firefox. Not sure if something is wrong with my environment.Other than that, LGTM

**Comment by bdmogal** [comment]
If this problem is only with my environment, I'd say let's merge this, I'll verify again on a freshly created SDK.

**Pull request merged**
