### PR TITLE
[CDAP-8952] - Fix Log Fast action looks initially enabled, but then gets disabled on hover

### PR DESCRIPTION
**Pull request by ajainarayanan**
Same PR created against release/4.1 - https://github.com/caskdata/cdap/pull/8343

### CODE REVIEW

**Comment by tonybach** [comment]
LGTM 👍

**Comment by leacd** [comment]
I don't think there is enough visual distinction between Log available and not available. 
Option 1) we can use different icons to signify the two states: No logs http://fontawesome.io/icon/file-o/ - in gray
Logs available: http://fontawesome.io/icon/file-text-o/ in #333
Option 2) change color of no logs icons to a lighter gray.

**Comment by ajainarayanan** [comment]
Talked to @leacd and we agreed upon using slightly different icons for enabled and disabled logs.

Based on the changes this is how it looks,
screen shot 2017-03-28 at 1 15 12 pm

**Comment by tonybach** [comment]
New code changes LGTM 👍

**Comment by leacd** [comment]
LGTM

**Pull request merged**
