### PR TITLE
Fixing CDAP-7407

### PR DESCRIPTION
**Pull request by abhinavbansal246**
https://issues.cask.co/browse/CDAP-7047

### CODE REVIEW

**Comment by anwar6953** [comment]
Create a bamboo build branch for this PR, using this build (since its against release/3.5):
builds.cask.co/browse/CDAP-RUT

**Comment by abhinavbansal246** [comment]
this PR fixes the issue of redeploying the snapshot application on a secure cluster

**Comment by bdmogal** [comment]
👍  to the code, as long as it is tested on a cluster. However, 👎 to the commit message :). Please include sufficient details about the fix in the commit message.

**Comment by abhinavbansal246** [comment]
Build is running here - http://builds.cask.co/browse/CDAP-RUT64-2

**Comment by bdmogal** [comment]
This is pending testing on a cluster.

**Comment by abhinavbansal246** [comment]
Tested the changes on the cluster, The change works

**Pull request merged**
