### PR TITLE
CDAP-5901 fix reading from stream in Hydrator

### PR DESCRIPTION
**Pull request by albertshau**
Correctly pass start, end, and format.

### CODE REVIEW

**Comment by CuriousVini** [comment]
LGTM

**Comment by albertshau** [comment]
http://builds.cask.co/browse/CDAP-DUT4109

**Comment by gokulavasan** [comment]
LGTM 👍 Wondering if we lack unit tests that might have caught this?

**Comment by anwar6953** [comment]
integration tests would've been nice too, I suppose. stream as source in MR should be done, imo

**Comment by chtyim** [comment]
Is it just affecting MR but not Spark?

**Comment by albertshau** [comment]
Just in MR.  There are integration tests but they are ignored right now.  There are also unit tests in hydrator-plugins that would have started failing once the snapshot artifacts were published to maven.

**Pull request merged**
