### PR TITLE
[CDAP-17492] Removes schema property while calling validation API (Validate & Get Schema buttons) for individual plugins

### PR DESCRIPTION
**Pull request by ajainarayanan**
JIRA - https://cdap.atlassian.net/browse/CDAP-17492

### CODE REVIEW

**Comment by elfenheart** [comment]
have this been tested for plugins where schema property is required, such as javascript or wrangler plugin? I believe this change will make that validation fail

**Comment by ajainarayanan** [comment]
> have this been tested for plugins where schema property is required, such as javascript or wrangler plugin? I believe this change will make that validation fail

Yes, that is correct. The changes are not ready for review. Still working on it. This will most likely not happen in UI. This is something that we need to change per-plugin. Will update PR sometime this week.

**Comment by ajainarayanan** [comment]
@elfenheart Have updated PR to remove the schema only while getting schema. This should be safe (with plugins we ship) since a plugin cannot have schema as required property, validate output schema and still be able to generate new schema.

**Review by elfenheart — APPROVED** [review]

**Pull request merged**
