### PR TITLE
[CDAP-9094][CDAP-9096] Populates macros with resolved preferences, in pipeline and preview

### PR DESCRIPTION
**Pull request by tonybach**
Cherry-pick from #8677.

### CODE REVIEW

**Comment by elfenheart** [comment]
👍  LGTM

**Comment by leacd** [comment]
Changes in the preferences are not reflected in the runtime arguments unless the user opens and closes the stage config modal.

**Comment by leacd** [comment]
LGTM

**Comment by tonybach** [comment]
Green build: https://builds.cask.co/browse/CDAP-DRC6434-3

**Pull request merged**
