### PR TITLE
(CDAP-7128) Fix changing number of Worker instances

### PR DESCRIPTION
**Pull request by chtyim**
- Also cleanup the ServiceTwillProgramController

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm

**Comment by poornachandra** [comment]
LGTM

**Comment by chtyim** [comment]
Verified on the cluster. Both Worker and Service increase/decrease instances are working.

**Comment by chtyim** [comment]
It only change logic on distributed runtime and program controller without any guice changes. Verified functionality on cluster, hence merging.

**Pull request merged**
