### PR TITLE
[CDAP-15534] Fix log saver status endpoint

### PR DESCRIPTION
**Pull request by CuriousVini**

### CODE REVIEW

**Comment by chtyim** [comment]
Why merge to release/6.0? New changes should be merge to develop and cherry pick to release/6.0 if needed.

**Comment by CuriousVini** [comment]
Since this is a bugfix, adding it to release/6.0. Will merge release to develop in a separate PR to keep develop upto date.

**Review by chtyim — APPROVED** [review]

**Comment by CuriousVini** [comment]
build: https://builds.cask.co/browse/CDAP-RUT1683-1

**Comment by CuriousVini** [comment]
build is green. merging.

**Pull request merged**
