### PR TITLE
Add colon to accepted chars for dataset id

### PR DESCRIPTION
**Pull request by mrahanjam**
This PR adds colon to the accepted chars for dataset id

JIRA: [CDAP-19519](https://cdap.atlassian.net/browse/CDAP-19519)

### CODE REVIEW

**Review by sumengwang — APPROVED** [review]

**Review by de-lan — APPROVED** [review]

**Review by albertshau — COMMENTED** [review]
why do we want to make this change? 

I'm concerned that somewhere in the code we've made some assumption about dataset id characters that will now break in some hard to find way, like if we've used ':' as a delimiter between datasetid and some other value somewhere.

**Comment by yaojiefeng** [comment]
Are we using colon as a separator for fqn? For gcp resources it is something like "projects/{project}/...", will the DC integration replace colon with expected character? How will it know when to replace it?

**Comment by avirmani** [comment]
> 

is there a way to find out if thats the case anywhere?

**Comment by mrahanjam** [comment]
> Are we using colon as a separator for fqn? For gcp resources it is something like "projects/{project}/...", will the DC integration replace colon with expected character? How will it know when to replace it?

They start with pluginName followed by `":"`. For example GCS is `gs://{bucket name}{path}` and BQ is `bigquery:myProject.myDataset.myTable`.

**Comment by albertshau** [comment]
is it possible to add a new field for FQN rather than use the dataset id? This would be safer, but I'm not sure if it would allow us to meet all the requirements for this project.

**Comment by mrahanjam** [comment]
> is it possible to add a new field for FQN rather than use the dataset id? This would be safer, but I'm not sure if it would allow us to meet all the requirements for this project.

@snehalakshmisha do you think we can do this?

**Pull request closed without merging**
