### PR TITLE
add label to ProvisionerDetail

### PR DESCRIPTION
**Pull request by yaojiefeng**
https://builds.cask.co/browse/CDAP-DUT6417-1

### CODE REVIEW

**Review by nitinmotgi — COMMENTED** [review]
Is there a icon also returned in the call. It should have a icon too for the provisioner.

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by albertshau** [comment]
there was no design for an icon, but we can do something where we scan the extension directory for an icon and have a separate endpoint to get it. An image should not be returned in this rest call. @yaojiefeng can you open a jira for this.

**Comment by bdmogal** [comment]
@albertshau should we add it to the widget spec json, the same formats that are supported for plugin icons?

**Comment by albertshau** [comment]
hm that's a good point, we could put it there

**Comment by yaojiefeng** [comment]
Created https://issues.cask.co/browse/CDAP-13376 to track the icon support

**Pull request merged**
