### PR TITLE
Make sure URLs are encoded

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Build already passed: http://builds.cask.co/browse/CDAP-DUT4155-1

**Comment by wolf31o2** [comment]
👍 LGTM

**Comment by gokulavasan** [comment]
@chtyim Would it be possible to add some more info about the change? Thanks!

**Comment by chtyim** [comment]
@gokulavasan I updated the commit message to include the JIRA that can gives more detail (the JIRA itself can't be resolved yet as the change in here is just to fix unit-test).

**Comment by gokulavasan** [comment]
LGTM 👍

**Pull request merged**
