### PR TITLE
Bug fixes in UI - 3

### PR DESCRIPTION
**Pull request by ajainarayanan**
[CDAP-8482](https://issues.cask.co/browse/CDAP-8482) - Fixes JustAdded section to update if recently created entities are deleted.

[CDAP-8422](https://issues.cask.co/browse/CDAP-8422) - Fixes cdap logo in cdap dropdown

[CDAP-8460](https://issues.cask.co/browse/CDAP-8460) - Fixes clicking on cask logo to go to cdap home.

### Note: Need to add reference to more JIRAs.

Bamboo build: http://builds.cask.co/browse/CDAP-DRC5718-2

### CODE REVIEW

**Comment by tonybach** [comment]
For CDAP-8482, you've added code to emit delete events, but you haven't added the code to actually listen to those right?

The code for the other two JIRAs looks good to me.

**Comment by ajainarayanan** [comment]
@tonybach https://github.com/caskdata/cdap/pull/7985/files#diff-65832a5f948bd74f26fd65e66668edb6R46

**Comment by tonybach** [comment]
@ajai Ah somehow I missed that. LGTM 👍

**Comment by elfenheart** [comment]
Code 👍 LGTM

**Pull request merged**
