### PR TITLE
[CDAP-1696] [CDAP-5897] Change default CDAP UI/Router ports

### PR DESCRIPTION
**Pull request by wolf31o2**
CDAP router's default port `10000` conflicts with HiveServer2. CDAP UI's default port `9999` conflicts with Cloudera Manager's Activity Monitor and Accumulo's Master. We have already changed these in `caskdata/cm_csd` and `caskdata/cdap-ambari-service` due to these conflicts. This will bring the SDK, packages, and documentation in line with those ports.

| Service | Old port | New port |
| --- | --- | --- |
| UI | 9999 | 11011 |
| Router | 10000 | 11015 |

I used the following to find the files to edit:
10000:

```
grep -R 10000 * | grep -v 100000 | grep -v 10000L | grep -v Binary | cut -d: -f1 | sort -u
```

9999:

```
grep -R 9999 * | grep -v 99999 | cut -d: -f1 | sort -u
```

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
Don't merge this to develop yet. We want to branch off 3.6 and develop will be open for 4.0 after. We can merge this to 4.0

**Comment by awholegunch** [comment]
LGTM. Only problem will be that the doc build will break because of the change to `cdap-default.xml`, but easier to fix after the fact.

**Comment by wolf31o2** [comment]
I thought that I had fixed that. Maybe I forgot to push. I'll check it before we take it off hold.

**Comment by sreevatsanraman** [comment]
Closing this PR. Please reopen when develop is open for 4.0

**Pull request closed without merging**
