### PR TITLE
CDAP-5730 CDAP-11497 fix for now allowing . for dataset/type/module name

### PR DESCRIPTION
**Pull request by yaojiefeng**
JIRA: https://issues.cask.co/browse/CDAP-5730
https://issues.cask.co/browse/CDAP-11497
Build: https://builds.cask.co/browse/CDAP-RUT1000-1
Fix the fromString method for not allowing . in dataset/type/module names

### CODE REVIEW

**Comment by gokulavasan** [comment]
LGTM 👍

**Comment by anwar6953** [comment]
Is Dataset the only Id that can have `.` in it?

**Comment by yaojiefeng** [comment]
@anwar6953 from https://issues.cask.co/browse/CDAP-5730, the comment mentioned "Dataset instance/type/module names can have '.' in them since we want to allow class names". Is that still true now?

**Comment by yaojiefeng** [comment]
@anwar6953 confirmed that we can have `.` in dataset type/module.

**Comment by yaojiefeng** [comment]
Build passed, merging

**Pull request merged**
