### PR TITLE
(CDAP-8565 Release 3.5) Improve master stop experience

### PR DESCRIPTION
**Pull request by chtyim**
This is basically cherry-picking from release/4.1 and the PR #8106 for release/3.5 branch

### CODE REVIEW

**Review by wolf31o2 — APPROVED** [review]
Shell LGTM

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Building: http://builds.cask.co/browse/CDAP-RUT659-5

**Comment by chtyim** [comment]
Build passed. Merging.

**Pull request merged**
