### PR TITLE
new loading icon for the SVG and changing text on publish pipeline

### PR DESCRIPTION
**Pull request by rohitcmu**
https://issues.cask.co/browse/CDAP-9001

### CODE REVIEW

**Comment by ajainarayanan** [comment]
👍 LGTM

**Comment by leacd** [comment]
I think we should change the label of the call to action from "Publish" to "Deploy" to match the loading message.
image

**Comment by ajainarayanan** [comment]
@rohitcmu One thing I am noticing is when we hit ESC key while we show loading animation it seems to remove it but the background action is still happening 
loadinganimation


@rohitcmu This seems to be happening in the existing release/4.1 but since we are working on loading animation can we fix this? This should be a simple modal property that we need to set.

**Comment by leacd** [comment]
LGTM

**Pull request merged**
