### PR TITLE
Add X-Requested-With header to all xhr requests made from UI

### PR DESCRIPTION
**Pull request by ajainarayanan**
Build: https://builds.cask.co/browse/CDAP-URUT244-1

### CODE REVIEW

**Review by elfenheart — APPROVED** [review]
👍 LGTM

**Review by elfenheart — APPROVED** [review]
👍 LGTM

**Review by elfenheart — APPROVED** [review]
👍 LGTM

**Comment by ajainarayanan** [comment]
Green build: https://builds.cask.co/browse/CDAP-URUT244-6

**Pull request merged**
