### PR TITLE
(cdap 6699) Made the Secure Store programmatic APIs consistent with the REST APIs

### PR DESCRIPTION
**Pull request by Nishith**

### CODE REVIEW

**Comment by anwar6953** [comment]
also resolves https://issues.cask.co/browse/CDAP-6936?

Edit: nvm; doesn't seem so.

**Comment by Nishith** [comment]
No, that will come with the PR for https://issues.cask.co/browse/CDAP-6797

**Comment by Nishith** [comment]
I need to merge my 2 open PRs before I can start to work on that. Already too many merge conflicts.

**Comment by anwar6953** [comment]
Users will not want to persist non-string values?

**Comment by Nishith** [comment]
Not in this release. We can decide to change if people actually ask for it.

**Comment by anwar6953** [comment]
lgtm

**Pull request merged**
