### PR TITLE
CDAP-17750: Performance improvements to Hierarchy widget

### PR DESCRIPTION
**Pull request by arbenhaziri**
JIRA: https://cdap.atlassian.net/browse/CDAP-17750

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@arbenhaziri Thanks for the pull request. It works perfect! 💯 

One thing I am noticing is double scroll bar within the autocomplete list. If for that 👍  the changes LGTM


https://user-images.githubusercontent.com/1452845/114973204-d7be6800-9e34-11eb-9132-770b59ecf583.mov

**Comment by arbenhaziri** [comment]
> @arbenhaziri Thanks for the pull request. It works perfect! 
> 
> One thing I am noticing is double scroll bar within the autocomplete list. If for that  the changes LGTM
> 
>  AutoComplete-scroll.mov

-The PR its rebased on top of the latest develop branch.
-Double scroll bar in autocomplete its fixed.

**Comment by rmstar** [comment]
Test is failing with error:
```
Error:  Failed to execute goal org.apache.rat:apache-rat-plugin:0.10:check (rat-check) on project cdap-ui: Too many files with unapproved license: 1 See RAT report in: /tmp/cdap/cdap/cdap-ui/target/rat.txt -> [Help 1]
```
Please add license in new files and squash commits.

**Comment by arbenhaziri** [comment]
> Test is failing with error:
> 
> ```
> Error:  Failed to execute goal org.apache.rat:apache-rat-plugin:0.10:check (rat-check) on project cdap-ui: Too many files with unapproved license: 1 See RAT report in: /tmp/cdap/cdap/cdap-ui/target/rat.txt -> [Help 1]
> ```
> 
> Please add license in new files and squash commits.

**Comment by arbenhaziri** [comment]
> Test is failing with error:
> 
> ```
> Error:  Failed to execute goal org.apache.rat:apache-rat-plugin:0.10:check (rat-check) on project cdap-ui: Too many files with unapproved license: 1 See RAT report in: /tmp/cdap/cdap/cdap-ui/target/rat.txt -> [Help 1]
> ```
> 
> Please add license in new files and squash commits.

@rmstar @ajainarayanan  Commits are squashed and license is added in the new file.

**Review by ajainarayanan — APPROVED** [review]

**Pull request merged**
