### PR TITLE
Exclude the IntelliJ generated iml files from rat checker validation.

### PR DESCRIPTION
**Pull request by Nishith**
These files cause the build to fail.

### CODE REVIEW

**Comment by rohitsinha54** [comment]
How and when will they make build to fail ?

**Comment by bdmogal** [comment]
LGTM, as long as `mvn clean package -DskipTests` passes locally, with some random `*.iml` files.

**Comment by chtyim** [comment]
Why need this??

**Comment by chtyim** [comment]
It is by default excluded, shouldn't need this change.

http://creadur.apache.org/rat/apache-rat-plugin/check-mojo.html#useIdeaDefaultExcludes

**Comment by anwar6953** [comment]
If you run into this issue, try a git clean and then a rebuild.

**Comment by chtyim** [comment]
Verified that we don't need this change. Please close this PR.

**Comment by Nishith** [comment]
The problem happened when I selected "Search for projects recursively" while importing it into Intellij. With that option turned on a lot more iml files are generated. These new files are not skipped by rat checker. 

The first module to fail is cdap-data-pipeline-plugins-archetype with the following error

`Failed to execute goal org.apache.rat:apache-rat-plugin:0.10:check (rat-check) on project cdap-data-pipeline-plugins-archetype: Too many files with unapproved license: 1 See RAT report in: /Users/Nishith/src/cdap-test/cdap/cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/target/rat.txt
`
Looking into the rat file mentioned, this was the issue.

```
Unapproved licenses:

  /Users/Nishith/src/cdap-test/cdap/cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/archetype-resources (1).iml
```

I removed that iml and continued the build which failed again for the next module

`[INFO] CDAP Data Pipeline Batch Plugins Archetype ......... SUCCESS [  9.409 s]
[INFO] CDAP ETL Realtime Source Archetype ................. FAILURE [  0.382 s]
[INFO] CDAP ETL Realtime Sink Archetype ................... SKIPPED
[INFO] CDAP ETL Batch Source Archetype .................... SKIPPED
[INFO] CDAP ETL Batch Sink Archetype ...................... SKIPPED
[INFO] CDAP ETL Transform Archetype ....................... SKIPPED
[INFO] CDAP ETL Realtime App .............................. SKIPPED
[INFO] CDAP ETL Tools ..................................... SKIPPED
[INFO] CDAP Data Quality Artifact ......................... SKIPPED
[INFO] CDAP Kafka Server .................................. SKIPPED
[INFO] CDAP CLI ........................................... SKIPPED
[INFO] CDAP Gateway ....................................... SKIPPED
[INFO] CDAP UI ............................................ SKIPPED
[INFO] CDAP Standalone .................................... SKIPPED
[INFO] CDAP Java Client Tests ............................. SKIPPED
[INFO] CDAP CLI Tests ..................................... SKIPPED
[INFO] CDAP Integration Test Framework .................... SKIPPED`

With a similar error pointing to another iml file 

`[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.10:check (rat-check) on project cdap-etl-realtime-source-archetype: Too many files with unapproved license: 1 See RAT report in: /Users/Nishith/src/cdap-test/cdap/cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/target/rat.txt

Unapproved licenses:

  /Users/Nishith/src/cdap-test/cdap/cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/archetype-resources (5).iml`

This happens for most of the modules mentioned above.

An easy way to not have this problem is to not select the  "Search for projects recursively" option while importing. In that case we should clearly note that in the documentation.

**Pull request closed without merging**
