### PR TITLE
Bump to 3.6.1 snapshot

### PR DESCRIPTION
**Pull request by anwar6953**

### CODE REVIEW

**Comment by anwar6953** [comment]
I'm not sure about the occurrence in these two files. Should they be left at 3.6.0, or be bumped to 3.6.1 in advance?

cdap-sdk-ubuntu12-with-uri.json
hdinsight/install.sh

@dereklwood , @wolf31o2 ?

**Comment by gokulavasan** [comment]
Changes look good. Merge after you get clarification on your question about cdap-sdk-ubuntu12-with-uri.json, hdinsight/install.sh. Thanks @anwar6953 !

**Comment by awholegunch** [comment]
DON'T MERGE THIS

**Comment by wolf31o2** [comment]
@anwar6953 `cdap-sdk-ubuntu12-with-uri.json` should always be ahead of current release because we list the checksums in the cookbook for the SDK versions, which will cause Chef to abort when it hits an invalid checksum (built SDK, versus release) in the file, so update it... the `hdinsight/install.sh` must match a valid CDAP release version, so leave it alone

**Comment by anwar6953** [comment]
Thanks for the explanation

**Comment by anwar6953** [comment]
Updated.
LGTY, @wolf31o2 ?

**Review by wolf31o2 — APPROVED** [review]
👍 LGTM

**Comment by anwar6953** [comment]
`mvn clean package -DskipTests` passed locally

**Pull request merged**
