### PR TITLE
[CDAP-14593] Remove examples that use flows and streams

### PR DESCRIPTION
**Pull request by anew**
Title says all.

### CODE REVIEW

**Review by chtyim — APPROVED** [review]

**Comment by anew** [comment]
Thanks, @chtyim, however, this will break the docs build and I need to remove them from docs, too.

**Comment by anew** [comment]
@chtyim I fixed the doc build, removed all references I could find. Please take another look. Thanks

**Review by chtyim — APPROVED** [review]
LGTM

**Comment by anwar6953** [comment]
@anew I wasn't able to find CDAP-14953 in Jira. Can you check to see if that's the correct Jira number?

**Comment by anew** [comment]
Good catch, @anwar6953. The jira number is a typo. It is really https://issues.cask.co/browse/CDAP-14593. The branch had it correctly, the message did not. How would you fix this now?

**Comment by anwar6953** [comment]
I went ahead and edited the PR title.
I think its not worth it to change it in the commit message, since that would require a force push. Or a revert + reapplying the commit.

**Comment by anew** [comment]
agreed. Thanks for fixing.

**Pull request merged**
