### PR TITLE
[CDAP-6132] - Reset metrics on the DAG on every new run. 

### PR DESCRIPTION
**Pull request by ajainarayanan**

### CODE REVIEW

**Comment by anwar6953** [comment]
Wouldn't the metrics return 0 from the backend as soon as the frontend starts querying for the new run?

**Comment by ajainarayanan** [comment]
@anwar6953 No. Actually the backend doesn't emit the metrics. So until we get metrics we used to show the one for the previous run.

**Comment by elfenheart** [comment]
👍  LGTM

**Comment by anwar6953** [comment]
There's some logic to show the previous run's metrics "until we get metrics".
Can't we simply remove the logic that does that? Instead of manually resetting the metrics?

**Comment by ajainarayanan** [comment]
@anwar6953 Right now there is no explicit logic that shows previous run's metrics until we get the current run. The way we do it today is we get the list of metrics for a run and populate the DAG with appropriate metrics. If the run id changes we are not resetting the metrics so the metrics from the previous run still stays in the DAG. Only when the backend starts emitting new metrics we update the metrics. Until the backend starts to emit any metrics for each node we used to show the metrics from previous run. 

So now what we have done is, as soon as a new run starts we reset the metrics and as backend emits metrics for the new run we update the metrics in the DAG.

**Comment by anwar6953** [comment]
LGTM

**Comment by elfenheart** [comment]
demoed to @bdmogal

**Pull request merged**
