### PR TITLE
[CDAP-17368] Upgrade Jest and replace React Testing Library

### PR DESCRIPTION
**Pull request by elfenheart**
JIRA: https://issues.cask.co/browse/CDAP-17368
Build: https://builds.cask.co/browse/CDAP-UDUT853

Also upgrading Typescript to v4.
Have added a sample test for `<If>` component to use @testing-library/react

### CODE REVIEW

**Review by njbriggs — APPROVED** [review]
LGTM.

How do you see this being used for CI? Would it be run with the unit tests?

**Comment by elfenheart** [comment]
@njbriggs Our build plan will run these tests, there's practically no distinction between the unit tests and integration test.

build plan: https://builds.cask.co/browse/CDAP-UDUT

**Review by ajainarayanan — APPROVED** [review]

**Pull request merged**
