### PR TITLE
[CDAP-12586] - Fixes global dataset specific explore views to show right explore query when datasets reside in external database

### PR DESCRIPTION
**Pull request by ajainarayanan**
#### Issue: 
 - We had two different implementations for generating explore query (determining database name and table name) in old and new UI. This PR fixes this issue in the old UI.

#### Fix:
- This is basically fixing explore in old UI to follow the logic mentioned in this PR https://github.com/caskdata/cdap/pull/7957. 

Corresponding changes in the old UI: https://github.com/caskdata/cdap/commit/0a8d95266d16cc02bc011d1022906e209b3c5457, https://github.com/caskdata/cdap/commit/f5cbf5d4d94e21ad5e60a2d72263b767e4889fdd

### CODE REVIEW

**Comment by tonybach** [comment]
Left minor comments on the old UI commit. Also, maybe update the license years in the files that you changed in the old UI branch?

**Comment by ajainarayanan** [comment]
@tonybach  Added changes to fix the issue: https://github.com/caskdata/cdap/commit/f5cbf5d4d94e21ad5e60a2d72263b767e4889fdd

**Comment by tonybach** [comment]
Code LGTM 👍

**Comment by ajainarayanan** [comment]
Verified against a valid cluster. Talked to @bdmogal . Merging.
screen shot 2017-09-19 at 7 19 27 pm

**Pull request merged**
