### PR TITLE
Add a select/deselect all for Pipeline runtime arguments Provided section + some refactoring

### PR DESCRIPTION
**Pull request by tonybach**
JIRA: https://issues.cask.co/browse/CDAP-12176

This PR adds a little dropdown menu next to the Provided label, which allows user to select/deselect all the Provided checkboxes.

Also before we had two very similar directives, `my-batch-pipeline-config` & `my-realtime-pipeline-config`, with the difference being some html and some controller variables. Have refactored to combine this two to just `my-pipeline-config`.

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@tonybach I wouldn't advice combining both the pipeline configs into one directive. They were specifically made as two different directives so that changing one doesn't affect the other meaning changing a setting for a batch pipeline shouldn't affect the real time pipelines. The differences, as I see, are not small. Not sure why we decided to combine but this would be a problem when we want things to be different while configuring pipelines of different types.

**Comment by tonybach** [comment]
@ajainarayanan I decided to combine the two since I didn't want to keep adding the same functionality in both the controllers for batch and realtime pipelines. If you think it's risky then I can revert this change, and extract out common functions into a service.

**Comment by tonybach** [comment]
Talked with @ajainarayanan about this. We decided to still keep the two configs as separate directives, as even though right now the two have similar structure, there might be a point in the future where we would add a big change to one config but not the other.

Will revert the changes where I combined the directives, and only keep the changes and fixes related to the JIRA. However, the two configs do share some similar components, such as runtime arguments, custom engine config properties, and some resources. We can probably extract these out in a future PR.

**Comment by tonybach** [comment]
Reverted the changes. Because of the initial refactoring and the later revert, it might be easier to review by looking at all the changes in the PR (by clicking on Files Changed), instead of looking at the commits individually.

**Review by ajainarayanan — COMMENTED** [review]
👍 Code LGTM

**Review by bdmogal — APPROVED** [review]

**Pull request merged**
