### PR TITLE
[CDAP-8977] Change appearance of field headers

### PR DESCRIPTION
**Pull request by rohitcmu**
Fix appearance of headers for https://issues.cask.co/browse/CDAP-8977

### CODE REVIEW

**Comment by leacd** [comment]
Sections headers: please reduce the size of the font to 12px and change color to hex #999
image

**Comment by leacd** [comment]
LGTM

**Comment by bdmogal** [comment]
Hey @rohitcmu, can you please put this PR on hold? Nitin had a look at these changes, and thinks the headers should be even more prominent. I will chat with you on Monday about it.

**Comment by ajainarayanan** [comment]
screen shot 2017-03-24 at 10 39 33 pm

The loading animation is not center aligned to the screen.

**Pull request closed without merging**
