### PR TITLE
(CDAP-12907) Update JVM options for Java 8

### PR DESCRIPTION
**Pull request by chtyim**
- Remove usage of MaxPermSize everywhere
  - Useless in Java 8 but print a warning message on startup
- Use G1GC as the default GC

### CODE REVIEW

**Review by sreevatsanraman — CHANGES_REQUESTED** [review]
Changes look good we should also add the flags that exit jvm on oom. -XX:+ExitOnOutOfMemoryError

**Comment by chtyim** [comment]
The only problem is, the `ExitOnOutOfMemoryError` flag is added after Java 8 update 92. Shall we make that as the minimum Java 8 version we support? Or use the old `-XX:OnOutOfMemoryError="kill -9 %p"`, which kind of assume `kill` command is there?

**Comment by sreevatsanraman** [comment]
Terence in that case, we don't need to add. We can suggest as a recommendation.

**Review by sreevatsanraman — APPROVED** [review]

**Comment by chtyim** [comment]
Build passed https://builds.cask.co/browse/CDAP-DUT6432-8

**Pull request merged**
