### PR TITLE
adds type context to template gallery

### PR DESCRIPTION
**Pull request by astewes**
-  Adds type filter to provide more context in the template gallery modal header - [[HYDRA-160](https://issues.cask.co/browse/HYDRA-160)]

gallery

### CODE REVIEW

**Comment by elfenheart** [comment]
👍  LGTM

**Comment by ajainarayanan** [comment]
screen shot 2016-08-15 at 4 41 52 pm

Two things,
1. Data pipeline (Realtime) ellipsis should extend until the end of the container
2. `No results for` should actually say `No templates for`**`Data pipeline (realtime)`**

**Comment by astewes** [comment]
Bamboo build: http://builds.cask.co/browse/CDAP-DRC4267

**Comment by elfenheart** [comment]
👍  LGTM

**Pull request merged**
