### PR TITLE
[CDAP-14296] Move metadata publishing from OpExecutor to DatasetService

### PR DESCRIPTION
**Pull request by anew**
- Moves the recording of system metadata from the op executor to the dataset service
- This ensures that op executor does not need to instantiate the MetadataStore - which might require creating that dataset and lead to a cyclic call back to OpExecutor to create it
- Refactoring AbstractSystemMetaDataWriter methods into a new interface SystemMetaDataProvider
- OpExecutor (that is, DatasetAdminService) now returns the system metadata to the caller instead of writing it itself. The caller (DatasetInstanceService) records it.
- Similar for removing metadata when a dataset it dropped.
- Consequent changes to test classes.

### CODE REVIEW

**Comment by anew** [comment]
Build passed:  https://builds.cask.co/browse/CDAP-DUT6647

**Comment by anew** [comment]
Tested also on cluster and works fine.

**Review by chtyim — APPROVED** [review]
LGTM

**Comment by anew** [comment]
Build also passed after rebasing on release/5.1: https://builds.cask.co/browse/CDAP-DUT6647. Merging

**Pull request merged**
