### PR TITLE
(CDAP-11836) Remove setting plugin conf into SparkConf

### PR DESCRIPTION
**Pull request by chtyim**
- Also make default SparkConf available in the initialize method.

### CODE REVIEW

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Build https://builds.cask.co/browse/CDAP-RUT1117

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by chtyim** [comment]
Build passed

**Comment by chtyim** [comment]
https://builds.cask.co/browse/CDAP-RUT1117-2

**Pull request merged**
