### PR TITLE
[CDAP-5150] deploy with config command now requires config file

### PR DESCRIPTION
**Pull request by liu-joe**
Build : http://builds.cask.co/browse/CDAP-DUT5253-1

### CODE REVIEW

**Comment by liu-joe** [comment]
http://builds.cask.co/browse/CDAP-DRC5254-10/

**Comment by albertshau** [comment]
why is this needed? the config should not be required.

**Comment by liu-joe** [comment]
The config isn't required, but it will be for this syntax. There is an existing command for when the config isn't specified, and they are conflicting

**Comment by gokulavasan** [comment]
LGTM 👍 fix develop build failure

**Pull request merged**
