### PR TITLE
CDAP-11605 fix bug with JavaSparkMain sparkprogram plugins

### PR DESCRIPTION
**Pull request by albertshau**
Had the class assignable check reversed.

### CODE REVIEW

**Comment by albertshau** [comment]
tested on a local sandbox

**Comment by albertshau** [comment]
https://builds.cask.co/browse/CDAP-RUT1104

**Comment by sreevatsanraman** [comment]
LGTM

**Comment by sreevatsanraman** [comment]
Build passed, merging.

**Pull request merged**
