### PR TITLE
CDAP-7066 Port over restart runnable changes from Twill

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA - https://issues.cask.co/browse/CDAP-7066
Build - http://builds.cask.co/browse/CDAP-DUT4708-1

Port over from https://github.com/caskdata/cdap/pull/6500 for Twill 0.7.0

### CODE REVIEW

**Comment by albertshau** [comment]
is it possible to comment on which parts are patched? For example, how come the 'restartRunnableInstances' list from https://github.com/apache/twill/pull/2/files isn't in this class?

**Comment by poornachandra** [comment]
The patched file details are in https://github.com/poornachandra/twill/pull/1. Twill 0.7.0 already had changes to fix race condition when restarting runnables. Look at the second commit in the referenced PR.

**Comment by albertshau** [comment]
lgtm

**Comment by poornachandra** [comment]
Verified on 3.5 cluster

**Comment by poornachandra** [comment]
Build is green, merging

**Pull request merged**
