### PR TITLE
Version Bump + Merging release/4.3 to develop

### PR DESCRIPTION
**Pull request by chtyim**
Only the last two commits are relevant. One for bumping version to 5.0.0-SNAPSHOT and the other for resolving version conflict in pom.xml and some xml and json files.

### CODE REVIEW

**Comment by anwar6953** [comment]
I think we should bump the following occurrences also to 5.0.0 (instead of 5.0.0-SNAPSHOT):
image

**Comment by chtyim** [comment]
hum.. I am not aware of we have hardcoded version in distributions. Will bump them as well

**Comment by chtyim** [comment]
Build passed; https://builds.cask.co/browse/CDAP-DUT6098

**Comment by anwar6953** [comment]
LGTM

**Pull request merged**
