### PR TITLE
[CDAP-9300] show a warning modal on preview run if pipeline contains action plugins

### PR DESCRIPTION
**Pull request by elfenheart**
JIRA: https://issues.cask.co/browse/CDAP-9300

### CODE REVIEW

**Comment by bdmogal** [comment]
@elfenheart can we disable the Preview tab on action plugins:
image

Also, it doesn't seem to be working when you have post-run actions. Added an email action. Didn't see the warning popup.

**Comment by bdmogal** [comment]
@elfenheart can we close the start/runtime arguments drawer first, then show the modal?
image

**Comment by prinam** [comment]
^ in the above modal, the padding on the left is not the same as right. It should be the same as on the right.

**Comment by elfenheart** [comment]
@prinam the text are not center aligned, so the text cannot have the same padding

**Comment by bdmogal** [comment]
Overall functionality LGTM. 
2 concerns:
1. For action plugins, we seem to have removed the Preview tab. Can we keep, but disable it, and add a tooltip saying "Preview data is not generated for action plugins".
2. The backend does not seem to be fully ignoring post run actions. If you misconfigure a post run action, you get an error like below, which is not nice. Once we have confirmation from @yaojiefeng or @sagarkapare about this, this is good to go.

**Review by ajainarayanan — APPROVED** [review]
👍 Code LGTM

**Comment by ajainarayanan** [comment]
👍 LGTM @bdmogal

**Pull request merged**
