### PR TITLE
CDAP-7185 Remove deprecated method: EntityId#getEntity.

### PR DESCRIPTION
**Pull request by anwar6953**
https://issues.cask.co/browse/CDAP-7185
https://builds.cask.co/browse/CDAP-DUT5723

### CODE REVIEW

**Comment by Nishith** [comment]
Still used here.

https://github.com/caskdata/cdap-security-extn/blob/develop/cdap-sentry/cdap-sentry-extension/cdap-sentry-binding/src/main/java/co/cask/cdap/security/authorization/sentry/binding/AuthBinding.java#L693

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by anwar6953** [comment]
@Nishith updated the external repo:
https://github.com/caskdata/cdap-security-extn/pull/116

**Comment by Nishith** [comment]
Thanks. LGTM.

**Pull request merged**
