### PR TITLE
(CDAP-14591) Remove Stream View code

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Review by anwar6953 — APPROVED** [review]

**Comment by CuriousVini** [comment]
should we also remove: https://github.com/cdapio/cdap/blob/develop/cdap-cli/src/main/java/co/cask/cdap/cli/ElementType.java#L52?

**Comment by chtyim** [comment]
@CuriousVini Removed.

**Review by CuriousVini — APPROVED** [review]
Also from here: https://github.com/cdapio/cdap/blob/develop/cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/EntityIdKeyHelper.java#L157?

Rest of the code changes lgtm 👍

**Comment by chtyim** [comment]
Build passed https://builds.cask.co/browse/CDAP-DUT6699

**Comment by chtyim** [comment]
Squash and merge.

**Pull request merged**
