### PR TITLE
CDAP-1491 Initial layout for security documentation

### PR DESCRIPTION
**Pull request by bdmogal**
Updates for security changes in CDAP 3.5.0.

Running as a Quick Build: http://builds.cask.co/browse/CDAP-DQB62-6

### CODE REVIEW

**Comment by anwar6953** [comment]
Wrong JIRA number in commit message and PR description.

**Comment by bdmogal** [comment]
@anwar6953 fixed

**Comment by bdmogal** [comment]
Removed placeholders and started a new build: http://builds.cask.co/browse/CDAP-DQB62-7. 

@awholegunch please review once again. I would like to merge this, and then create follow-up PRs for adding content for individual sections.

**Comment by awholegunch** [comment]
LGTM

**Comment by bdmogal** [comment]
Build: http://builds.cask.co/browse/CDAP-DQB62-8. Merging. Will follow-up with PRs for more content soon.

**Pull request merged**
