### PR TITLE
(CDAP-5800) speed up app-fabric tests

### PR DESCRIPTION
**Pull request by chtyim**
Reduce / group usage of AppFabricTestBase to reduce overhead in startup/tear down.

### CODE REVIEW

**Comment by anwar6953** [comment]
LGTM

**Comment by anwar6953** [comment]
LGTM

**Comment by chtyim** [comment]
Build passed. Reduced 10 mins build time.

**Comment by chtyim** [comment]
https://builds.cask.co/browse/CDAP-DUT5907-2

**Pull request merged**
