### PR TITLE
CDAP-7881 Avoid counting rows for a different targetType against the offset

### PR DESCRIPTION
**Pull request by anwar6953**
Avoid counting rows for a different targetType against the offset.
Basically, we were counting rows/entries for target types other than the search target type in part of our offset.

So, if our offset was 5, we were skipping the first 5 rows, even if they are for programs (when our query is for apps).

https://issues.cask.co/browse/CDAP-7881

### CODE REVIEW

**Comment by anwar6953** [comment]
The test cases I added fails without the fix in MetadataDataset.

**Comment by anew** [comment]
Nice! LGTM

**Comment by anew** [comment]
This will conflict with @rohitsinha54 's change to filter out hidden entities (that begin with _).

**Comment by anwar6953** [comment]
Whoever's change is simpler should merge first, and the person with the more complex change should resolve conflicts, in my opinion.

**Comment by anew** [comment]
agreed, @anwar6953. I only mentioned it to get @rohitsinha54 's attention.

**Comment by rohitsinha54** [comment]
I will base off from this branch. Merge your changes. Will unblock some ui stuff I guess

**Comment by anwar6953** [comment]
Ran the relevant metadata test cases.
Merging to unblock ui testing.

After the LGTM, I just added this diff (simple comment change):
image

**Comment by bdmogal** [comment]
Great catch @anwar6953 ! 👍

**Pull request merged**
