### PR TITLE
Fix/remove spark1 report

### PR DESCRIPTION
**Pull request by gsps1**
Removing Spark-1 Reporting app.

JIRA https://issues.cask.co/browse/CDAP-13838

Files from spark 2 and report-base are merged into one module and removed spark1 and base modules. 

Relevant pom file changes in the cdap-program-report module, cdap-master and cdap-standalone module for packaging.

Tested building sandbox and testing locally.
Pending testing on cluster.

### CODE REVIEW

**Review by albertshau — APPROVED** [review]
lgtm pending cluster test

**Comment by gsps1** [comment]
build green https://builds.cask.co/browse/CDAP-DUT6646

**Comment by gsps1** [comment]
@albertshau bumped into an UI issue, not sure why, but when enabling reports, there wasn't any action (deploy app) performed. 

So tested it using integration test and that was successful. Can we merge this and debug the UI issue later ?

**Comment by gsps1** [comment]
Its failing due to unrelated issue while listing artifacts, so merging this PR.

**Pull request merged**
