### PR TITLE
fixes modal header styling for plugin function modals

### PR DESCRIPTION
**Pull request by astewes**
-  Adds consistent modal header styling to plugin function modals

headers

Layered modal: adjusted position (laptop):
sm

Layered modal: adjusted position (large display):
lg

### CODE REVIEW

**Comment by ajainarayanan** [comment]
Minor nitpick: 
screen shot 2016-08-17 at 1 55 47 am

Table header font looks weird. Would be nice if we have the consistent bolded header just like we have in output schema.

**Comment by ajainarayanan** [comment]
If for one minor comment 👍 LGTM

**Comment by ajainarayanan** [comment]
Talked to @astewes,
- There are some styling issues in the table (complex schema) that we show in the output schema modal (way too much width for the name and the type and nullable columns are cornered to the right)
- Remove `:` from `Output schema` in the modal.

Otherwise the PR 👍 LGTM

**Comment by elfenheart** [comment]
👍  LGTM

**Comment by astewes** [comment]
Bamboo build: http://builds.cask.co/browse/CDAP-DRC4283

**Pull request merged**
