### PR TITLE
Feature release/cdap 12454 fix config table read

### PR DESCRIPTION
**Pull request by anew**
The issue is that ConfigurationTable uses an HBase client to instantiate an HTable. However, that is not safe inside an HBase coprocessor. Instead, the CoprocessorEnvironment should be used.

ConfigurationTable is used 
- by the master to write to the table: this should use the HBase client
- by the coprocessors to read from the table: this should use the coprocessor env
- by test cases to write and read the table: this should use the HBase client

Thus the fix is to refactor ConfigurationTable into a reader and a writer:
- ConfigurationReader takes a provider that creates the HTable. This class does not depend on HBase server classes. This class is not used directly (only in tests), but serves as a base class. 
- ConfigurationWriter extends ConfigurationReader with a write() method, and it uses a table provider that uses the HBase client. It is used my the master (and by test cases) to write
- CConfigurationReader extends ConfigurationReader and uses a provider that creates the HTable from the coprocessor environment. Obviously it is used inside coprocessors. Because this depends on HBase server classes, it can only be used in coprocessors (and in test cases).

The first commit is only about this refactoring and the ripple effect on other classes and tests. The subsequent commits apply the changes to one HBase compat module each. 

The last commit is an unrelated addition to the build doc.

### CODE REVIEW

**Comment by anew** [comment]
Build is running with identical code, but before I reorganized into multiple commits: https://builds.cask.co/browse/CDAP-RUT1332

**Comment by chtyim** [comment]
Shall we move all the classes that uses `CoprocessorEnvironment` from data-fabric into the compat-base module, as they should only be used inside coprocessor?

**Comment by anew** [comment]
Yes, that was actually the intention. Just a few classes slipped through. Will push another commit.

**Comment by anew** [comment]
I need to do some more refactoring, to move all dependencies on hbase-server to the compat modules.

**Comment by anew** [comment]
ok, I think now there is no more dependency on hbase server classes in data-fabric. removing on-hold, please review again.

**Comment by anew** [comment]
Builds: 
- https://builds.cask.co/browse/CDAP-RUT1332
- https://builds.cask.co/browse/CDAP-ITNTOP-11

@chtyim please take another look at the PR.

**Comment by anew** [comment]
RUT passed, ITN-Top passed on two distros and failed on one with the same two existing tests that were previously failing already. Hence no failures introduced by this change.

**Comment by chtyim** [comment]
LGTM

**Pull request merged**
