### PR TITLE
Bump release/3.5 version to 3.5.4-SNAPSHOT

### PR DESCRIPTION
**Pull request by sagarkapare**

### CODE REVIEW

**Review by wolf31o2 — APPROVED** [review]
👍 on cdap-distributions

**Comment by sagarkapare** [comment]
Thank you @wolf31o2 for the review.
@elfenheart Can you please take a look at cdap-ui changes?
@anwar6953 Please take a look at the rest. Thanks!

**Comment by anwar6953** [comment]
What about the instances of '3.5.3' mainTemplate.json and pkg/install.sh?
@dereklwood @wolf31o2, can you guys input about whether we should bump them or not?

**Comment by dereklwood** [comment]
for HDInsight, go ahead and bump them to 3.5.4 (non-snapshot).  This is because we can't test with snapshots anyway, and so will ease the testing after 3.5.4 is released.

**Comment by anwar6953** [comment]
LGTM

**Pull request merged**
