### PR TITLE
(CDAP-5601) Configurable flowlet batch size

### PR DESCRIPTION
**Pull request by chtyim**
- Added the key() attribute for the @Batch annotation
- Dynamically lookup the batch size from runtime arguments/flowlet properties

### CODE REVIEW

**Comment by chtyim** [comment]
Build passed: http://builds.cask.co/browse/CDAP-RUT85-2

**Comment by sreevatsanraman** [comment]
LGTM. We need a corresponding docs PR.

**Comment by awholegunch** [comment]
Docs LGTM. @chtyim should confirm.

**Comment by chtyim** [comment]
Squashed and merging.

**Pull request merged**
