### PR TITLE
CDAP-13205 Fix inconsistency when the Job is deleted but Trigger still exist in the schedulestore.

### PR DESCRIPTION
**Pull request by sagarkapare**
JIRA: https://issues.cask.co/browse/CDAP-13205

### CODE REVIEW

**Comment by sagarkapare** [comment]
Build is running here - https://builds.cask.co/browse/CDAP-RUT1496-1

**Comment by sagarkapare** [comment]
Fixed test case. New build running here - https://builds.cask.co/browse/CDAP-RUT1496-2

**Comment by chtyim** [comment]
LGTM

**Comment by sagarkapare** [comment]
Build is green here - https://builds.cask.co/browse/CDAP-RUT1496-3. Squashing and merging.

**Pull request merged**
