### PR TITLE
remove testFlowStreamAuth

### PR DESCRIPTION
**Pull request by yaojiefeng**
This is purely testing flow and stream auth so we can remove it in 6.0

### CODE REVIEW

**Review by chtyim — COMMENTED** [review]
There are other tests using the StreamAuthApp, should those be removed as well?

**Review by chtyim — APPROVED** [review]
LGTM

**Comment by yaojiefeng** [comment]
@chtyim removed more tests, please take another look, thank you!

**Comment by yaojiefeng** [comment]
Build: https://builds.cask.co/browse/CDAP-DUT6692-1

**Pull request merged**
