### PR TITLE
(CDAP-11846) Fix Hive on Spark.

### PR DESCRIPTION
**Pull request by chtyim**
- The location of the localized file in the explore container changed to explore.archive.zip file, adjust the jar file filter logic accordingly.

### CODE REVIEW

**Comment by chtyim** [comment]
Verified on CDH 5.11

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by sreevatsanraman** [comment]
Build: https://builds.cask.co/browse/CDAP-RUT1120

**Comment by sreevatsanraman** [comment]
Build passed, merging.

**Pull request merged**
