### PR TITLE
[CDAP-12032, 12045, 12046] Microservice bugfixes

### PR DESCRIPTION
**Pull request by tonybach**
JIRAs: 
- https://issues.cask.co/browse/CDAP-12032
- https://issues.cask.co/browse/CDAP-12045
- https://issues.cask.co/browse/CDAP-12046

### CODE REVIEW

**Comment by elfenheart** [comment]
👍 code LGTM

**Comment by tonybach** [comment]
@bdmogal What it looks like after the latest commit, when the microservice artifact hasn't been loaded yet:

screen shot 2017-07-06 at 11 25 03 am

**Review by elfenheart — APPROVED** [review]
👍 code LGTM

**Comment by tonybach** [comment]
Demoed to @bdmogal and got approval. Squashing and merging.

**Pull request merged**
