### PR TITLE
Bugfix release/merge 401 to 41

### PR DESCRIPTION
**Pull request by CuriousVini**
Conflicts:

- cdap/cdap-ui/old_dist/index.html - kept release/4.1
- cdap-ui/old_dist/assets/bundle/manifest.json - kept release/4.1
- doceker.rst - kept changes from release/4.1
- FileMetadataManager - Merged changes from release/4.1 and 4.0.1
- LogCleanup - Merged changes from release/4.1 and 4.0.1

Build: http://builds.cask.co/browse/CDAP-RUT521-9

### CODE REVIEW

**Comment by bdmogal** [comment]
The diff seems large - @ajainarayanan sure we usually checkin these files?

**Comment by ajainarayanan** [comment]
👍 UI changes LGTM

**Comment by awholegunch** [comment]
Doc changes look fine to me.

**Comment by gsps1** [comment]
lgtm

**Pull request merged**
