### PR TITLE
CDAP-2316 Delete metrics upon stream/dataset deletion.

### PR DESCRIPTION
**Pull request by anwar6953**
Delete metrics upon stream/dataset deletion.
Previously, if you deleted a stream and recreated it, the event count metric was not reset.

https://issues.cask.co/browse/CDAP-2316
http://builds.cask.co/browse/CDAP-DUT4776-1

### CODE REVIEW

**Comment by anwar6953** [comment]
One alternative is to move the dataset instance metric deletion to the dataset op executor service (instead of the dataset instance service).

**Comment by chtyim** [comment]
So the deletion happens in place during app removal? What if the app emitted a lot of metrics, will it take a long time to delete?

**Comment by anwar6953** [comment]
App metrics were already being removed (before this PR) upon app deletion.
I'll look into whether metric deletion takes longer if there's a lot of metrics for the given tags being deleted.

**Comment by anwar6953** [comment]
@chtyim I spoke with @gsps1. Metrics are only deleted from the totals table is deleted (not from the other resolution tables, since they have TTLs). So, performance shouldn't be an issue.

**Comment by chtyim** [comment]
This means if app is removed and added back, then the resolution table will still have those metrics?

**Comment by anwar6953** [comment]
Right. That's a drawback of MetricsStore#delete.

**Comment by anwar6953** [comment]
TODO: Test the performance of dataset/stream/namespace delete now, compared to before.

**Comment by anwar6953** [comment]
Spoke with @chtyim; he suggested that MetricStore should not be accessible from the stream container. It should not know about metrics.
Similar for datasets - DatasetServiceModules should not require a MetricStoreModule binding.

**Comment by anwar6953** [comment]
Closing PR; will reopen once the suggested approach is implemented.

**Pull request closed without merging**
