### PR TITLE
[CDAP-12202] Propagate errors from MapReduce, Spark, Workflow TwillRunnable

### PR DESCRIPTION
**Pull request by ecfm**
https://issues.cask.co/browse/CDAP-12202
https://builds.cask.co/browse/CDAP-DUT5980

### CODE REVIEW

**Comment by anwar6953** [comment]
If a MapReduce fails, will it get retried with this change? (What about Spark,Workflow)?
That was the original point of the code that you removed, right? (To make MapReduce not retry upon failure).

**Comment by ecfm** [comment]
@anwar6953 they will not be retried, since the maximum retry is set to 0 as here for MR https://github.com/caskdata/cdap/pull/9295/files#diff-7d167e3a6abc6f2b86f42353499c9241R96

**Review by anwar6953 — APPROVED** [review]

**Comment by anwar6953** [comment]
LGTM; just make sure to test it on cluster

**Comment by ecfm** [comment]
Verified on cluster and see container exit with error in workflow AM YARN log. Merging

**Pull request merged**
