### PR TITLE
fixes alignment of pipeline name

### PR DESCRIPTION
**Pull request by astewes**
-  Fixes alignment of pipeline name, description in detail view - [[HYDRA-346](https://issues.cask.co/browse/HYDRA-346)]
-  Increases font-size of logview icon - [[CDAP-6867](https://issues.cask.co/browse/CDAP-6867)]

Pipeline name with description:
wdescription

Pipeline name with no description:
wodescription

Logview icon now more legible:
logview

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@astewes line-height seems to be less. characters like 'g,y,l,q' seems to be cut off in the bottom. 
screen shot 2016-08-11 at 4 21 14 pm

**Comment by ajainarayanan** [comment]
@astewes For a nameonly pipeline the name doesn't seem to be aligning with the icons or other elements horizontally.
screen shot 2016-08-11 at 4 23 13 pm

I feel the icons in the buttons have moved up rather than the name moving down.

**Comment by elfenheart** [comment]
👍  LGTM

**Comment by astewes** [comment]
Bamboo build: http://builds.cask.co/browse/CDAP-DRC4243

**Pull request merged**
