### PR TITLE
[CDAP-15552] Visual updates for new columns in ColumnsTab

### PR DESCRIPTION
**Pull request by njbriggs**
Jira: https://cdap.atlassian.net/browse/CDAP-15552

* Add visual styling for new columns (fades after 4 seconds)
image
* Scroll if they're out of view

### CODE REVIEW

**Comment by njbriggs** [comment]
Build: https://builds.cask.co/browse/CDAP-UDUT967

**Review by elfenheart — APPROVED** [review]
👍  LGTM

**Pull request merged**
