### PR TITLE
[CDAP-9117] Condensed logs in logviewer, and adds option to include system logs

### PR DESCRIPTION
**Pull request by tonybach**
Cherry-pick from #8497

### CODE REVIEW

**Comment by tonybach** [comment]
Putting On-hold because the current filter query shows correct user logs for pipelines, but not for programs/applications. The solution will be to have different queries for each case.

**Review by ajainarayanan — APPROVED** [review]
👍 Code LGTM

**Comment by tonybach** [comment]
Corresponding backend JIRA for the `className` -> `loggerName` change: https://issues.cask.co/browse/CDAP-9019

**Review by bdmogal — APPROVED** [review]

**Comment by tonybach** [comment]
Build: https://builds.cask.co/browse/CDAP-DRC6248-7

**Pull request merged**
