### PR TITLE
UI Pipeline Triggers

### PR DESCRIPTION
**Pull request by elfenheart**
__On Hold for Backend Changes__

Backend Feature branch (temporary branch to merge all backend changes): `feature/implement-program-status-based-scheduling`

### Pending:
- Trigger Payload (runtime argument)
- Outbound Trigger pipeline info should include application name and namespace
- Enabled Triggers and Outbound Triggers should be filtered based on running Schedules
- Enable Trigger should be collapsed using 1 API

### CODE REVIEW

**Comment by bdmogal** [comment]
Functionality LGTM

**Comment by elfenheart** [comment]
👍  LGTM on @ajainarayanan changes

**Comment by elfenheart** [comment]
👍  LGTM on @ajainarayanan changes

**Comment by ajainarayanan** [comment]
👍 LGTM on Edwin's changes.

**Pull request merged**
