### PR TITLE
[CDAP-17338] Add integration tests for LogViewer

### PR DESCRIPTION
**Pull request by elfenheart**
JIRA: https://issues.cask.co/browse/CDAP-17338
Build: https://builds.cask.co/browse/CDAP-UDUT848

E2E Test: https://builds.cask.co/browse/IT-UPD2198

### CODE REVIEW

**Review by njbriggs — APPROVED** [review]
Tests LGTM. My only question is about running the pipeline to get the logs - is the file guaranteed to be present in all environments?

**Comment by elfenheart** [comment]
@njbriggs Our integration tests copy over the files to the location. This is the same file being used for FLL tests

**Pull request merged**
