### PR TITLE
Documentation: Tighten spacing between Installation Images

### PR DESCRIPTION
**Pull request by awholegunch**
This is a minor change to tighten the spacing between the images at the top of each of the installation pages.

By doing so, the page can be made smaller without the images wrapping to two lines. A minor improvement, but just helps a bit.

Existing page: [Cloudera Manager Installation](http://docs.cask.co/cdap/develop/en/admin-manual/installation/cloudera.html)

New page: [Cloudera Manager Installation](http://builds.cask.co/artifact/CDAP-DQB20/shared/build-1/Docs-HTML/3.5.0-SNAPSHOT/en/admin-manual/installation/cloudera.html)

Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DQB20-1)

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@awholegunch Were the images necessary? From other pages we just use the left panel (Table of Contents) to navigate between different sections right? 

If we want this as an image we could have had it as one single image instead of 5 different ones. Was there any specific requirement for the design/different images for each step instead of making all the steps as 1 image (lesser image requests, a little bit faster loading)?

**Comment by awholegunch** [comment]
The images were requested specifically (@sreevatsanraman) to show the different steps of the install, and people have said they saw them as buttons that they expected to be clickable. They have been here for a while...I was just tightening them up for a better presentation.

**Comment by awholegunch** [comment]
Oh, and they are five different ones so that they are clickable, without having to create a map and pass raw HTML through Sphinx...

**Comment by ajainarayanan** [comment]
👍 LGTM

**Comment by awholegunch** [comment]
Re-running Doc Build to make sure it passes before merging.

**Pull request merged**
