### PR TITLE
Fixes popover to not close on opening 2nd level popovers

### PR DESCRIPTION
**Pull request by ajainarayanan**

### CODE REVIEW

**Comment by elfenheart** [comment]
👍 LGTM

**Comment by tonybach** [comment]
Added a commit to fix this issue when the list of directives is empty when added to pipeline:

screen shot 2017-04-14 at 5 14 44 pm

Consulted with Lea, and we decided to move the button here:

screen shot 2017-04-14 at 5 15 00 pm

**Comment by ajainarayanan** [comment]
@tonybach changes 👍 LGTM

**Comment by leacd** [comment]
LGTM

**Pull request merged**
