### PR TITLE
[CDAP-8423] - Decide on Jump button functionality to transition between tracker and hydrator 

### PR DESCRIPTION
**Pull request by sushil-car**
https://issues.cask.co/browse/CDAP-8423

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@sushiladokar Putting this on hold as the changes are un-usable and more design changes coming in.

**Comment by ajainarayanan** [comment]
Have modified the look and functionality based on discussion with @bdmogal and @nitinmotgi. Ready for review

**Comment by elfenheart** [comment]
minor styling on `my-link-button:active`:

screen shot 2017-02-21 at 8 32 06 pm

**Comment by elfenheart** [comment]
👍  LGTM

**Pull request merged**
