### PR TITLE
CDAP-6663 expose Secure Store APIs for plugins in ActionContext

### PR DESCRIPTION
**Pull request by lumig242**
Simply expose secure store apis from CustomActionContext outside the ActionContext and provide access to plugins.

### CODE REVIEW

**Comment by lumig242** [comment]
Green build here: http://builds.cask.co/browse/CDAP-DUT4508-2

This has been tested manually. A related test case will be added in @thegreenfrog 's PR.

**Comment by albertshau** [comment]
lgtm

**Comment by Nishith** [comment]
LGTM.

**Comment by lumig242** [comment]
https://issues.cask.co/browse/CDAP-6663

**Pull request merged**
