### PR TITLE
[CDAP-9849] Modifies lineage to be at workflow level

### PR DESCRIPTION
**Pull request by ajainarayanan**
- Modifies tracker lineage api in UI to rollup programs at workflow level when rendering the lineage diagram.

JIRA: https://issues.cask.co/browse/CDAP-9849

### CODE REVIEW

**Comment by tonybach** [comment]
Code LGTM :+1:

**Comment by bdmogal** [comment]
@ajainarayanan does adding this parameter work?

**Comment by ajainarayanan** [comment]
Talked with @bdmogal . He is still thinking if this change should come in because once we do this change there is no way for the user to know what program a particular change originated from. So on-hold

**Comment by ajainarayanan** [comment]
The design needs to be revisited. Will come back to this in 5.1

**Pull request closed without merging**
