### PR TITLE
CDAP-8295 Set namespace directory permissions only if Kerberos is enabled

### PR DESCRIPTION
**Pull request by anwar6953**
[CDAP-8295](https://issues.cask.co/browse/CDAP-8295) Set namespace directory permissions only if Kerberos is enabled.
See JIRA for more details.

http://builds.cask.co/browse/CDAP-DUT5378-3

### CODE REVIEW

**Comment by anew** [comment]
LGTM.

However, this means that in insecure clusters, data is not owned by the group that was configured. Perhaps we have to update that in documentation for the namespace config?

Overall, I am not sure whether the behavior on insecure clusters is intuitive.

**Comment by anwar6953** [comment]
Created a JIRA for this: https://issues.cask.co/browse/CDAP-8299.

**Comment by anwar6953** [comment]
@anew, please take another look; updated unit tests accordingly.

**Comment by anew** [comment]
LGTM

**Comment by anwar6953** [comment]
Squashed commits; merging. Build is green.

**Pull request merged**
