### PR TITLE
Revise documentation fonts and colors

### PR DESCRIPTION
**Pull request by awholegunch**
Increases the size of the fonts, adds colors, and uses "Open Sans" to match Cask website.

There are **two** examples below:
- the first one uses a moderate increase in font size, and adds colors
- the second uses a larger increase in font size, but no color changes.

Running as a Quick Build: http://builds.cask.co/browse/CDAP-DQB304-17 (passed)

Pages of interest:
- Current Intro: http://docs.cask.co/cdap/4.2.0-SNAPSHOT/en/introduction/index.html

- **Revised Intro:** http://builds.cask.co/artifact/CDAP-DQB304/shared/build-17/Docs-HTML/html/introduction/index.html

- **Example RESTful API:** http://builds.cask.co/artifact/CDAP-DQB304/shared/build-17/Docs-HTML/html/reference-manual/http-restful-api/views.html

- **CLI:** http://builds.cask.co/artifact/CDAP-DQB304/shared/build-17/Docs-HTML/4.2.0-SNAPSHOT/en/reference-manual/cli-api.html

### CODE REVIEW

**Comment by awholegunch** [comment]
**Note:** I see that the last commit broke the header; fixing...

**Comment by awholegunch** [comment]
New build at: http://builds.cask.co/browse/CDAP-DQB304-6

- Moved search box
- left-sidebar hides

http://builds.cask.co/artifact/CDAP-DQB304/shared/build-6/Docs-HTML/4.2.0-SNAPSHOT/en/index.html

**Comment by awholegunch** [comment]
New build at: http://builds.cask.co/browse/CDAP-DQB304-7

all of the above plus a sticky footer, cleaned up CSS and HTML files, improved hiding.
CDAP logo in upper-left is clickable, and goes to main doc web page for CDAP.

**Comment by bdmogal** [comment]
A few suggestions:
1. Items in the header bar don't seem to be vertically centered. 
2. The footer, with the previous and next pages, needs improvement. As you scroll, there's no clear indication that its a separate thing - 
image
Perhaps add a different background or at least a horizontal rule between content and the footer
3. Doesn't scroll to the bottom - you can't see the last line completely
image
4. These section headers are not as prominent. Should we use h2? 
image - This seems like a big issue to me.
5.

**Comment by awholegunch** [comment]
These issues have been addressed in build 12 (http://builds.cask.co/browse/CDAP-DQB304-12). See links at the top of this page.
1. I investigated the spacing, and adjusted the search box up 1px. to match the other items in the header.
2. & 3. The footer issue has been addressed by: partially by removing the titles, just having previous and next buttons, with the page titles on mouse-over, so that the footer is always the same height; adding a rule across the top to distinguish it.
4. The rubric (which is what those titles are) have been increased to be the same as an H3: 120% font size and bold weight. See the Operation page (http://builds.cask.co/artifact/CDAP-DQB304/shared/build-12/Docs-HTML/4.2.0-SNAPSHOT/en/admin-manual/operations/index.html) to compare.
5. Was there a #5?
6. I have adjusted the background color of code samples from beige to eggshell blue.

**Comment by awholegunch** [comment]
**Build 13** (see links at top) now has a tightened up spacing in the header, and adjusted sidebar: the link is fixed, and so the symbol stays in one place vertically as the sidebar is scrolled. The color of the sidebar button has been lightened so it is almost not there. The breadcrumbs have been massaged so that they shouldn't wrap. And the footer has been adjusted so that it should not cut any text off.

**Comment by awholegunch** [comment]
**Build 17** (was *Build 14*) (see links at top) builds on the above with a custom Jinja extension that walks the TOC and talks back with the current breadcrumbs. This is so the breadcrumbs that are displayed at the top match the list in the Table of Contents sidebar rather than the titles of the documents, as those are often much longer. Plus, by having the two lists match, it makes more sense visually.

**Review by bdmogal — APPROVED** [review]
lgtm. Let's merge since we agree on the overall look and feel. There are some things that we need to fix (index, header, etc), but they can come in follow-up PRs.

**Pull request merged**
