### PR TITLE
Bump develop version to 4.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by sagarkapare**

### CODE REVIEW

**Comment by wolf31o2** [comment]
We should also update the versions in several JSON files.

**Comment by wolf31o2** [comment]
``` bash
$ grep '3.[4-6].0' $(find . -name '*.json')
./cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json:          "version": "3.6.0-1",
./cdap-distributions/src/packer/files/cdap-sdk.json:    "version": "3.4.0-1"
./cdap-examples/resources/weblog-analytics-config.json:        "version": "3.6.0-SNAPSHOT"
./cdap-ui/npm-shrinkwrap.json:  "version": "3.6.0-SNAPSHOT",
./cdap-ui/npm-shrinkwrap.json:      "version": "3.4.0",
./cdap-ui/npm-shrinkwrap.json:      "resolved": "https://registry.npmjs.org/bluebird/-/bluebird-3.4.0.tgz"
./cdap-ui/npm-shrinkwrap.json:      "from": "clean-css@>=3.4.0 <3.5.0",
./cdap-ui/npm-shrinkwrap.json:          "from": "lodash@>=3.5.0 <4.0.0",
./cdap-ui/npm-shrinkwrap.json:      "from": "js-yaml@>=3.6.0 <3.7.0",
./cdap-ui/package.json:  "version": "3.6.0-SNAPSHOT",
./cdap-ui/templates/apps/predefined/AmazonSQSToHBase.json:        "version": "3.6.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/EventClassifier.json:        "version": "3.6.0-SNAPSHOT",
./cdap-ui/templates/apps/predefined/KafkaToHBase.json:        "version": "3.6.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/KafkaToOLAPCube.json:        "version": "3.6.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/KafkaToStream.json:        "version": "3.6.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/LogsAggregateDataPipeline.json:        "version": "3.6.0-SNAPSHOT",
./cdap-ui/templates/apps/predefined/NaiveBayesTrainer.json:        "version": "3.6.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/StreamToHBase.json:        "version": "3.6.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/TwitterToHBase.json:        "version": "3.6.0-SNAPSHOT"
./cdap-ui/templates/apps/predefined/TwitterToStream.json:        "version": "3.6.0-SNAPSHOT"
```

**Comment by sagarkapare** [comment]
Updated json files. @wolf31o2 Please take a look again. Thanks!

**Comment by wolf31o2** [comment]
👍 LGTM

**Pull request merged**
