### PR TITLE
Bump to 5.1.1 snapshot

### PR DESCRIPTION
**Pull request by anwar6953**
Bump release/5.1 branch to 5.1.1-SNAPSHOT, since 5.1.0 has been released.

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
Let's hold on this change.

**Comment by anwar6953** [comment]
```
$ mvn clean package -DskipTests -Pexamples,templates

...

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Cask Data Application Platform (CDAP) 5.1.1-SNAPSHOT SUCCESS [  4.420 s]
[INFO] CDAP API Common .................................... SUCCESS [  3.647 s]
[INFO] CDAP API ........................................... SUCCESS [  5.942 s]
[INFO] CDAP Runtime SPI ................................... SUCCESS [  0.512 s]
[INFO] CDAP Protocol ...................................... SUCCESS [  2.586 s]
[INFO] CDAP Watchdog API .................................. SUCCESS [  0.436 s]
[INFO] CDAP SPI ........................................... SUCCESS [  0.256 s]
[INFO] CDAP Data Format ................................... SUCCESS [  0.962 s]
[INFO] CDAP Security SPI .................................. SUCCESS [  0.521 s]
[INFO] CDAP Build Common .................................. SUCCESS [  0.297 s]
[INFO] CDAP Common ........................................ SUCCESS [  6.966 s]
[INFO] CDAP Test Framework ................................ SUCCESS [  0.676 s]
[INFO] CDAP Notifications APIs ............................ SUCCESS [  0.522 s]
[INFO] CDAP Security ...................................... SUCCESS [  3.268 s]
[INFO] CDAP HBase SPI ..................................... SUCCESS [  0.288 s]
[INFO] CDAP HBase Compactability Base ..................... SUCCESS [  1.638 s]
[INFO] CDAP Transactional Messaging System ................ SUCCESS [  2.183 s]
[INFO] CDAP Explore Client ................................ SUCCESS [  0.706 s]
[INFO] CDAP Data-Fabric ................................... SUCCESS [ 11.341 s]
[INFO] CDAP Watchdog ...................................... SUCCESS [  3.497 s]
[INFO] CDAP Notifications ................................. SUCCESS [  0.800 s]
[INFO] CDAP Java Client ................................... SUCCESS [  0.886 s]
[INFO] CDAP App-Fabric .................................... SUCCESS [ 15.743 s]
[INFO] CDAP Explore JDBC Driver ........................... SUCCESS [  2.957 s]
[INFO] CDAP Explore ....................................... SUCCESS [  3.238 s]
[INFO] CDAP Spark1 API Scala 2.10 ......................... SUCCESS [  7.461 s]
[INFO] CDAP PySpark Library ............................... SUCCESS [  0.440 s]
[INFO] CDAP Spark1 Core Scala 2.10 ........................ SUCCESS [ 27.581 s]
[INFO] CDAP Unit Test Framework ........................... SUCCESS [ 15.775 s]
[INFO] CDAP Examples ...................................... SUCCESS [  0.864 s]
[INFO] Count Random ....................................... SUCCESS [  2.818 s]
[INFO] Clicks and Views App ............................... SUCCESS [  2.786 s]
[INFO] Application with Cube Service ...................... SUCCESS [  1.841 s]
[INFO] Data Cleansing App ................................. SUCCESS [  2.379 s]
[INFO] CDAP Spark2 API Scala 2.11 ......................... SUCCESS [  8.218 s]
[INFO] CDAP Spark2 Core Scala 2.11 ........................ SUCCESS [ 20.787 s]
[INFO] CDAP Unit Test Framework with Spark2_2.11 .......... SUCCESS [ 11.423 s]
[INFO] DecisionTreeRegression ............................. SUCCESS [ 37.498 s]
[INFO] FileSet Example .................................... SUCCESS [  2.449 s]
[INFO] Hello World ........................................ SUCCESS [  1.922 s]
[INFO] LogAnalysis ........................................ SUCCESS [  9.661 s]
[INFO] Purchase App ....................................... SUCCESS [  2.196 s]
[INFO] SpamClassifier ..................................... SUCCESS [ 12.740 s]
[INFO] SparkKMeans ........................................ SUCCESS [ 15.238 s]
[INFO] Spark Page Rank .................................... SUCCESS [  2.250 s]
[INFO] Sport Results Analytics ............................ SUCCESS [  2.089 s]
[INFO] Stream Conversion .................................. SUCCESS [  2.971 s]
[INFO] User Profiles App .................................. SUCCESS [  2.139 s]
[INFO] WebAnalytics App ................................... SUCCESS [  2.001 s]
[INFO] WikipediaPipeline .................................. SUCCESS [ 10.909 s]
[INFO] WordCount App ...................................... SUCCESS [  2.057 s]
[INFO] CDAP App Templates ................................. SUCCESS [  0.291 s]
[INFO] CDAP ETL Template .................................. SUCCESS [  0.395 s]
[INFO] CDAP ETL App Template API .......................... SUCCESS [  0.762 s]
[INFO] CDAP ETL App Template Spark API .................... SUCCESS [  5.311 s]
[INFO] CDAP ETL Protocol .................................. SUCCESS [  0.943 s]
[INFO] CDAP ETL App Template Core ......................... SUCCESS [  2.614 s]
[INFO] Hydrator Spark1 Core Scala 2.10 .................... SUCCESS [  4.350 s]
[INFO] Hydrator Test Classes .............................. SUCCESS [  1.313 s]
[INFO] CDAP ETL Batch Application ......................... SUCCESS [  7.180 s]
[INFO] CDAP Data Pipeline Application Spark1 Scala 2.10 ... SUCCESS [ 11.679 s]
[INFO] Hydrator Spark2 Core Scala 2.11 .................... SUCCESS [  4.306 s]
[INFO] CDAP Data Pipeline Application Spark2 Scala 2.11 ... SUCCESS [ 12.395 s]
[INFO] CDAP Data Streams Application Spark1 Scala 2.10 .... SUCCESS [  4.825 s]
[INFO] CDAP Data Streams Application Spark2 Scala 2.11 .... SUCCESS [  4.856 s]
[INFO] CDAP Application Archetypes ........................ SUCCESS [  0.260 s]
[INFO] CDAP Data Pipeline Batch Plugins Archetype ......... SUCCESS [  0.388 s]
[INFO] CDAP ETL Tools ..................................... SUCCESS [  3.328 s]
[INFO] CDAP Program Run Report Application Spark2 Scala 2.11 SUCCESS [ 18.685 s]
[INFO] CDAP HBase 0.98 Compatibility ...................... SUCCESS [  1.283 s]
[INFO] CDAP Data-Fabric Tests ............................. SUCCESS [  1.479 s]
[INFO] CDAP Transactional Messaging System Tests .......... SUCCESS [  0.591 s]
[INFO] CDAP CLI ........................................... SUCCESS [  4.713 s]
[INFO] CDAP Gateway ....................................... SUCCESS [  2.020 s]
[INFO] CDAP UI ............................................ SUCCESS [  6.096 s]
[INFO] CDAP Standalone .................................... SUCCESS [  1.971 s]
[INFO] CDAP Java Client Tests ............................. SUCCESS [  2.103 s]
[INFO] CDAP CLI Tests ..................................... SUCCESS [  0.823 s]
[INFO] CDAP App Fabric Tests .............................. SUCCESS [  1.276 s]
[INFO] CDAP HBase 0.96 Compatibility ...................... SUCCESS [  1.383 s]
[INFO] CDAP HBase 1.0-CDH5.5.0 Compatibility .............. SUCCESS [  1.629 s]
[INFO] CDAP HBase 1.0-CDH Compatibility ................... SUCCESS [  1.377 s]
[INFO] CDAP HBase 1.0 Compatibility ....................... SUCCESS [  1.417 s]
[INFO] CDAP HBase 1.1 Compatibility ....................... SUCCESS [  1.502 s]
[INFO] CDAP HBase 1.2-CDH5.7.0 Compatibility .............. SUCCESS [  1.752 s]
[INFO] CDAP Documentation Generator ....................... SUCCESS [  0.424 s]
[INFO] CDAP Kafka Server .................................. SUCCESS [  0.414 s]
[INFO] CDAP KMS ........................................... SUCCESS [  0.468 s]
[INFO] CDAP Master ........................................ SUCCESS [  2.085 s]
[INFO] CDAP Google Cloud Dataproc Runtime Extension ....... SUCCESS [  2.183 s]
[INFO] CDAP Amazon EMR Runtime Extension .................. SUCCESS [  0.520 s]
[INFO] CDAP Remote Hadoop Runtime Extension ............... SUCCESS [  0.305 s]
[INFO] CDAP Operational Stats Core ........................ SUCCESS [  0.868 s]
[INFO] CDAP Distributions ................................. SUCCESS [  0.403 s]
[INFO] CDAP Application Archetypes ........................ SUCCESS [  0.178 s]
[INFO] CDAP Spark Java Archetype .......................... SUCCESS [  0.416 s]
[INFO] CDAP Spark Scala Archetype ......................... SUCCESS [  0.398 s]
[INFO] CDAP MapReduce Archetype ........................... SUCCESS [  0.274 s]
[INFO] CDAP Application Archetype ......................... SUCCESS [  0.247 s]
[INFO] CDAP Integration Test Framework 5.1.1-SNAPSHOT ..... SUCCESS [  1.682 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:51 min
[INFO] Finished at: 2018-10-12T20:03:32-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by anwar6953** [comment]
Changing the PR to change content to 5.1.1, instead of 5.1.1-SNAPSHOT, as we will be releasing 5.1.1 soon.

**Review by rohitsinha54 — APPROVED** [review]

**Comment by anwar6953** [comment]
Squashed commits.

**Comment by anwar6953** [comment]
Got approval from @sreevatsanraman that this no longer needs to be on hold.

**Pull request merged**
