### PR TITLE
Revert "(CDAP-6385) Moved the FileSecureStore password from cdap-defa…

### PR DESCRIPTION
**Pull request by Nishith**
…ult.xml to (#6241)"

This reverts commit 67c9a4605c85228ce31a635bc2fb48226ef40d16.

### CODE REVIEW

**Comment by sagarkapare** [comment]
Does this fix - http://builds.cask.co/browse/CDAP-ITN17-ST-13/log?

**Comment by Nishith** [comment]
Yes.

**Comment by Nishith** [comment]
Merged to unblock every one.

**Comment by sagarkapare** [comment]
Since the PR is reverted should we re-open https://issues.cask.co/browse/CDAP-6385?

**Pull request merged**
