### PR TITLE
(CDAP-15521) added the initial infrastructure to implement a graphql layer

### PR DESCRIPTION
**Pull request by miguelvelezmj25**

### CODE REVIEW

**Comment by miguelvelezmj25** [comment]
JIRA: https://issues.cask.co/browse/CDAP-15521

**Comment by miguelvelezmj25** [comment]
Build: https://builds.cask.co/browse/CDAP-DUT6984

**Comment by nitinmotgi** [comment]
Why is this not a Node JS module and why a java module ?

**Comment by miguelvelezmj25** [comment]
@nitinmotgi GraphQL is a specification with various implementation in different languages (e.g. Java, JavaScript, Go, Scala). Hence, most, if not all, features of the specification are supported by all implementations We primarily selected Java as the implementation language since we want to move the querying logic to the backend.

**Comment by nitinmotgi** [comment]
Don’t see the value of it being in the backend. It can still be in backend but more specifically in the nodejs server backend of the front end. It seems wrong to put it in the backend Java. It graphql is the aggregator then it makes more sense for it to be nodejs. We can product complexity to backend for doing aggregations.

**Comment by nitinmotgi** [comment]
Thanks for your contribution merging it.

**Comment by miguelvelezmj25** [comment]
Not only does this layer do aggregation, but it will also use remote client, which do service discovery, to fetch the data. It you put graphql in the front end, then it will block the page while the fetchers retrieve the data. By putting it in the backend, the layer will expose one endpoint which is used by clients (e.g., the frontend) to retrieve the data. Think of it as using graphql instead of REST endpoints. You would not want to put your enpoints in the frontend.

**Comment by nitinmotgi** [comment]
Am not able to understand the incremental value of such a interface. Have we done any analysis of that and compared it against the TCO of it ?

**Comment by miguelvelezmj25** [comment]
Is TCO the Total Cost of Ownership? In any case, I had a discussion with @elfenheart about where the layer should be and this is what he said: "The main benefit [of having the layer in the backend] is developers productivity, where the backend will define the schema, and it's done. If we do it in the NodeJS, backend have to define the schema, then that schema has to be reimplemented in the NodeJS GraphQL layer." In other words, the backend contains the data that is requested by clients. Therefore, it is better to have the layer in the backend to define the schema describing that data. If we put the layer in the frontend, then we are coupling the frontend and the backend, and that would now help developers on either side.

**Comment by chtyim** [comment]
Here is my take in Q&A form:

1. Can GraphQL replaces REST for communications between backend services?
A: Technically GraphQL is yet another RPC protocol, so it can perform whatever REST can do. However, given that GraphQL is quite verbose, especially when carrying binary data, it might not be an optimal choice. Typically for backend services communication, it's better to use more efficient protocol, such as REST (which is quite free form) or something like gRPC.

1. But GraphQL can drop unnecessary fields, isn't it more efficient?
A: Backend is having a (micro)service oriented design, and the network API are mainly designed for functional purpose (e.g. create, delete, list, get), not for querying flexibility (some API are, such as metrics or logs, that's why they have query API endpoints). The benefits of filtering out fields is very minimal.

1. GraphQL can increase development efficient.
A: It depends on where GraphQL is being used. If GraphQL is used as a federation service for the UI, then it can help FE development a lot. This is because a change of UI requirement doesn't always need to wait for BE to change the API, as long as the information is already available from the backend API. FE can rely on GraphQL to federate multiple calls to BE to fetch all the necessary information from multiple BE services.
However, if a change in UI actually requires new information being fetched from the BE (or fetch it efficiently), then it still need to wait for BE to make the change to the API.
Using GraphQL schema doesn't really speed up the BE development, as it is just yet another other way to define the RPC contract (In REST, it is defined by documentation. In gRPC, it is defined using protobuf).

1. Using GraphQL for backend services can decouple FE and BE development.
A: The decoupling should be achieved by well defined RPC contract, not by a particular technology. As mentioned above, different RPC protocols have their own way to define the contract. As developers, we should honor the contract to maximize development efficiency.

@anew @sreevatsanraman @nitinmotgi Maybe you have something to add as well?

**Comment by chtyim** [comment]
In conclusion, I think it is better to jus t use GraphQL as a query federation service for now.

**Comment by miguelvelezmj25** [comment]
I would argue that the third point is the main reason to implement the layer in the backend. However, there are several questions and comments that I would like to make, but I think it would be better to have a discussion in person. 

In the meantime, @chtyim @elfenheart @anwar6953 @anew @sreevatsanraman @nitinmotgi would the code in this PR (with the infrastructure to create a graphql layer) change if we use the graphql layer differently? I would argue "no" since there is a standard way to create a graphql layer. I think that what might change, depending on how we use the layer, is the data fetchers, which I will send in a separate PR.

**Comment by nitinmotgi** [comment]
After reviewing all the comments, I strongly recommend that we treat this as a federated service to be used by UI/FE. We should not have a backend service. Why should we incur the cost when we have better alternatives.

**Comment by miguelvelezmj25** [comment]
@nitinmotgi We can use it as a federated service, but putting the layer in the frontend would create a burden and coupling for the frontend and backend developers

**Comment by anew** [comment]
my $0.02: Saying, we will use GraphQL instead of using REST, does not add value. The REST APIs will not go away because they are used by CLI and programmatic clients. For the backend to expose to "official" APIs just duplicates the effort of maintaining APIs. If this GraphQL layer is only used the UI, then it is part of the UI just like the NodeJS server is now. The REST APIs remain the source of truth for all clients, but any client (including the U) can chose to add an extra layer of abstraction.

**Pull request closed without merging**
