### PR TITLE
[CDAP-13549] Adds bigquery and gcs icons in dataprep connections popover

### PR DESCRIPTION
**Pull request by ajainarayanan**
JIRA: https://issues.cask.co/browse/CDAP-13549
Build: https://builds.cask.co/browse/CDAP-URUT19

### CODE REVIEW

**Comment by elfenheart** [comment]
There's another set of Big Query and GCS icon needed to be added to `DataPrepConnections/index.js` for the side panel

**Review by elfenheart — APPROVED** [review]
👍  LGTM

**Review by elfenheart — APPROVED** [review]
👍 LGTM

**Review by bdmogal — CHANGES_REQUESTED** [review]
Need to confirm if we want to call it GCP or Google Cloud. Please wait for confirmation from me

**Comment by ajainarayanan** [comment]
Talked to @nitinmotgi and @bdmogal . Confirmed on GCP for labelling. Merging.

**Pull request merged**
