### PR TITLE
Make hashCode transient in Principal, so its not serialized

### PR DESCRIPTION
**Pull request by bdmogal**

### CODE REVIEW

**Comment by anwar6953** [comment]
What's the impact? Why is this needed?

**Comment by bdmogal** [comment]
There's no immediate impact to the user, in that `Principal` is not currently in the response of a RESTful API. However, if we serialized it in an authorization backend other than Sentry (say a database backed authorization extension), it may unnecessarily include the `hashCode`. 

Again, this doesn't break anything. Its just something I noticed while documenting the REST APIs.

**Comment by anwar6953** [comment]
lgtm

**Comment by sreevatsanraman** [comment]
Not merging the change to the release, since this is not required. Please reopen against develop.

**Pull request closed without merging**
