### PR TITLE
[CDAP-8433][CDAP-8861] Minor UI bugfixes

### PR DESCRIPTION
**Pull request by tonybach**
[CDAP-8433] https://issues.cask.co/browse/CDAP-8433
- Show units for memory for YARN in the Administration page.

[CDAP-8861] https://issues.cask.co/browse/CDAP-8861
- Removed CDAP Version Range from the card of Market entities.
- Also removed unnecessary cdapVersion prop in the AccessTokenModal.

### CODE REVIEW

**Comment by elfenheart** [comment]
@tonybach should remove the versions from use cases as well

screen shot 2017-03-07 at 5 56 42 pm

**Comment by elfenheart** [comment]
Also the show units for YARN memory is wrong. It should only apply to memory information. Virtual Cores for instance, is just an integer, not bytes.

screen shot 2017-03-07 at 6 05 05 pm

**Comment by tonybach** [comment]
@elfenheart Right now for the stats on the Administration page, there's no way to know which values need units, since for each stat we just get a single key-value pair from the backend, with the value always being an integer. 

That's why I had to manually create a list of the stats that we need to add units to. Should this be a JIRA to the backend, to return more info, instead of just an integer value?

**Comment by elfenheart** [comment]
@tonybach yeah, perhaps file a JIRA for the backend to return what kind of value it is. But at the moment, it might require some hard coding for those specific keys to display the unit

**Comment by tonybach** [comment]
@elfenheart Yep, hardcoded the list of keys that need units in my last commit.

**Review by ajainarayanan — APPROVED** [review]
👍 LGTM

**Comment by tonybach** [comment]
Build: http://builds.cask.co/browse/CDAP-DRC6035

**Pull request closed without merging**
