### PR TITLE
[CDAP-12824] make schema editor editable when dataset selector do not find schema

### PR DESCRIPTION
**Pull request by elfenheart**
JIRA: https://issues.cask.co/browse/CDAP-12824

### CODE REVIEW

**Comment by ajainarayanan** [comment]
👍 Code LGTM

**Comment by elfenheart** [comment]
@ajainarayanan there was a problem when reopening the modal, the schema would be empty and non-editable.

**Review by tonybach — APPROVED** [review]
LGTM 👍

**Comment by bdmogal** [comment]
Lgtm

**Pull request merged**
