### PR TITLE
[HYDRA-402] Bugfix release/ui hydrator user friendly config

### PR DESCRIPTION
**Pull request by elfenheart**
Consolidate executor and driver resources into pipeline resource.

JIRA: https://issues.cask.co/browse/HYDRA-402

### CODE REVIEW

**Comment by ajainarayanan** [comment]
Code LGTM 👍 

However there are two things in terms of design,
1. For some reason I am finding this to be a little off-spaced. 
screen shot 2016-08-17 at 2 16 13 am
2. Would we have a usecase where the user wants to have different settings for driver and executor resources?
3. What happens if the user imports a pipeline that has different value? Now the UI overwrites one with the other.

Perhaps @ToddGreenstein or @nitinmotgi could give some insights into this

**Comment by nitinmotgi** [comment]
Yes, they could have. Also, the design again is not as per mocks. Could we put MR and Spark in same line please. Thanks.

**Comment by ToddGreenstein** [comment]
@sreevatsanraman suggested we take the driver resource as the executor resource, and wouldn't the same should be true for importing?    Do we need to change this?

**Comment by sreevatsanraman** [comment]
@ToddGreenstein @ajainarayanan - taking the executor resource as the driver resource was the proposal.

**Comment by elfenheart** [comment]
screen shot 2016-08-17 at 12 29 07 pm

**Comment by elfenheart** [comment]
Closing. Changes is in https://github.com/caskdata/cdap/pull/6484

**Pull request closed without merging**
