### PR TITLE
(CDAP-8855) Port fix for TEPHRA-223: Transactions started after a snapshot restore can have incorrect invalid transaction list

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA: https://issues.cask.co/browse/CDAP-8855
Build - http://builds.cask.co/browse/CDAP-RUT753-1

The first commit copies over the classes from Tephra v0.8.0-incubating, and the second commit contains the fix.

### CODE REVIEW

**Comment by anew** [comment]
LGTM.

**Comment by anew** [comment]
Actually, almost LGTM. It would be good to add comments in the modified copied tephra files, so that anyone who looks at them can see immediately what was changed.

**Comment by poornachandra** [comment]
@anew I'm planning to leave the two commits as-is without squashing them. That should be sufficient to figure out what changed, no?

**Comment by anew** [comment]
ho do I see commits when reading code?

**Comment by anew** [comment]
LGTM

**Comment by poornachandra** [comment]
Build is green

**Pull request merged**
