### PR TITLE
[WRANGLER-58] DataPrep Parse Directive

### PR DESCRIPTION
**Pull request by elfenheart**
Dependent on https://github.com/caskdata/cdap/pull/8418

JIRA: https://issues.cask.co/browse/WRANGLER-58

### CODE REVIEW

**Comment by bdmogal** [comment]
1. The red banner should disappear after the next successful directive.
2. Change "value match regex" to "value matches regex"
3. If you do parse-as-log on a non-log col

**Comment by bdmogal** [comment]
@elfenheart 
1. I am also not sure about the filter if value is empty directive. Currently it is implemented as value is whitespace. Instead, perhaps it should be ``filter-row-if-true <value>.length == 0``. I will find out the right directive and get back to you
2. the dropdown should close right after clicking Apply
3. Here's what happens when you have multiple errors + dropdown. Only one of the errors should be visible at a time:
image
4. The color of the red banner is different from the color of red banners in pipelines.

**Comment by elfenheart** [comment]
@bdmogal for 3, those errors are for different context though. Why should it close the other?

**Comment by bdmogal** [comment]
@elfenheart I am not sure. Both the power mode and the point and click experience are essentially doing the same action - applying directives on the data. Any errors IMO should represent the last directive applied. You can't have 2 directives applied (one with power mode; and the other with point and click) at the same time, right?

**Comment by bdmogal** [comment]
The modal for depth of JSON should be smaller. Is there a way to restrict it to a number widget? Also, it could use some help text.
```
The maximum depth in the JSON up to which to parse. e.g. for the JSON '{"key": { "key1": "value1, "key2": "value2""}}'``; depth 1 will parse to a column 'key' with value '{ "key1": "value1", "key2": "value2"}', while depth 2 will parse to 2 columns: 'key_key1' with value 'value1', and 'key_key2' with value 'value2'. 
```
?

**Comment by elfenheart** [comment]
@bdmogal these improvements will be done in separate PR as discussed

**Comment by tonybach** [comment]
I think we should add `backdrop='static'` to the newly created `Modal`s to be consistent with our existing Modals. We already have the X and the Cancel buttons to close the modal.

**Comment by ajainarayanan** [comment]
Apart from @tonybach's comment 👍 LGTM

**Comment by tonybach** [comment]
LGTM :+1:

**Pull request merged**
