### PR TITLE
(CDAP-8250) On connection closed unexpectedly, no need to log details

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by anwar6953** [comment]
Does this fix https://issues.cask.co/browse/CDAP-8250?

**Comment by chtyim** [comment]
There is always a JIRA for everything... ..

**Comment by chtyim** [comment]
Build: http://builds.cask.co/browse/CDAP-RUT559

**Comment by anew** [comment]
LGTM

**Comment by chtyim** [comment]
Build passed

**Pull request merged**
