### PR TITLE
CDAP 3.5.2 release notes

### PR DESCRIPTION
**Pull request by awholegunch**
Running as a Quick Build: http://builds.cask.co/browse/CDAP-DQB150-4

Release Notes: http://builds.cask.co/artifact/CDAP-DQB150/shared/build-4/Docs-HTML/3.5.2-SNAPSHOT/en/reference-manual/release-notes.html#release-3-5-2

Hydrator Plugins: http://builds.cask.co/artifact/CDAP-DQB150/shared/build-4/Docs-HTML/3.5.2-SNAPSHOT/en/hydrator-manual/plugins/actions/index.html

### CODE REVIEW

**Comment by anwar6953** [comment]
Can you take a look at other JIRAs also fixed in 3.5.2?
For instance, I just added release notes to https://issues.cask.co/browse/CDAP-6587

**Comment by anwar6953** [comment]
I also don't see in the list - https://issues.cask.co/browse/CDAP-7291

**Comment by awholegunch** [comment]
"On-hold" as we have changes to come, and this should not be merged until those are resolved.

**Comment by anwar6953** [comment]
Can you add this also? Just now merged to release/3.5:
https://issues.cask.co/browse/CDAP-2945

**Comment by ecfm** [comment]
Do these two changes need to be included https://issues.cask.co/browse/CDAP-6183 and https://issues.cask.co/browse/CDAP-7682 ?

**Comment by sreevatsanraman** [comment]
LGTM. We will need one more pass with new JIRAs

**Pull request merged**
