### PR TITLE
Remove remaining references to cdap-notifications module.

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Review by CuriousVini — APPROVED** [review]
lgtm 👍

**Review by albertshau — APPROVED** [review]
lgtm

**Review by albertshau — APPROVED** [review]
lgtm

**Review by CuriousVini — APPROVED** [review]
lgtm second commit 👍

**Comment by chtyim** [comment]
RAT passed https://builds.cask.co/browse/CDAP-DRC8727-56

**Pull request merged**
