### PR TITLE
Merge release 3.6 to develop.

### PR DESCRIPTION
**Pull request by sagarkapare**
Following were the conflicts - 

1. BaseHiveExploreService: Not using namespace.getNamespace.Id() in following
a. `String database = getHiveDatabase(namespace.getNamespace());`
b. `inactiveOperationInfo.getHiveDatabase().equals(getHiveDatabase(namespace.getNamespace()))`

2. build.sh: took `DEFAULT_XML_MD5_HASH` from develop

3. cdap-cli.bat: took the release/3.6 version

4. cdap-site.xml: Description of `explore.executor.container.memory.mb` and `log.saver.container.memory.mb` took from develop 

5. IntegrationTestManager: Merged the imports

6. LoggingContextHelper: Removed unused imports

7. tx-maintenance.rst: took develop version for the command `$ /opt/cdap/master/bin/cdap run co.cask.cdap.data.tools.SimpleHBaseQueueDebugger`

8. tx-debugger.bat new file.

### CODE REVIEW

**Comment by sagarkapare** [comment]
Build is running here - https://builds.cask.co/browse/CDAP-DUT5022-1

**Comment by anwar6953** [comment]
lgtm

**Comment by awholegunch** [comment]
2, 3, 4, 7, and 8 LGTM. I asked @sagarkapare to run a Quick Build in docs before merging.

**Comment by sagarkapare** [comment]
Doc build is running here - https://builds.cask.co/browse/CDAP-DQB165-1

**Comment by awholegunch** [comment]
@sagarkapare That was a good idea, but not quite the right fix. That build is broken because of https://github.com/caskdata/cdap-apps/pull/126 and is fixed in https://github.com/caskdata/cdap/pull/7040 (not yet merged). The fix is more than the MD5 hash; the file was changed such that the references to it need to be changed. I would reverse your commit, and then  just accept the doc build being broken as a known issue. Of course, we could merge 7040 and then you could pull it in :)

**Comment by sagarkapare** [comment]
@awholegunch I have reverted the last commit. Release build is green here - https://builds.cask.co/browse/CDAP-DUT5022-2 merging this PR. Doc build would be fixed when #7040 is merged to develop.

**Pull request merged**
