### PR TITLE
[CDAP-20290] Remove remaining hive dependencies and fix unit tests to depend only on Gson

### PR DESCRIPTION
**Pull request by dli357**

### CODE REVIEW

**Review by itsankit-google — APPROVED** [review]
lgtm

**Comment by vsethi09** [comment]
@dli357 There are few `org.apache.hive:hive-storage-api:jar:2.7.2` transitive dependencies from `org.apache.spark:spark-sql_2.12:jar:3.1.1` dependency. Should these transitive hive dependencies be excluded?
Run `mvn dependency:tree` to see them.

**Comment by dli357** [comment]
> @dli357 There are few `org.apache.hive:hive-storage-api:jar:2.7.2` transitive dependencies from `org.apache.spark:spark-sql_2.12:jar:3.1.1` dependency. Should these transitive hive dependencies be excluded? Run `mvn dependency:tree` to see them.

I think the transitive dependencies are ok unless they include log4j, in which case we exclude log4j itself. I don't think it's necessary to explicitly exclude hive since we're not using it anymore. The removal being done here is mostly just cleaning up remaining references that aren't needed anymore.

**Review by vsethi09 — APPROVED** [review]

**Review by dj-smart — APPROVED** [review]
LGTM

**Pull request merged**
