### PR TITLE
Fix transactional publish from program context

### PR DESCRIPTION
**Pull request by chtyim**
- Set the transaction write pointer if available.

### CODE REVIEW

**Comment by chtyim** [comment]
Verified on cluster. Filed https://issues.cask.co/browse/CDAP-8813 for unit-test improvement.

**Comment by chtyim** [comment]
Building http://builds.cask.co/browse/CDAP-RUT736

**Comment by poornachandra** [comment]
LGTM

**Comment by poornachandra** [comment]
Will this fix need to be back ported?

**Comment by chtyim** [comment]
Only if we release 4.0.x?

**Comment by poornachandra** [comment]
LGTM

**Pull request merged**
