### PR TITLE
add unit test for downloading support bundle

### PR DESCRIPTION
**Pull request by zbj6266**

### CODE REVIEW

**Review by dli357 — COMMENTED** [review]
Is it intended for us to update the UI in this PR?

**Comment by zbj6266** [comment]
> Is it intended for us to update the UI in this PR?

No this is just test we generated an zip bundle and contains several expected folders

**Comment by dli357** [comment]
To clarify, it looks like we updated the submodules in this PR, was that intended?

**Review by dli357 — APPROVED** [review]

**Comment by zbj6266** [comment]
> To clarify, it looks like we updated the submodules in this PR, was that intended?

No I removed that one

**Pull request merged**
