### PR TITLE
[TRACKER-272] Pressing enter should save the dictionary item and start a new entry

### PR DESCRIPTION
**Pull request by sushil-car**
https://issues.cask.co/browse/TRACKER-272

### CODE REVIEW

**Comment by sushil-car** [comment]
Added save functionality on click of enter.
So removed the save icon button and new entry row will be visible always to add new column

**Comment by ajainarayanan** [comment]
@sushiladokar Hitting ENTER on filling column name doesn't add a new row. Is that intended? Is it a criteria to have all the fields filled up before creating a new row?

**Comment by sushil-car** [comment]
User will fill required fields and then hit enter on description text box. This will save record and will display new row to add another. User can save only one record at a time. Name, type and description are mandatory fields.
@russorat is this correct behavior or need any changes

**Comment by russorat** [comment]
@ajainarayanan @sushiladokar description is a required field. if the user only enters column name and not description, and tries to enter a new row, there should be an error message displayed.

**Comment by russorat** [comment]
@ajainarayanan could you take a look here?

**Comment by ajainarayanan** [comment]
One last comment, we seem to be making a backend call on each new row addition and when backend takes time to get a response there is no feedback if something is happening or not. Would be good if we had a loading indicator, indicating that the field is being added before the user wants to add a new row. 

We might also want to prevent the user from pressing multiple RETURNs which throws an exception in the backend (this is when the backend takes time to respond).

**Comment by ajainarayanan** [comment]
Also noticed when we add a new entry in the dictionary the entry is automatically sorted and the newly added row gets inserted in between. Just wanted to confirm if thats the behavior we want.

The reason I am asking is if the user goes to multiple pages and if the newly added row gets added to the second page then its not clear if something has been added or not.

**Comment by ajainarayanan** [comment]
👍 LGTM. 

@sushiladokar  One thing to note is the commits cannot be squashed to one any more as rebase is not easy or clean after doing a merge with develop. Lets try to do rebase from next time so that we can squash and combine all commits to one before merging it to develop.

**Comment by abhinavbansal246** [comment]
@sushiladokar Please squash the commits

**Comment by sushil-car** [comment]
Squashing the commits

**Pull request merged**
