### PR TITLE
Consolidate spark-shell call to one.

### PR DESCRIPTION
**Pull request by chtyim**
Should speed up the start time by couple seconds since launch `spark-shell` takes couple seconds.

### CODE REVIEW

**Review by wolf31o2 — APPROVED** [review]
👍

**Comment by chtyim** [comment]
Verified on cluster.

**Review by albertshau — CHANGES_REQUESTED** [review]
if SPARK_HOME is set, then SPARK_COMPAT will not be computed

**Comment by wolf31o2** [comment]
Ugh... he's right. You need to check both variables are set.

**Pull request merged**
