### PR TITLE
CDAP-6599 Added binding for the NamespaceQueryAdmin in ContextManager used for hive queries.

### PR DESCRIPTION
**Pull request by sagarkapare**
JIRA: https://issues.cask.co/browse/CDAP-6599

### CODE REVIEW

**Comment by sagarkapare** [comment]
Verified on the cluster that the Explore query works after this fix.

**Comment by sagarkapare** [comment]
Build is running here - http://builds.cask.co/browse/CDAP-DUT4466-1

**Comment by bdmogal** [comment]
The change looks ok. But why does `ContextManager` need a separate injector?

**Comment by bdmogal** [comment]
I mean it would be good to find out and add a comment. Also, if the injector is indeed needed, then we should add a unit test for it, so we can catch such failures in the build. It is impossible to test this stuff otherwise.

**Comment by sagarkapare** [comment]
@bdmogal Injector is used in the MapReduce job that hive launches. I have added a unit test case for it. Please take a look again.
Thanks!

**Comment by bdmogal** [comment]
LGTM

**Comment by sagarkapare** [comment]
Build is running here - http://builds.cask.co/browse/CDAP-DUT4466-4

**Comment by sreevatsanraman** [comment]
Build passed. Merging.

**Pull request merged**
