### PR TITLE
Separate out and move some spark tests to run with Spark2.

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by chtyim** [comment]
Build https://builds.cask.co/browse/CDAP-RUT1398

**Comment by anwar6953** [comment]
What's the motivation for this?

**Comment by chtyim** [comment]
To reduce change of having SparkTest runs out of permgen.

**Comment by chtyim** [comment]
Build passed

**Review by anwar6953 — APPROVED** [review]

**Pull request merged**
