### PR TITLE
[CDAP-6235] add cdap mode to navbar

### PR DESCRIPTION
**Pull request by elfenheart**
screen shot 2016-07-13 at 4 58 13 pm
screen shot 2016-07-13 at 4 58 26 pm

### CODE REVIEW

**Comment by ajainarayanan** [comment]
@elfenheart Any specific reason why we are not passing this as part of the `config.js` json? We have the configurations passed through that today (for instance security enabled).

**Comment by elfenheart** [comment]
screen shot 2016-07-14 at 3 15 46 pm
screen shot 2016-07-14 at 3 15 38 pm

**Comment by ajainarayanan** [comment]
👍 LGTM

**Comment by elfenheart** [comment]
demoed to @nitinmotgi

**Pull request merged**
