### PR TITLE
(CDAP-17287) Fixed a bug in the event upload that it will hang for 30 seconds

### PR DESCRIPTION
**Pull request by chtyim**
- A response status was not written when the upload finished
- Refactored the code to move the runtime client logic in the same class
- Added unit-test for the event upload

### CODE REVIEW

**Review by tivv — COMMENTED** [review]
Now `uploadSparkEventLogs` and `sendMessages` are very similar up to BadRequestException processing and body to post. Can we unify those and have one copy of all urlconnection processing harness?

**Comment by chtyim** [comment]
There are subtle differences between lines in the two methods (e.g. content-type, compression or not, direct copying of file vs avro encoding the bytes). If we try to have a generic method to support that, the method itself might not seems so readable. I did a small refactoring to extract out the connection closing part, which brings a bit more clarity to both methods.

**Review by tivv — COMMENTED** [review]
Thanks!
I am wondering if we could bring it down to something like
```
doPost(path,  "avro/binary", OutputStream os -> 
   writeMessages(messages, EncoderFactory.get().directBinaryEncoder(os, null)));
```
To do this we would need to have same processing for BadRequestException. Could you confirm it is retryable? I see that io.cdap.cdap.common.service.Retries#DEFAULT_PREDICATE checks for `RetryableException` and BadRequestException do not inherit from it. If it is, we can pass a custom predicate.

**Comment by tivv** [comment]
Please disregard my previous comment. I've doublechecked the code and see that I miss different calls on opening an outputStream. LGTM.

**Review by tivv — APPROVED** [review]

**Review by MEseifan — APPROVED** [review]

**Pull request merged**
