### PR TITLE
CDAP-5734 increase timeout to 10 min from 5 min, we have seen tests f…

### PR DESCRIPTION
**Pull request by gsps1**
…ail as MR job was running even after 5mins sometimes

JIRA : https://issues.cask.co/browse/CDAP-5734

### CODE REVIEW

**Comment by anwar6953** [comment]
Local jobs shouldn't take 5+ minutes, right? Doesn't that potentially indicate some other issue?

**Comment by gsps1** [comment]
this happens when the build machines are really slow. typically towards the release. i couldn't reproduce the issue on my local machine ( successful on repeated runs > 100) .

**Comment by gsps1** [comment]
Also i noticed for spark programs we use timeout of 10mins in other tests. so its not uncommon to wait up to 10min for completion.

**Comment by anwar6953** [comment]
lgtm

**Pull request merged**
